### ISSUE TITLE
Autofill has stopped working across all sites in Firefox on Linux

### ISSUE THREAD

**Issue by mashedkeyboard** [bitwarden/clients#10815]
### Steps To Reproduce

1. Go to any site with a login field
2. Open the browser extension and log in, with the normal expected relatively long loading time
3. Click either an existing configured login, or click a login and select "Autofill"
4. Observe the "Unable to fill selected login item on this page" error message, for any page, on any website
5. Close the browser extension
6. Observe that the browser extension icon does not show the number of logins registered on this site
7. Open the browser extension
8. Observe that the browser extension takes the same time to load as it did the first time around

### Expected Result

Successful autofill on any site, especially sites that have previously worked on the same Firefox/Linux setup, and continue to work on other platforms (e.g. Windows and Android)

### Actual Result

Autofill appears to be broken, as does the Bitwarden extension's icon representation of the number of registered logins for a site, and the in-memory vault storage (perhaps relatedly?)

### Additional Context

A number of other users have also been reporting this same issue on the Bitwarden forum: https://community.bitwarden.com/t/autofill-no-longer-works-on-windows-firefox/71481/4

### Operating System

Linux

### Operating System Version

Manjaro 6.1.103-1-MANJARO x86_64; other users report on Fedora 40 and Ubuntu 22

### Web Browser

Firefox

### Browser Version

129.0.1; other users report on 129.0.2

### Build Version

2024.8.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by JABirchall** [comment]
Link #10814

**Comment by mashedkeyboard** [comment]
During the "long loading time" phase, I get this output in the browser console:


```
State version: 66 2 [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
Waiting for migrations to finish, waiting for 4ms [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
State version: 66 [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
Waiting for migrations to finish, waiting for 8ms [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
State version: 66 [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
Waiting for migrations to finish, waiting for 16ms [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
State version: 66 [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
Waiting for migrations to finish, waiting for 32ms [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
State version: 66 [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
Waiting for migrations to finish, waiting for 64ms [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
State version: 66 [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
Waiting for migrations to finish, waiting for 128ms [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
State version: 66 [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
Waiting for migrations to finish, waiting for 256ms [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
State version: 66 [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
Waiting for migrations to finish, waiting for 512ms [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
State version: 66 [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
Waiting for migrations to finish, waiting for 1024ms [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
State version: 66 [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
Waiting for migrations to finish, waiting for 2048ms [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
State version: 66 [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
Waiting for migrations to finish, waiting for 4096ms [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
State version: 66 [main.js:1:11296](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
Waiting for migrations to finish, waiting for 8192ms [main.js:1:1129](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/main.js)
```

Each time I press "Autofill", along with the standard Bitwarden error that appears in the GUI, I get this output in the console, which seems probably irrelevant but just mentioning in case:

```
Error in parsing value for ‘width’.  Declaration dropped. 6 [index.html:1:1](moz-extension://f268e982-2774-4855-bde8-935288674b81/popup/index.html)
```

**Comment by ashjaylk** [comment]
Also affecting Chrome and Edge on Fedora

![image](https://github.com/user-attachments/assets/8d176125-109b-4438-b398-b202d503ed13)
![image](https://github.com/user-attachments/assets/e5dd61b5-6883-462c-b80c-02d89362ae3c)

Microsoft Edge
Version 128.0.2739.42 (Official build) (64-bit)

**Comment by JABirchall** [comment]
> Also affecting Chrome and Edge on Fedora
> 
> ![image](https://private-user-images.githubusercontent.com/77319819/363385593-8d176125-109b-4438-b398-b202d503ed13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDY2MjUsIm5iZiI6MTcyNTEwNjMyNSwicGF0aCI6Ii83NzMxOTgxOS8zNjMzODU1OTMtOGQxNzYxMjUtMTA5Yi00NDM4LWIzOTgtYjIwMmQ1MDNlZDEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEyMTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYWYzYmI3YjcyY2FlZWNiNDg5NDM1ODM1ZTRjNWRkYjVkMjQ2MjgyMzQ4OTc1NjU4ODg4ZmRlMjllMDZmZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e2-fg0mB63b0Nx1oarf2YsGzdUJxT5kBVnTXI0cxFX0) ![image](https://private-user-images.githubusercontent.com/77319819/363385679-2134cf9b-8c75-41e7-96e9-514becc495d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDY2MjUsIm5iZiI6MTcyNTEwNjMyNSwicGF0aCI6Ii83NzMxOTgxOS8zNjMzODU2NzktMjEzNGNmOWItOGM3NS00MWU3LTk2ZTktNTE0YmVjYzQ5NWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEyMTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYTdjODJiNDFjZTg2NDcwOGZhNWE1ODVhMzFmMzZiNzRhYTU1Y2M3NDZkODYwZWM3YTQyZWEyMDM5YThhMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gYIMVnZFF8Z5eHw5X1p0dzpiHIaTWKCbaGhSXHhllVY)
> 
> Microsoft Edge Version 128.0.2739.42 (Official build) (64-bit)

So this is more wide spread to other browsers tooo.

**Comment by Ac1dg0sling** [comment]
> > Also affecting Chrome and Edge on Fedora
> > ![image](https://private-user-images.githubusercontent.com/77319819/363385593-8d176125-109b-4438-b398-b202d503ed13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDY2MjUsIm5iZiI6MTcyNTEwNjMyNSwicGF0aCI6Ii83NzMxOTgxOS8zNjMzODU1OTMtOGQxNzYxMjUtMTA5Yi00NDM4LWIzOTgtYjIwMmQ1MDNlZDEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEyMTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYWYzYmI3YjcyY2FlZWNiNDg5NDM1ODM1ZTRjNWRkYjVkMjQ2MjgyMzQ4OTc1NjU4ODg4ZmRlMjllMDZmZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e2-fg0mB63b0Nx1oarf2YsGzdUJxT5kBVnTXI0cxFX0) ![image](https://private-user-images.githubusercontent.com/77319819/363385679-2134cf9b-8c75-41e7-96e9-514becc495d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDY2MjUsIm5iZiI6MTcyNTEwNjMyNSwicGF0aCI6Ii83NzMxOTgxOS8zNjMzODU2NzktMjEzNGNmOWItOGM3NS00MWU3LTk2ZTktNTE0YmVjYzQ5NWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEyMTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYTdjODJiNDFjZTg2NDcwOGZhNWE1ODVhMzFmMzZiNzRhYTU1Y2M3NDZkODYwZWM3YTQyZWEyMDM5YThhMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gYIMVnZFF8Z5eHw5X1p0dzpiHIaTWKCbaGhSXHhllVY)
> > Microsoft Edge Version 128.0.2739.42 (Official build) (64-bit)
> 
> So this is more wide spread to other browsers too. Is the context menu on forms also missing?

I checked Edge, chrome, brave, arc all of these browsers are having the same issue with bitwarden extension on Windows10/11 IOT LTSC.

**Comment by mashedkeyboard** [comment]
This seems to have resolved for me after a clean reinstall of the extension, removing the data from the Firefox profile. I wonder given the migration messages whether this relates to a change in the extension's internal storage schema or something in the last version, breaking upgrades but meaning new installs are OK?

**Comment by JABirchall** [comment]
> I started having the same problem with the latest version on Brave on Linux. It would log in, but would not autofill and neither would it sync the vault. If I deactivated and reactivated the extension, it started working until the next browser restart. It is not doing this with the older version of the extension on my Vivaldi browser.


Ahh crap, no syncing might be a problem, ive already added new passwords manually since this started happening.

**Comment by Danie10** [comment]
Nope for me uninstalling the extension and removing data, restarting browser and re-installing extension, still produces the no sync issue.

Worse, Vivaldi just updated the extension to v2024.8.1, and I have the same problem there now. I need to somehow revert to the 2024.7.x version otherwise I may be pretty stuck as every password I have is inside Bitwarden.

**Comment by ashjaylk** [comment]
I also can confirm that reinstalling Bitwarden extensions on chromium browsers resolved the issue

**Comment by StefanBrand** [comment]
> If you have more information that can help us, please add it below.

I have this issue with 

- Bitwarden extension Version: 2024.8.1
- Firefox 129.0.2 installed via Snap
- Ubuntu 24.04.1 LTS

**Comment by fixator10** [comment]
Same on Opera on Windows
* Extension 2024.8.1
* Opera 113.0.5230.47
* Windows 10.0.19045

Autofill in context menu seems to believe that every input field is on `google.com`

**Comment by Aldjinn** [comment]
Same here as well with today's new Firefox.

* Extension 2024.8.1
* Firefox 130.0
* Windows 11 23H2 22631.4112

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
I'm seeing the same thing on Fedora 40.  Firefox is 129.0.2, Extension 2024.8.1.

**Comment by Jaakkonen** [comment]
Also experiencing this. Firefox developer edition 130.0b7 and extension 2024.8.1 on Arch Linux.

I'm surprised that there's no integration test to test for this kind of regressions in the pipeline. Just paid for my annual subscription...

**Comment by JABirchall** [comment]
> I've logged it at their Help Centre now and mentioned this issue as it has not been allocated to anyone yet.

From what I know, no one is able to replicate it, as it doesnt happen on a fresh install (which tests typically mimic). This regression from old installs.

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
> So unless we can find a method to replicate the issue on a fresh install, it likly wont get patched.

Unfortunately -- at least for me -- re-install does not fix it.

**Comment by Aevrin** [comment]
Did anyone try a firefox reinstall?  Clearing all temp files and such?

**Comment by Aevrin** [comment]
I manually deleted the extension folders in C:\Users\$User\AppData\Roaming\Mozilla\Firefox\Profiles\$Profile\storage\default removed and reinstalled, and it's now working.

**Comment by Aldjinn** [comment]
For me with Firefox on Windows, just removing and adding the addon again fixed it.

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
> I manually deleted the extension folders in C:\Users$User\AppData\Roaming\Mozilla\Firefox\Profiles$Profile\storage\default removed and reinstalled, and it's now working.

This fixed it for me too.  Just removing the plugin from Firefox did not remove the package from the filesystem.  Manually deleting the file from ~/.mozilla/firefox/<profile>/extensions resolved the issue.

**Comment by StefanBrand** [comment]
After restarting the computer it now works again. I noticed that I had a mismatch of "Version" and "Server version" before (Server version was still 2024.8.0):

![image](https://github.com/user-attachments/assets/5b719efe-75db-4d6e-b94f-0910ebb0c5b2)

Now the two versions match again.

**Comment by Lantau** [comment]
I'm encountering the problem about 50% of the time I start Firefox. I've noticed that when Firefox starts, if the lock symbol on the Bitwarden icon for the extension is present then operation is normal, i.e. I have to log into Bitwarden and it works correctly. However, sometimes the lock is not present on starting Firefox , even if I have not yet logged into Bitwarden.  Selecting the icon will bring up the master password prompt. After login the logins are visible but there's no auto fill. 
I hope this adds a bit more info. 
Ubuntu 20.04.6 LTS
129.0.2 (64-bit)
Bitwarden Version: 2024.8.1

**Comment by MrAlucardDante** [comment]
Locking the vault in the extension fixed it for me on Windows 11 and Firefox 130. But maybe it's only a temporary fix and it might end up reappearing.

> mimi

So, this basically means that no one at Bitwarden is using Bitwarden, which I highly doubt.

**Comment by jdambron** [comment]
I had the same problem with:

- Extension 2024.8.1
- Firefox 130.0
- Arch Linux

Just removing and reinstalling the extension did not work.
Removing the extension and cleaning the  folder like https://github.com/bitwarden/clients/issues/10815#issuecomment-2329060731 worked :heavy_check_mark:

**Comment by likwidoxigen** [comment]
I had this issue yesterday. I fixed it with the uninstall and re-install.  And today it's broken again.

- Extension 2024.8.1
- Firefox 130.0
- Windows 10

**Comment by Danie10** [comment]
Now working on Brave Beta for me from today - deleted the extension again, and reinstalled, and noted the extension version matches the server version.

**Comment by EventHorizonsEngineering** [comment]
Started with me a few days ago.  Found this thread after restarts of Firefox did nothing.
Disabling and re-enabling extension did not work.

Uninstalled and re-installed extension.  Worked, even after a restart of Firefox.

Rocky (RHEL) 9.4  (Linux 5.14.0-427.28.1.el9_4.x86_64 x86_64)
Firefox 115.13.0esr (64-bit)

**Comment by JABirchall** [comment]
> Started with me a few days ago. Found this thread after restarts of Firefox did nothing. Disabling and re-enabling extension did not work.


Yea disabling and reenabling the extension fixes the issue until you close and reopen firefox.

**Comment by thezoggy** [comment]
and another one here, bitwarden was fine on firefox 129.x, then as soon as I updated to firefox 130 autofill stopped working

    Extension 2024.8.1
    Firefox 130.0
    Windows 10

**Comment by arnelap** [comment]
I thought reinstalling solved it, but it did not. Only directly after the install it worked, but after a restart the issue was back again and I don't have auto-fill unless i reinstall again. 

I tried deleting the extension folder from my home folder, and then install fresh, no difference. 

Linux Firefox 129.0.1 , Bitwarden  2024.8.1

**Comment by arnelap** [comment]
I thought reinstalling solved it, but it did not. Only directly after the install it worked, but after a restart the issue was back again and I don't have auto-fill unless i reinstall again. 

I tried deleting the extension folder from my home folder, and then install fresh, no difference. 

Linux Firefox 129.0.1 , Bitwarden  2024.8.1


This is what I get in the extension debugger when I turn off and back on tthe bitwarden extension


**Uncaught (in promise) TypeError: null has no properties
    injectAutofillScriptsInAllTabs autofill.service.ts:2779**


```

This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
[background.html](moz-extension://c8f353b7-09b4-4347-b5ee-d371b4f30bf6/background.html)
State version: 68 [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator lp (to version 3) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Od (to version 4) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator mu (to version 5) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator nh (to version 6) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator ip (to version 7) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator rp (to version 8) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator op (to version 9) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Ul (to version 10) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator El (to version 11) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator zl (to version 12) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Bl (to version 13) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Wl (to version 14) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Gl (to version 15) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Ql (to version 16) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator ec (to version 17) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator nc (to version 18) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator oc (to version 19) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator cc (to version 20) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator hc (to version 21) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator vc (to version 22) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator wc (to version 23) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Pc (to version 24) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Oc (to version 25) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Dc (to version 26) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Uc (to version 27) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Ec (to version 28) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Rc (to version 29) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Vc (to version 30) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator $c (to version 31) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator qc (to version 32) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Zc (to version 33) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator nd (to version 34) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator od (to version 35) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator cd (to version 36) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator hd (to version 37) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Sd (to version 38) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator kd (to version 39) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Nd (to version 40) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Md (to version 41) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Kd (to version 42) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator _d (to version 43) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator jd (to version 44) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Yd (to version 45) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Xd (to version 46) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator du (to version 47) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator pu (to version 48) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator gu (to version 49) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Pu (to version 50) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Ou (to version 51) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Au (to version 52) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Uu (to version 53) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Mu (to version 54) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Vu (to version 55) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator ju (to version 56) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Gu (to version 57) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Qu (to version 58) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator th (to version 59) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator lh (to version 60) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator yh (to version 61) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Ph (to version 62) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Ah (to version 63) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Th (to version 64) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Bh (to version 65) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Gh (to version 66) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator Qh (to version 67) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Migrator ep (to version 68) should migrate: false - up [console-log.service.ts:43:16](webpack:///libs/common/src/platform/services/console-log.service.ts)
Uncaught (in promise) TypeError: null has no properties
    injectAutofillScriptsInAllTabs autofill.service.ts:2779
    o background.js:1
    promise callback*l background.js:1
    o background.js:1
    promise callback*l background.js:1
    o background.js:1
    promise callback*l background.js:1
    o background.js:1
    promise callback*l background.js:1
    o background.js:1
    promise callback*l background.js:1
    o background.js:1
    promise callback*l background.js:1
    fC background.js:1
    fC background.js:1
    injectAutofillScriptsInAllTabs background.js:1
    loadAutofillScriptsOnInstall autofill.service.ts:123
    fC background.js:1
    fC background.js:1
    loadAutofillScriptsOnInstall background.js:1
    checkOnInstalled runtime.background.ts:360
    WI background.js:1
    WI background.js:1
    checkOnInstalled runtime.background.ts:358
    setTimeout handler*38249/checkOnInstalled/< runtime.background.ts:358
    WI background.js:1
    WI background.js:1
    checkOnInstalled background.js:1
    init runtime.background.ts:64
    WI background.js:1
    WI background.js:1
    init background.js:1
    bootstrap main.background.ts:1203
    o background.js:1
    promise callback*l background.js:1
    o background.js:1
    promise callback*l background.js:1
    o background.js:1
    promise callback*l background.js:1
    o background.js:1
    promise callback*l background.js:1
    o background.js:1
    promise callback*l background.js:1
    HI background.js:1
    HI background.js:1
    bootstrap background.js:1
    38249 background.ts:12
    Webpack 5
[autofill.service.ts:2779:40](webpack:///src/autofill/services/autofill.service.ts)

> ​
```

**Comment by arnelap** [comment]
I may have found something. 

I changed the algorithm from PBKDF2 with 600000 iterations to Argon2id with 64mb ram, and the last few browser restarts Bitwarden has worked consistently without needing to turn off and on the extension.

**Comment by JABirchall** [comment]
> I may have found something.
> 
> I changed the algorithm from PBKDF2 with 600000 iterations to Argon2id with 64mb ram, and the last few browser restarts Bitwarden has worked consistently without needing to turn off and on the extension.
> 
> based on suggestion here: [bitwarden/ios#820](https://github.com/bitwarden/ios/issues/820)

Ive been using Argon from the start.

**Comment by jdambron** [comment]
> > I may have found something.
> > 
> > I changed the algorithm from PBKDF2 with 600000 iterations to Argon2id with 64mb ram, and the last few browser restarts Bitwarden has worked consistently without needing to turn off and on the extension.
> > 
> > based on suggestion here: [bitwarden/ios#820](https://github.com/bitwarden/ios/issues/820)
> 
> Ive been using Argon from the start. 

Same here.

**Comment by JABirchall** [comment]
Ive determined the issue is with the new Autofill UI they released in 2024.8.1
See: https://github.com/bitwarden/clients/issues/10814#issuecomment-2334831100

**Comment by eylenburg** [comment]
Same problem for me on Windows + Firefox. Nothing to do with Linux specifically. Also I am unable to lock the vault or log out. 

I deleted the extension and reinstalled and logged in again and now it shows me the autofill 'numbers' (like the small 1 if I have an account on the website). But who knows how long it'll last...

**Comment by Tea23** [comment]
Seems to be fixed in 2024.8.2

**Comment by WrichikBasu** [comment]
Yep, the issue seems to have been resolved in the latest version; can finally autofill as usual. Thank you devs!

**Comment by Danie10** [comment]
IT only worked for me for a short bit after re-installing the extension. The same is still happening with v2.9.0 too on both Brave and Vivavldi. I did delete the extension yesterday and reinstalled, but today again no autofill. Also notice it takes quite a while to login.

**Comment by WrichikBasu** [comment]
Gonna take back my previous comment. It worked fine in 8.2, but not in 9.0. Same issue as 8.1.

**Comment by DrPhil** [comment]
I have the same issue.
Version: 2024.9.0

**Comment by solonovamax** [comment]
Disabling then re-enabling the extension did not fix it for me.
_However_, going to `about:addons` -> Bitwarden -> Permissions and then toggling "Exchange messages with programs other than Firefox Developer Edition" ("Firefox Developer Edition" will be replaced by whatever the name of your firefox browser is. eg. "Firefox", "Firefox Developer Edition", "Librewolf", etc.) seemed to fix it for me.
It may have something to do with the permissions being bugged somehow and toggling this reloaded the permissions, fixing them. Unsure.

**Comment by arnelap** [comment]
Enabling "Exchange messages with program" did not solve the issue for me. 

Closing and then re-opening my browser after reboot does "solve" the issue. 
I'm not sure why/how that could be, but I open my browser, wait for bitwarden to load, then close the browser (count to 10 to make sure the background process is fully terminated) then re-open the browser, and then bitwarden works normally. 


After I reboot my device I need to do this again.

**Comment by cagonzalezcs** [comment]
@mashedkeyboard  Thank you for this bug report. This appears to be a duplicate of the problem described in #10814 , [please see this comment for details surrounding the problem](https://github.com/bitwarden/clients/issues/10814#issuecomment-2359336680).

As this is a duplicate, I'm closing this thread for now to focus discussion within the Github issue mentioned above. Please feel free to continue discussion there.
