### ISSUE TITLE
Command Line Interface Not properly signed on macOS.

### ISSUE THREAD

**Issue by johnappletree** [bitwarden/clients#11169]
### Steps To Reproduce

1. Download the latest bw cli client from the bitwarden website.
2. Unzip the archive and execute the bw executable.

### Expected Result

A signed exexutable that is compliant with apple's gatekeeper default settings.

### Actual Result

Error message when launching the executable: Apple could not verify "bw" is free of malware that may harm your Mac or compromise your privacy.

--> How can I make sure this download/executable has not been compromised?

### Screenshots or Videos

<img width="262" alt="Screenshot 2024-09-20 at 13 09 20" src="https://github.com/user-attachments/assets/077f8ebd-cf8d-42ce-a9ca-dd26100a10d1">

### Operating System

macOS

### Operating System Version

15.0 (24A335) - This issue is also relevant for previous macOS releases.

### Shell

Zsh

### Build Version

2024.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by RedMageKnight** [comment]
Hi @NovaSilentium,

I just wanted to report that I also experienced issues signing into the CLI on Windows as well with 2024.9.0 - being flagged as malware which is causing an extension I've been working with that uses the CLI to login via API to fail. 2024.8.2 does not experience this issue. I'm running Windows 11, and I use only Windows Defender as my built in AV. 

Even unblocking the executable which was only possible after turning off the on-demand active scan process still results in the CLI to fail to authenticate. Just wanted to throw my hat in due to the similarities in the CLI executable being recognized as malware at the OS level.

**Comment by johnappletree** [comment]
Update from my side: the issue is still present in version 2024.10.0.

**Comment by acouvreur** [comment]
Same issue

**Comment by nguyenvulong** [comment]
same issue on MacOS M1 pro chip

**Comment by dwbit** [comment]
The CLI will be signed moving forward, thanks for your patience everyone!

**Comment by davidraedev** [comment]
I tried out the latest version 2025.2.0, and I still got an error, although I am allowed to manually override in Settings whereas the previous version did not have that option

Intel 15.3

```
% spctl -a -v  /usr/local/sbin/bw
/usr/local/sbin/bw: rejected
```

<img width="494" alt="Image" src="https://github.com/user-attachments/assets/55072818-2838-4ef4-84ba-95ff8fee4a86" />

**Comment by Mikaoj2077** [comment]
Also have this issue on a MacBook Pro with intel chip

**Comment by Jdahn** [comment]
@dwbit, I just tested version 2025.5.0, the issue is still present on my side. Could you please elaborate what you mean with your comment "CLI will be signed moving forward"

Thanks!

**Comment by coroiu** [comment]
This has been fixed as part of https://github.com/bitwarden/clients/pull/15132 which will be pushed out with the next release!

The issue was caused by the CLI not being signed. Apple made signing a requirement which caused all versions of the CLI to be blocked from executing.

I'm closing the issue but please let us know if the issue persists!

**Comment by johnappletree** [comment]
Reopening this issue since the issue is still present, and in my opinion never has been fixed. I tried following version bw-macos-2025.8.0 

--> apparently I am not allowed to reopen this issue.

**Comment by Jdahn** [comment]
Hi @NovaSilentium, @coroiu, could you please reopen this issue? It is not solved, i just checked version 2025.11.0 and the issue is still present in the Bitwarden CLI Package! :-/
I am on 26.1 (25B78)

<img width="276" height="247" alt="Image" src="https://github.com/user-attachments/assets/216941d9-73cc-4c38-98f4-6a95be865ac7" />
