### ISSUE TITLE
Cannot add account, nor display accounts added via brower extension

### ISSUE THREAD

**Issue by gm-s** [bitwarden/clients#11698]
### Steps To Reproduce

1. Click on your username in the upper right corner
2. Click "+Add account"
3. Enter the email address of another Bitwarden account and click "Continue"
4. Enter the password for that account and click "Login with master password"

### Expected Result

You should be presented with a screen that asks for a code from your authentication app.

### Actual Result

The wait cursor just spins for a minute or two and then stops.  The attempt to add another account has failed at this point.

### Additional Context

I am able to add accounts via the browser extension, which works fine.  However, accounts added that way do not appear in the desktop app.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NeverToOldToLearn** [comment]
Similar problem. Yet only desktop variation. Webvault and app are working. Desktop a no go for me at least.

**Comment by sammbw** [comment]
Hello @gm-s,

This was likely due to a temporary issue that has been resolved since - could you test this once more and check if you're able to add your secondary accounts now?

If not, please get in touch with support using the link below.

Contact Bitwarden: https://bitwarden.com/contact/

Thanks!

**Comment by gm-s** [comment]
Still not working properly.  I will contact support via the link you provided.
