### ISSUE TITLE
In Admin Console item names disappear when the window becomes narrower than a certain limit

### ISSUE THREAD

**Issue by poglazov** [bitwarden/clients#11772]
### Steps To Reproduce

1. Go to Admin Console - Collections.
2. Narrow the window.

### Expected Result

Item names in the table remain

### Actual Result

Item names in the table disappear

### Screenshots or Videos

[Screencast from 29.10.2024 19:54:45.webm](https://github.com/user-attachments/assets/685caac0-c400-4205-8daf-1cefc531c5f2)

### Additional Context

This problem is even worse on a phone: since the width of the phone screen is limited, it is impossible to see the names of items at all!

Sad to discover this after I implemented Bitwarden for 60 employees.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.5 LTS

### Web Browser

Chrome

### Browser Version

Version 130.0.6723.58 (Official Build) (64-bit)

### Build Version

2024.10.3

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by ketanMehtaa** [comment]
I think this issue is resolved , checked in web.

**Comment by poglazov** [comment]
> I think this issue is resolved , checked in web.

No, the problem is definitely still present.

I even changed the laptop, OS and web browser, and the problem is still here:

https://github.com/user-attachments/assets/4d0164f4-02ac-431d-9ba8-82b5bf0418c1

For today's video:
### Operating System
Linux
### Operating System Version
Debian GNU/Linux 13 (trixie)
### Web Browser
Firefox
### Browser Version
128.11.0esr (64-bit)
### Build Version
2025.6.0

@ketanMehtaa if you see that the problem has been fixed on your laptop, could you please record the same screencast, as well as provide information about the environment?

**Comment by ketanMehtaa** [comment]
> > I think this issue is resolved , checked in web.
> 
> No, the problem is definitely still present.
> 
> I even changed the laptop, OS and web browser, and the problem is still here:
> 
>  video_2025-06-16_15-10-18.mp4 
> For today's video:
> 
> ### Operating System
> Linux
> 
> ### Operating System Version
> Debian GNU/Linux 13 (trixie)
> 
> ### Web Browser
> Firefox
> 
> ### Browser Version
> 128.11.0esr (64-bit)
> 
> ### Build Version
> 2025.6.0
> 
> [@ketanMehtaa](https://github.com/ketanMehtaa) if you see that the problem has been fixed on your laptop, could you please record the same screencast, as well as provide information about the environment?

you are using self hosted version ?

**Comment by ketanMehtaa** [comment]
I am able to see this problem in Trash folder.

**Comment by poglazov** [comment]
> you are using self hosted version ?

No, I'm using the cloud version, https://vault.bitwarden.com/.
