### ISSUE TITLE
Password generator history on edge extension generating passwords every few seconds

### ISSUE THREAD

**Issue by snowdej** [bitwarden/clients#12047]
### Steps To Reproduce

using Version 131.0.2903.51 edge
using edge bitwarden 2024.11.1
go to password generator
go to history

### Expected Result

Only passwords you asked to generate

### Actual Result

passwords generated every few seconds

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/39b01678-f413-43ba-9a7f-85947cf4f2d9)

### Additional Context

does not happen in firefox on same device
does not happen in mobile app on android

### Operating System

Windows

### Operating System Version

24h2 26100.2314

### Web Browser

Microsoft Edge

### Browser Version

Version 131.0.2903.51

### Build Version

2024.11.1 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a previously generated passwords. Every time you pop in and out of the generator tab a new password is generated.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

**Comment by daniellbw** [comment]
Hi @snowdej ,

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you have any additional information you would like to add here, please do!

**Comment by masgyro** [comment]
This also happens on my Windows 11 Firefox. Edge/Chrome don't 't seem to have the same issue for me so I'm guessing it's actually NOT browser dependent?

**Comment by masgyro** [comment]
Oops, spoke too soon. It also impacts Chrome.

@daniellbw This should be fixed as a high priority item, yes? I imagine it takes a lot of system resource for this to run continuously...

**Comment by madrugal** [comment]
This bug is also affecting me. Firefox on Windows 11.

Besides auto-generating a password every few seconds, I'm unable to adjust the generation settings.

**Comment by Kobberholm** [comment]
Can confirm same issue exists with Bitwarden version 2024.11.0 in Firefox 132.0.2 on Linux/KDE Neon 6.0 (based on Ubuntu 22.04).

**Comment by ozskywalker** [comment]
Can confirm same issue with Bitwarden version 2024.11.0 in Edge 130.0.2849.90 & Firefox 133.0 on macOS.  Trying to nail it down, but it seems to be generating a suggested password every time it's encountering a password field (hidden or shown), and without being prompted to do so.

**Notes**
- Bitwarden is on default settings.
- Disabling "Show context menu options" had no effect.
- Doesn't appear to be resource intensive.

**Steps to reproduce:**
1. Open browser tab and navigate to page with known password field
2. Open bitwarden extension, go to Generate
3. Go to History
4. You should see 2x entries - 1x from when you clicked Generate, and 1x from the time you navigated to the page seconds before.

**Impact to User**
Over time the browser will have encountered a sufficient number of password text fields resulting in the generated password history being "spammed".  This especially breaks the use case of User saving password after account creation.

When a User uses BItwarden to inject a suggested (generated) password for new account creation, and if Bitwarden did not prompt to save on the next page, the user will try to retrieve the generated pwd via history, only to become confused & unable to distinguish which password was used for their new account.

See image as example
![image](https://github.com/user-attachments/assets/85ccbc8a-3142-4e4a-94e1-fa1b0682ea4d)

**Comment by jma4th** [comment]
Same issue.  Using Thorium Version 122.0.6261.132 on Windows 10.  Generates 25-50 passwords per request.  I have a few hundred from just today.  Might be related to Fill Generated Password feature since it has only recently became automatically visible on log-in pages.
![Screenshot 2024-11-29 125432](https://github.com/user-attachments/assets/2f8e4524-e730-4646-9f1b-5620c7f5fdd4)
![Screenshot 2024-11-29 125427](https://github.com/user-attachments/assets/6b5b3f02-3fcc-4222-ba8e-8b1d74ead1d3)
![Screenshot 2024-11-29 125419](https://github.com/user-attachments/assets/3fc63574-8afa-401c-a52c-126408870456)
![Screenshot 2024-11-29 125336](https://github.com/user-attachments/assets/beb7d615-ac93-48b4-8933-5db0fb7822eb)

**Comment by dev1anceONE** [comment]
Chrome 131.0.6778.86 and Bitwarden 2024.11.2 and same problem like other people, i think is problem related to that new "fill generated password" feature, because that generate every password after page refresh(so if i go to on some forum from page 1 to page 2 this will generate new password)

**Comment by Taomyn** [comment]
Does this issue explain why on many sites when I first click on the password field it shows this:
![image](https://github.com/user-attachments/assets/dff8afb4-b095-4419-b3a4-4088fbfaae6e)

It's happening to me on both Edge and Brave browsers, but has so far never actually changed the site's password.

**Comment by ivntrdata** [comment]
This is still an ongoing issue that's present in Brave browser as I've tested. I noticed that the replication for me seems to be dependent on browsing the web. If you just sit at a single page waiting and doing nothing no additional passwords are generated. But if you unlock Bitwarden and then browse the web, click on links...etc. Then check the password history after a few minutes there's a ton of passwords generated.

**Comment by aaronblair** [comment]
Still getting this issue in Chrome

**Comment by masgyro** [comment]
Yep - still exist in Firefox and Edge as well.

**Comment by dev1anceONE** [comment]
> Still getting this issue in Chrome



> Yep - still exist in Firefox and Edge as well.

Because they still don't release update, that issue was present in 2024.11.2 and newest version is 2024.11.2, maybe they will release in few days before holiday version 2024.12.0 with fixed that issue

**Comment by jprusik** [comment]
Apologies for not updating here sooner; correct, the fix isn't in production builds yet. However, the it will be in the next (forthcoming) release.

**Comment by huksley** [comment]
What is the estimated release schedule for this?

It still very painful to use generated passwords. 

My previous workflow was to generate password, copy and login into the service, AND afterwards go into bitwarden to save that generated password as a new login. This was convenient becase when you register/login you might use copy buffer many times for different things - email address, address, phone number etc. 

This workflow is not possible anymore, since the password used are lost in tenths of generated passwords. 
It results in the need to **reset** the password immediately after registering/changing the password.

This is also made worse by Bitwarden being unable to detect new login and present a **Save this password** prompt.

**Comment by ozskywalker** [comment]
@huksley spoke to Bitwarden Support, and while they can't provide an exact day, they indicated this should be fixed sometime between tomorrow & next week. I do want this fix too, but I'd rather their QA process vet the browser plugin first before it gets released.

**Comment by huksley** [comment]
This is ridiculous, one month passed and the official extension still not fixed (Firefox) 
![image](https://github.com/user-attachments/assets/63697d3b-d4f0-475e-84dc-b70f8fa0fd78)

**Comment by dev1anceONE** [comment]
> This is ridiculous, one month passed and the official extension still not fixed (Firefox) ![image](https://private-user-images.githubusercontent.com/1594349/397971858-63697d3b-d4f0-475e-84dc-b70f8fa0fd78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NzA0MDEsIm5iZiI6MTczNDg3MDEwMSwicGF0aCI6Ii8xNTk0MzQ5LzM5Nzk3MTg1OC02MzY5N2QzYi1kNGYwLTQ3NWUtODRkYy1iNzBmOGZhMGZkNzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjJUMTIyMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmMxMjdkY2JlNDMwNDlmMDE1MjhkYTU0ZjE3NDYwNTk3MzQ1NTlhOTExNjNhZWRkNjdjYWQ3MzFmZjVkZDZhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.c8RBS0SVj9Fdk4zHjPwgEJ7EFZWOnbVYI4kZ_XmtcXY)
Its because u use old extension version, here what u should have 2024.12.x - 
![image](https://github.com/user-attachments/assets/d1baf213-de7b-431f-9676-8c010c2a5128)
Probably Mozilla didn't aprove new extension yet, u can try sideload version from here https://github.com/bitwarden/clients/releases

**Comment by ivntrdata** [comment]
I can confirm that this is fixed in the most recent version on Brave browser.

**Comment by jprusik** [comment]
Hi @Dex321x - are you still seeing issues? I am testing on Brave Version 1.73.105 Chromium: 131.0.6778.265 and Bitwarden version 2025.1.0 and am unable to reproduce the original issue. You might try updating both and seeing if that helps

**Comment by Taomyn** [comment]
> Hi [@Dex321x](https://github.com/Dex321x) - are you still seeing issues? I am testing on Brave Version 1.73.105 Chromium: 131.0.6778.265 and Bitwarden version 2025.1.0 and am unable to reproduce the original issue. You might try updating both and seeing if that helps

I cannot get 2025.1.0 to appear, I'm using the Google Chrome store and Brave browser. Even checking on the store does not show it as the latest version, same for Firefox:

![Image](https://github.com/user-attachments/assets/74564d96-09d9-49ec-a58d-39b11ca3b410)

**Comment by aussiedean** [comment]
I use Brave as well and in a bit of a predicament as the problem described above has not allowed me to find a master password the I did via the generator and none of them work. 

I changed the master password and it didn't offer to update it and I didn't look at it till too late. 

Is there a way to find more history somehow apart from whats on the browser app list?
