### ISSUE TITLE
Families 2019 owned organization items premium features not working in web extension and web application.

### ISSUE THREAD

**Issue by pcartwright81** [bitwarden/clients#12458]
### Steps To Reproduce

1. Go to an item owned by an organization
2. Look at TOTP and see premium.

### Expected Result

TOTP is displayed

### Actual Result

TOTP says premium

### Screenshots or Videos

<img width="311" alt="image" src="https://github.com/user-attachments/assets/30bc586c-b9d5-4e77-abbb-7aab29798204" />

<img width="273" alt="image" src="https://github.com/user-attachments/assets/7cd21b2c-f968-4f99-bd8d-186c2eaa36f0" />

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2024.12.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by pcartwright81** [comment]
Did you try with a Families 2019 organization that does not give premium to each user?  Support was not helpful before and kept telling me to buy premium for TOTP. If the Families 2019 is not going to work properly then maybe my subscription should not have been renewed.

<img width="271" alt="image" src="https://github.com/user-attachments/assets/9eac897d-8c1c-4367-868d-fdc099c92481" />
<img width="275" alt="image" src="https://github.com/user-attachments/assets/61ff4e63-3a30-435f-bd08-f553e4c5d011" />

**Comment by jtodddd** [comment]
Hi there,

While I am unable to reproduce this issue, we have had other direct reports so I will reopen this case for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by dzaggiel** [comment]
Hello I struggle with this issue, I can give you all details which you need.

**Comment by mawd** [comment]
Hello same here. It is also the case for attachment.
However it is working in certain condition, I have described the use case on reddit : [](https://www.reddit.com/r/Bitwarden/comments/1hl8u3t/premium_tag_on_otp_for_familly_organization/)

**Comment by pcartwright81** [comment]
My workaround is this, and seems to work 100% of the time.
<img width="311" alt="image" src="https://github.com/user-attachments/assets/642e20ab-cebc-408f-943a-b76d2014afc2" />

**Comment by Simisticot** [comment]
Hello,

I am running into this same behavior specifically on the firefox extension, I have a premium subscription (not family). TOTP works fine on bitwarden.com and in the android app.
Workaround suggested by @pcartwright81 does not work in my case.

**Comment by jarrodjackson** [comment]
Members of my organization can no longer access Verification Codes (TOTP) for credentials stored in organization collections.
This seems to have started after the most recent update to the browser (Chromium) plugin.
Browser: Brave [Version 1.73.104 Chromium: 131.0.6778.204 (Official Build) (64-bit)](https://brave.com/latest/)
Plugin: [Version 2024.12.3](https://chromewebstore.google.com/detail/bitwarden-password-manage/nngceckbapebfimnlniiiahkandclblb)

We have had this paid Families organization since 2019 and have had access to Bitwarden Authenticator (TOTP) premium feature through the organization the entire time.

![BitwardenFamiliesOrganizationTOTPDisabled20241226_AnnotatedRedacted](https://github.com/user-attachments/assets/fee4aede-0a2a-4986-9ae2-f5d28779a928)

This specific item was created in August 2020 and was last edited June 2022. The copy TOTP button is greyed out in the plugin, disabled on the web app (through the item interface), and does not appear as an option when I right-click on the plugin interface. 

After looking at the workaround suggested by @pcartwright81, I successfully got TOTP codes through Safari browser (macOS) and the Android app (Version 2024.10.0 11270). I was also able to copy the TOTP code through the hamburger menu on the right side of the vault search results interface in the web app.

**Comment by bsteimel** [comment]
With the latest UI change in Android the workaround does not work.  There is no vertical ... I have had to revert back to Authy for Android.   I definitely won't renew until this is fixed.  I would say 75% of my usage is with the android application.

**Comment by rjtort** [comment]
I'm having this issue too. Families 2019 subscription. Firefox add-in version 2024.12.3.
If you click copy info > copy verification code, it works without issue. But if you click to view the login info via the extension, the TOTP is showing the premium badge, and won't let you copy it.

**Comment by NWItaly** [comment]
Any news? Is anyone working on this?

**Comment by pcartwright81** [comment]
> With the latest UI change in Android the workaround does not work. There is no option to copy TOCP on the search page and when you go into the item it says premium subscription required. I have had to revert back to Authy for Android. I definitely won't renew until this is fixed. I would say 75% of my usage is with the android application.
> 
> App version
> 
> Version: 2025.1.0 (19622) 📱 google Pixel 6 🤖 15@35 📦 prod local

This was for the browser, not the Android extension.  On that note my Android is working fine on the same version as yours.  I have noticed a few needed to be resaved for the copy to show up.

**Comment by bsteimel** [comment]
![Screenshot_20250112-190741](https://github.com/user-attachments/assets/01ec3804-fcbf-45b7-8d95-23ef94ad4f46)


Even after saving it shows this.

**Comment by demodigit92** [comment]
Please review this bug it's a must have for premium members

**Comment by beastarman74** [comment]
I am experiencing the same issue in the Android app, but not using family subscription just 2 Pro licenses. 

Had to create a copy of the impacted credentials in the each of our personal vaults to workaround this. As none of the suggested workaround are working for us.

This is a terribly impactful bug.

**Comment by nissim-c** [comment]
Having the same issue, though different clients. Premium account with a login + TOTP in a shared organization. Desktop/Firefox 2024.12.4 works fine, as before. But on Android, version 2025.10 (19622), no TOTP code for items in the shared org appear in the Verification Code screen, and navigating to a login has "Premium subscription required" in the TOTP field. Using the web vault on bitwarden.com correctly shows TOTP codes for the above items.
"Copy TOTP" menu item does not appear on mobile, so I can't figure out a workaround on Android.

**Comment by up-guillaume** [comment]
Hi guys,

Is this being taken care of seriously in the product development. With the recent updates on mobile, some of my employees have no workaround. I have been give the mission to find a replacement solution by next week may we cannot use our 2FA anymoe.

**Comment by chaseadam** [comment]
> My workaround is this, and seems to work 100% of the time. <img alt="image" width="311" src="https://private-user-images.githubusercontent.com/2352477/398425894-642e20ab-cebc-408f-943a-b76d2014afc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcxMTY1NDMsIm5iZiI6MTczNzExNjI0MywicGF0aCI6Ii8yMzUyNDc3LzM5ODQyNTg5NC02NDJlMjBhYi1jZWJjLTQwOGYtOTQzYS1iNzZkMjAxNGFmYzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTdUMTIxNzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2NjY2FjMTVjNDY5YTU2ZmZlY2M2M2JiYjEzM2RjNWE1MzQxN2UzNTEyY2Q2MzAwZDY2Njc3NzBiNzQ3YWZiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.J_Aqu5GHS50_1ym29HKRoW6kB0DrLuAOX_0lK1QKfSA">

This does not appear to work in 

![Image](https://github.com/user-attachments/assets/1075e86e-2bb1-48db-a61d-e313f9170a9b)

**Comment by shawnshyguy** [comment]
+1 on this issue (Support sent me here as well)

2 users with Premium accounts in the same free organization. I can access TOTP no issue, my partner can access TOTP codes via Web UI but not the Android app. Tried all the normal troubleshooting, reinstall / rejoin org / etc.

**Comment by GHM3434** [comment]
I have the same issue on browser extension self hosted. TOTP code field only has premium button and I can't see or copy and TOTP codes to login to my accounts.

**Comment by IgorCampbell** [comment]
Hello!
The Firefox extension is all right. My problem is on Android...

Version: 2025.1.0 (19622)
📱 samsung SM-S916B 🤖 14@34 📦 prod

**Comment by ROosterloo1988** [comment]
Here also problems with android!

**Comment by chrisstaite** [comment]
Going to throw my hat in the ring for the android app: 
Version 2025.1.0
com.x8bit.bitwarden

**Comment by gnr8shn** [comment]
We have a premium plan. We're using Organisations. Works fine on web, iOS. 

Android honours new TOTP & Passkeys but forbids viewing/using existing ones. The TOTP field states "Premium subscription required".

Workaround mentioned above sadly doesn't work for us. 

A polite Bitwarden support staffer sent us here.

Android 14 Play System Update 2024-11-01. Patch level 2024-12-01 (yyyy-mm-dd). Bitwarden Version: 2025.1.0 (19622)

**Comment by Mouth7505** [comment]
I have the same issue in the **browser plugin** and **web view**, the TOTP field is asking for premium. The password is saved in the legacy families plan and my iOS app is showing the TOTP code correctly, not blocked by the "Premium" tag.

Bitwarden plan: Families 2019

Bitwarden Plugin version: 
Version: 2025.1.0
SDK: 'main (28c7e29)'

Brave version: v1.74.50 (Jan 23, 2025)

**Comment by douira** [comment]
For me it's broken for _some_ iOS app users and for _some_ website users. (also using Families 2019)

**Comment by microwavesafe** [comment]
I am also on the Families (2019) subscription and am unable to add new attachments using the Firefox extension (on Linux desktop and Android). I am also unable to add attachments on the Android app. All of them stating that I need premium to access this feature.

However I CAN add attachments on the Linux desktop app.

As others have stated, I have had no communication that this feature was going to be removed and as it works on the Linux desktop app, it points to a bug in the Android app and Firefox extension that is not correctly detecting that people with the older families plan has premium feature access on the organisation vault.

**Comment by gsklee** [comment]
Same here. Been having this issue for more than a month. Is this a ploy to try to subvert early Bitwarden adopters so we will be "upgrading" from the legacy plan to newer plans which offers the same functionality but in triple price? Absolutely no engagement and commitment from the dev team to address this issue at all. This should make a very good HN story.

**Comment by ROosterloo1988** [comment]
Change will be reverted:

https://github.com/bitwarden/android/pull/4633

**Comment by microwavesafe** [comment]
@ROosterloo1988 does this change also fix the issue with attachments?

**Comment by ROosterloo1988** [comment]
I don't know. You can maybe ask it in the other case.

> @ROosterloo1988 does this change also fix the issue with attachments?

**Comment by pcartwright81** [comment]
That revert only fixed the Android client.  That still leaves the web extensions and the website.

**Comment by microwaveric** [comment]
> That revert only fixed the Android client. That still leaves the web extensions and the website.

I haven't seen this issue recently on the web extensions - only in the Android app.

**Comment by demodigit92** [comment]
It is still the case with chrome web extension 2025.1.2

<img width="483" alt="Image" src="https://github.com/user-attachments/assets/c4a2bc1f-2ff2-4926-a695-d676a7d67592" />

**Comment by pcartwright81** [comment]
My issue was for Families 2019 and is still an issue.
Web extension

<img width="274" alt="Image" src="https://github.com/user-attachments/assets/77015276-4a34-4bdd-bc77-e5c1dd691555" />

Website

![Image](https://github.com/user-attachments/assets/acd03413-0021-4ecf-b67b-83f771088365)

**Comment by rbeede** [comment]
My extension is on 2015.1.0 (it did not update itself) and does not have the issue. Not sure if I'm just lucky or if they stopped the auto-update due to bugs.


> It is still the case with chrome web extension 2025.1.2
>

**Comment by dzaggiel** [comment]
> My issue was for Families 2019 and is still an issue. Web extension
> 
> <img alt="Image" width="274" src="https://private-user-images.githubusercontent.com/2352477/407882196-77015276-4a34-4bdd-bc77-e5c1dd691555.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgxODA4NzQsIm5iZiI6MTczODE4MDU3NCwicGF0aCI6Ii8yMzUyNDc3LzQwNzg4MjE5Ni03NzAxNTI3Ni00YTM0LTRiZGQtYmM3Ny1lNWMxZGQ2OTE1NTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjlUMTk1NjE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2RhNjIxZDc4NDUwYWYyZmY5ZWMzMDZkZGNmMjU3NDJkYzFhOWQwMzgwNDM4NDg5ZjJlOTFlYzc1MjUzNDcwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YSaCqpWoJ6-dWDuUek3FcfGc74GnvhKta4t5JQ7pQiw">
> Website
> 
> ![Image](https://github.com/user-attachments/assets/acd03413-0021-4ecf-b67b-83f771088365)

Yep I have the same problem only in web extension

**Comment by mawd** [comment]
hey @bitwarden-bot please priotize this issue

**Comment by BodoHuber** [comment]
Same issue here with self-hosted Family 2019 abo and MacOS, Chrome and Safari extensions asks to purchase premium when trying to read TOTP code while the Bitwarden desktop app works as expected and provides TOTP.

**Comment by alastairherd** [comment]
I am running into the same issue on my Android phone, I have no option to "Copy TOPT" from there, and have to go to the desktop app to be able to get my 2FA for several accounts. I've had the issue intermittently for a few weeks.

**Comment by pcartwright81** [comment]
This is for the web extension and web application (not Android) as the title says.   Also you did not specify if this was for an organization, but I think this is for you.  https://github.com/bitwarden/android/issues/4587

**Comment by demodigit92** [comment]
fixed for me since the last web version 2025.1.3 (Arc - Chromium - Mac)

**Comment by ROosterloo1988** [comment]
Also fixed for me in android 2025.1.2

**Comment by dzaggiel** [comment]
I can confirm finally they fixed this on Edge web extension

**Comment by rbeede** [comment]
Update to Windows, Chrome, Chrome Webstore Extension version 2025.1.3 results in bug. Cannot see TOTPs now whereas version 2025.1.2 I could.

**Comment by kajmikkelsen** [comment]
totp not working in extensions, and not in web application and not in flathub version (Linux mint 22.1)

**Comment by demodigit92** [comment]
Hello @pcartwright81 can you reopen the issue, it is affecting me again since Web version 2025.2.0 (Arc 1.82.1 - MacOS 15.3.1)?

**Comment by vladdy** [comment]
I'm having the same issue in Firefox on macOS and the support redirected me to this issue. Adding this as additional data point on the number of affected users.

**Comment by pcartwright81** [comment]
I am seeing this in the Firefox store.  
https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/versions/

<img width="361" alt="Image" src="https://github.com/user-attachments/assets/81aee47a-c003-4a9a-96d8-cab245bed503" />

Is this the beta version?

**Comment by pcartwright81** [comment]
This is broken in both the web app 2025.2.0, and the extension 2025.2.1.  So we got the bug fixed in 2025.1.2 just for it to be broken in 2025.2.1.

**Comment by davesonaquest** [comment]
It's comical! Chrome extension (2025.2.0) on Win 10 (22H2) exhibiting same behavior. The new UI + this, would be nice if they would break less things.

**Comment by sutusa** [comment]
+1 as I have this issue too.  It appeared after I updated my local self hosted bitwarden.  TOTP is marked a premium only feature that I used to have access to for years.  This is quite hindering on a day-to-day basis...

- I have the "Families 2019" subscription plan.
- Self hosted version of Bitwarden via docker at version "2025.2.0" via the webapp.
- Same issue in the Firefox extension at version "2025.2.0"
- Can confirm that I can use the Copy "hamburger" icon, and select "copy verification code" as a work around via the FireFox extension.
- No work around via the webapp that I can find.
- Reissue of my self-hosted license from Bitwarden does not fix the issue.

Any update on when there will be a fix for this?  It is quite annoying.  Not to mention it is a feature I paid to have access to and no longer have.  Thank you.

**Comment by Greenderella** [comment]
Thank you to everyone who has reported this issue, and we apologize for the delay. This should now be resolved. Could everyone who was affected by this bug please log out (not just lock) and log back in to the affected clients? After doing so, please check if you're now able to visualize the TOTP codes.

Thanks for your patience!

**Comment by demodigit92** [comment]
Hello, I am using Bitwarden Web Extension 2025.2.2 here (+Arc Mac OS 15.3.1).

The bug seems to be partially fixed, as I cannot copy the code from the item itself -> still disable with premium tag : 

<img width="365" alt="Image" src="https://github.com/user-attachments/assets/ab66b545-43f3-43a4-ad0a-174694e6a494" />

However, I can copy the OTP code from the main item list 

<img width="369" alt="Image" src="https://github.com/user-attachments/assets/4c006712-021d-4483-b0fd-49b69bce2d15" />

**Comment by Greenderella** [comment]
Thank you for confirming. If anyone else continues to experience this issue, please reach out to us through our 'Contact Support' form, available in our Help Center (https://bitwarden.com/help/).
