### ISSUE TITLE
Popup too small on some instances

### ISSUE THREAD

**Issue by francois-pasquier** [bitwarden/clients#13174]
### Steps To Reproduce

1. Open chromium or equivalent
2. Open extension

### Expected Result

Full size height

### Actual Result

window.screen ->
```js
{
availHeight: 994,
availLeft: 0,
availTop: 38,
availWidth: 1728,
colorDepth: 30,
height: 1117,
isExtended: false,
onchange: null,
orientation: ScreenOrientation {angle: 0, type: 'landscape-primary', onchange: null},
pixelDepth: 30,
width: 1728
}
```

The behaviour seems to be random. As sometimes it does take the full height.

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/4e4e35e3-e40e-48e4-b0b6-bdd24010a15a)

### Operating System

macOS

### Operating System Version

Sequoia 15.2

### Web Browser

Chrome

### Browser Version

Version 132.0.6828.0 (Developer Build) 

### Build Version

2025.1.2

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by pamperer562580892423** [comment]
That reminds me of this issue I still have... unresolved: https://github.com/bitwarden/clients/issues/12941

**Comment by coltanium13** [comment]
I have also been having what seems to be a half size window on chrome on my Mac. When I first open the extension, to enter the password, it only opens half the normal length. If I click away, so the extension goes away, then click the extension button again, it is then the normal full length. 

This does not always happen though. Seems usually once or twice in a day. Usually the first time in the morning when I login to the extension at least. I have u installed and re installed the extension and it did not fix it.

**Comment by pamperer562580892423** [comment]
> ... When I first open the extension, to enter the password, it only opens half the normal length. If I click away, so the extension goes away, then click the extension button again, it is then the normal full length.

I think that's more or less how it began for me.

It kind of reversed the last days: now, the extension starts most of the time with a normal window, and then changes into the "half length" without returning for now. - If I don't use the extension, let's sax for the next hour (and the extension already locks after 5 minutes), it kind of get's "resetted" and the cycle begins anew.

**Comment by Krychaz** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by coltanium13** [comment]
> Hi there,
> 
> I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 
> 
> Thanks!

I tried it again this morning, and when I click on the extension icon, the window was half size again. I'm not sure what other information to give at this point.

I'm on a mac, chrome, its a pinned extension. It seems the session has to time out or something for it to occur. If you click it once the small size happens, then close the window, then click again it's fixed(until the next timeout).

I'll keep looking for more info that might be relevant and let you know.

**Comment by pamperer562580892423** [comment]
I'm also not sure what I could add... It's not completely consistent - sometimes the window is normal, but most of the time it is only "half length". In unlocked state, it's almost only "cut in half" - except for rare cases directly after unlocking it could be that it's the normal window for a short time, and if I the extension window doesn't close. (if it closes, it's almost certain that it's cut in half the next time, even it's only a few seconds before I open the window again)

As @coltanium13 has it with Chrome on Mac, and me with Vivaldi on Windows 11, it seems not tied to a specific system.

And I can't see any "cause" for this behaviour - it just began out of the blue (and didn't resolve itself - even not with the latest extension update, as I think it began on extension 2025.1.1 for me, but continued on 2025.1.2... and also the latest Vivaldi update from today, doesn't change it...).

**Comment by pamperer562580892423** [comment]
@Krychaz Updated to extension version 2025.1.3 now and the issue still persists...

**Comment by pamperer562580892423** [comment]
By chance, I searched in the community forum for something else - and stumbled upon old and similar reports to our current issue here:

- https://community.bitwarden.com/t/bitwarden-vivaldi-extension-window-size-very-small/26539
- https://community.bitwarden.com/t/brave-chrome-extension-window-suddenly-half-size/45821

And there are also old issues here on GitHub to that: https://github.com/bitwarden/clients/issues/3970 and https://github.com/bitwarden/clients/issues/4114

My summary: had to do with "fingerprinting" settings/changes of the browsers - setting the browser flags (e.g. vivaldi://flags) to "default" could fix it in some instances (note: I tried to do that now, but it didn't change it for me now on Vivaldi) - but ultimately, browser updates fixed this (at least for Brave, as I saw it correctly)...

So, is this the same thing again? Or is it a different bug now? - Do we ultimately have to wait for browser updates? Or can it be mitigated otherwise? (also @Krychaz )

**Comment by coltanium13** [comment]
> @Krychaz Updated to extension version 2025.1.3 now and the issue still persists...

I just updated to the latest version too. I will keep monitoring and see if it changes for me too. 

I was wondering too, if any of the appearance settings or auto fill settings would make any difference with the issue? 

I have auto fill > click items to auto fill it on vault turned on

And for appearance> all check boxes except the compact mode are turned on

**Comment by pamperer562580892423** [comment]
@Krychaz I can report something new:

1. It's still happening for me on extension version 2025.2.0 (Vivaldi), but...
2. ... I just discovered, it happens not in all "Workspaces" on my Vivaldi browser... - I'm relatively new to Vivaldi and (yeah, shame on me) used mainly one "Workspace" for now with around 1000 Tabs (though, most of them "hibernated" per Vivaldi settings). - As I opened some other "Workspaces", I now discovered, that in them, with just a few tabs, the extension window has it's normal size!! As soon as I change back to my crowded Workspace, the extension window is "cut in half (height)" again.
3. ... It's not the Workspace itself... I moved all tabs to a new Workspace - extension window immediately cut in half again in that new Workspace with the 1000 tabs... I'm now down to about 800 tabs and still have the extension window cut in half... Whether it is due to the sheer amount of open tabs or one or more certain tabs that produce the error, I don't know at the moment... but it has definitely something to do with the tabs...

**Comment by pamperer562580892423** [comment]
To make it short: I can report, that the issue resolved for me. (for the record: I posted my issue here originally: https://github.com/bitwarden/clients/issues/12941)

Around two weeks ago, I posted my above comments, about reducing open tabs in Vivaldi had an impact on that. I reduced the open tabs further, and without counting them now exactly: I have about 7 "Workspaces" with a few tabs up to about 100 tabs each. In total, it might still be about 300 tabs in all 7 Workspaces. But the issue didn't occur again for me now after reducing the tabs.

As one could see in the video: the workspaces with "few" tabs showed the extension in full height (what I didn't recognize before, as I didn't use the Workspaces, as I was new to Vivaldi...).

When I reached about 300 tabs for one Workspace, it began that the extension somewhat sometimes showed the full height, and sometimes was cut in half again. It maybe even was dependent on which tab I actively was.

Again, as no Workspace has now more than about 100 tabs, the extension window is never cut in half for me now.

Hopefully, that feedback helps. Either "individually" - or maybe Bitwarden still finds a solution to this, even with "more tabs". But it definitely - at least in my case - had to do with the amount of open tabs.

**Comment by francois-pasquier** [comment]
I don’t have more than 10 tabs usually

**Comment by BWPeter** [comment]
Hello @francois-pasquier ,

Closing this issue as it appears the originally posted problem has been resolved in QA environments. A mitigation to this issue is currently implemented in QA environments and will be released on May 29th. If this happens again or continues to be an issue after the fix is released, please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Comment by pamperer562580892423** [comment]
@BWPeter This issue has reappeared for me. It always was in combination with "too many open tabs" for me, but now I already reduced the open tabs by a lot (actually, several hundred 🙄), but still get the reduced height of the browser extension window. (not every time, though)
