### ISSUE TITLE
Browser doesn't automatically ask for fingerprint when autofill shortcut is pressed

### ISSUE THREAD

**Issue by BijornCoote** [bitwarden/clients#13654]
### Steps To Reproduce

In firefox, when you press the autofill keyboard shortcut when the vault is locked, the Touch ID prompt is not automatically invoked. You have to click unlock to invoke it, but previously it was not like this

This can be reproduced by trying to autofill a page using the keyboard shortcut when the vault is locked.

### Expected Result

Touch ID prompt is automatically invoked when autofill keyboard shortcut is pressed.

### Actual Result

Touch ID prompt is **not** automatically invoked when autofill keyboard shortcut is pressed, instead you need an extra click to invoke the Touch ID prompt.

### Screenshots or Videos

<img width="409" alt="Image" src="https://github.com/user-attachments/assets/1fb978a7-4c43-4ee7-ad44-b25c960f871a" />

### Operating System

macOS

### Operating System Version

Sequoia 15.3 

### Web Browser

Firefox

### Browser Version

135.0.1 

### Build Version

2025.2.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by XerXes777** [comment]
Same problem with windows and firefox.

**Comment by jpjonte** [comment]
Can confirm, same issue on 2025.2.0 with Firefox 135.0.1 on macOS.

Started happening within the last two weeks.

**Comment by sn55997** [comment]
**similar** issue on WIN 11, Firefox 135.0.1 (64-Bit): Klick on add-on doesn't invoke win 11 biometric dialogue.
Checkbox "Ask for biometric data at startup" ist missing.

Addon Version: 2025.2.0 SDK: 'main (28c7e29)', 

Desktop Version 2025.2.0 SDK 'main (28c7e29)'
Shell 34.0.0
Renderer 132.0.6834.83
Node 20.18.1
Architecture x64

**Comment by q20** [comment]
2025.2.0 with Firefox 135.0.1 on macOS - I actually have to click twice to initiate a biometric prompt:

<img width="476" alt="Image" src="https://github.com/user-attachments/assets/5898b726-f367-4d7a-bfe1-2b567faf4d12" />


<img width="472" alt="Image" src="https://github.com/user-attachments/assets/af72c478-971c-4054-94d0-8939556f1db2" />

**Comment by nicolafarina** [comment]
I confirm the same issue on Windows 11, with the desktop app also (a part from browser integration).

**Comment by SinBirb** [comment]
This is intended new behavior... https://github.com/bitwarden/clients/issues/13840

**Comment by ewjoachim** [comment]
Oh, those 2 issues seems to be duplicates.
Just in case, I've suggested a couple of ways Bitwarden could circumvent the issue in https://github.com/bitwarden/clients/issues/13840#issuecomment-2746129035

**Comment by q20** [comment]
> This is intended new behavior... [#13840](https://github.com/bitwarden/clients/issues/13840)

I am currently training muscle memory to initiate biometric auth on macOS+Firefox. It goes like this:

- browse to website requiring auth
- `CMD+SHIFT+L`
- `TAB`
- `TAB`
- `ENTER`
- Fingerprint

Done! Much shorter than the Konami code, but certainly more key presses than should be necessary. Still, with this combo I do not need to move my mouse cursor.  👍

**Comment by DimitriDR** [comment]
I'm wondering why It is "intended" on Firefox but not on Chrome! Chrome behavior is so much faster and smooth. Why I have to do extra steps on Firefox? Is it some kind of 'privileges' we have when using Firefox. Internet is not very Firefox friendly anymore, and Bitwarden adds a new layout.

**Comment by BijornCoote** [comment]
Can we please get an update on this? It's still an issue that wasn't present before the update, which broke this.

**Comment by nicolafarina** [comment]
There's a banner on Bitwarden forum website to alert that is a known issue resolved within the next Firefox addon release (in pending/approval by Mozilla).

**Comment by pamperer562580892423** [comment]
> There's a banner on Bitwarden forum website to alert that is a known issue resolved within the next Firefox addon release (in pending/approval by Mozilla).

Firefox extension 2025.6.1 is available now.

**Comment by BijornCoote** [comment]
@nicolafarina appreciate it!

**Comment by BijornCoote** [comment]
Okay, I see. The option that was enabled before it stopped working just has to be re-enabled. "Ask for biometrics on launch".
