### ISSUE TITLE
“No Passkeys found for this application” on AWS using the Bitwarden extension

### ISSUE THREAD

**Issue by computerpoet** [bitwarden/clients#14139]
### Steps To Reproduce

I used to be able to use the bitwarden extension to provide my registered Passkey on AWS, but now it does not work anymore as it says “No Passkeys found for this application”.

- Chrome Version 134.0.6998.166 (Official Build) (arm64)
- MacOS Sequoia 15.4
- Bitwarden extension 2025.3.1

[First reported here on the community website](https://community.bitwarden.com/t/issues-with-aws-passkeys-bitwarden-extension/83430)

<img width="365" alt="Image" src="https://github.com/user-attachments/assets/4b6ec4fd-2bcd-4c12-a84f-3fd396e9fa0e" />

<img width="343" alt="Image" src="https://github.com/user-attachments/assets/4045c6f4-1f5e-45e4-a9f9-2e8ca6475c86" />

<img width="341" alt="Image" src="https://github.com/user-attachments/assets/126b5f39-4e66-4538-96bb-5c13972f41f7" />

<img width="363" alt="Image" src="https://github.com/user-attachments/assets/29a3d173-93bd-460e-a0b1-ea1518fa8e15" />

1 & 3 are "Default Base domain
2 is “starts with”

Other passkeys work. AWS is not on the excluded domain list.

### Expected Result

I should be able to see my passkeys for AWS, select them to do MFA.

### Actual Result

<img width="395" alt="Image" src="https://github.com/user-attachments/assets/afbb96bd-388a-4d62-b63b-4bebf873f903" />

### Operating System

macOS

### Operating System Version

Sequoia 15.4

### Web Browser

Chrome

### Browser Version

134.0.6998.166 (Official Build) (arm64)

### Environment Versions

Version: 2025.3.1

SDK: 'main (6008e90)'

Server version: 2025.3.3

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by S-Kakar** [comment]
Thank you for reporting this issue! We've added this to our internal tracking system.
ID: PM-19912

**Comment by tyron** [comment]
I just started seeing the same problem with Microsoft (login.microsoft.com), when trying to access my Personal Drive in OneDrive. Not sure if it's worth creating a New Issue here, as it seems too similar to be a coincidence...

**Comment by pamperer562580892423** [comment]
@tyron Another user here... You could provide some details about your "system". Can help to detect a "pattern" (or not if there is no pattern ;-) ).

**Comment by tyron** [comment]
Sorry, it's all the same as the OP.
- Chrome Version 134.0.6998.166 (Official Build) (arm64)
- MacOS Sequoia 15.4
- Bitwarden extension 2025.3.1

**Comment by pamperer562580892423** [comment]
@tyron You both using Mac and Chrome might already be a common factor. But two people is too early to see a clear pattern and it's just speculation at this point.

**Comment by computerpoet** [comment]
Edited Uris to:

Uri1: https://aws.amazon.com/ 
Uri2: https://signin.aws.amazon.com/
Uri3: https://eu-north-1.signin.aws.amazon.com/
Uri4: https://signin.aws.amazon.com/signin

All Default Base domain

**Comment by tyron** [comment]
In my case, it's happening with onedrive.live.com, when I try to open my Personal Vault. There's a popup for logging into Personal Vault with URL: https://login.microsoft.com/consumers/fido/get
I have my Vault entry configured with the following URLs, all of them matching Base Domain:
```
https://login.live.com
androidapp://com.microsoft.office.officelens
androidapp://com.microsoft.skydrive
https://login.microsoftonline.com
https://login.microsoft.com
```
If I inpect the service worked view on Bitward extension, I can see the following messages in the console:
```
(ERROR)
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
background.js:1

(INFO)
[Fido2Authenticator] Aborting because no matching credentials were found in the vault.
background.js:2
```

**Comment by pamperer562580892423** [comment]
@tyron I also saw your update now, that it is fixed by re-creating the passkey.

I have wild theory, based on your reported error messages...:

At the moment, there is also a bug, that attachments can get lost (https://github.com/bitwarden/clients/issues/14150) and URI matching detection for URIs can get lost (https://github.com/bitwarden/clients/issues/14188) - and one of your error messages states "no matching credentials were found in the vault"... so I'm beginning to think, if the passkey data in the vault (or at least parts of it) could got lost. ?!

Someone with experiencing that error could compare an old backup export with a new one, to compare the passkey data and see if there is something different and/or missing.

But again, just a wild theory and speculation - from another user.

**Comment by holow29** [comment]
> I'm having a very similar issue on https://connect.secure.wellsfargo.com/auth/login/present

I am also having this issue with Wells Fargo. Passkey works in-app on iOS and also in Safari on iOS. However, in browser, Bitwarden extension continues to say no passkey found. This is odd as the site is https://connect.secure.wellsfargo.com/auth/login/present and the the saved passkey has `"rpId": "connect.secure.wellsfargo.com",` (Browser Version: 2025.4.0; SDK: 'main (50f5a17)')

**Comment by wlhamaty** [comment]
I am encountering this with connect.secure.wellsfargo.com on Firefox 138.0.4, Windows 11, Bitwarden 2025.04.0.
Also, same system, with Edge 136.0.3240.76, Bitwarden 2025.5.0
It does work with the WF Android App, Pixel 6, Android 15 BP1A.2505.005 , Bitwarden 2025.4.0 (20100)

**Comment by abergs** [comment]
Hi everyone, I work at Bitwarden. I just wanted to share that we've identified a bug with how Wells Fargo uses the webauthn api. While it's an issue on their side, we've made adjustments to make sure the way they call the API does not cause problems in bitwarden.

This *may* resolve the issue on other sites as well, but please note that you would need to recreate the passkey.

The fix has been made, but has not been released. We'll try to include it in the next possible release, but it may be about 30 days until it rolls out to everyone.

**Comment by holow29** [comment]
> Hi everyone, I work at Bitwarden. I just wanted to share that we've identified a bug with how Wells Fargo uses the webauthn api. While it's an issue on their side, we've made adjustments to make sure the way they call the API does not cause problems in bitwarden.

Thanks for your work on and attention to this! I'm presuming the fix is in https://github.com/bitwarden/clients/pull/14816? Oddly, iOS doesn't seem to care about discoverability in the same way...which seems like iOS is violating spec and hence why I can login to Wells Fargo using the passkey on BW that is saved as discoverability: "false". (That or somehow iOS is also providing the user handle at the same time...)

**Comment by wlhamaty** [comment]
> > Thanks for your work on and attention to this! I'm presuming the fix is in [#14816](https://github.com/bitwarden/clients/pull/14816)? Oddly, iOS doesn't seem to care about discoverability in the same way...which seems like iOS is violating spec and hence why I can login to Wells Fargo using the passkey on BW that is saved as discoverability: "false" using Safari on iOS.

Retired developer here. A lot of younger developers, particularly those trained outside the US, seem to want to make everything into a string. It wouldn't surprise me at all if generative AI were to pick up that habit. I didn't look at 14816 closely, but assuming the passkey is represented as JSON, whether the string ends up as 'true' would depend on what was used to write the JSON, and whether is is converted to boolean true depends on what is used to read it. Both sides have the opportunity to auto-convert. It also wouldn't surprise me if the specification is ambiguous. I have seen standards derailed by a single sentence that can be read two different ways.

**Comment by abergs** [comment]
Correct, a passkey "should" be  a discoverable webauthn credential (and is often synced).
We also support non discoverable webauthn credentials (which are more commonly used in MFA-like settings).

**Comment by holow29** [comment]
Extension 2025.6.0 is working for me on Wells Fargo. Ebay and Discord both still have `"discoverable": "false",` for their passkeys. I'm not sure about AWS. I don't know if #14816 was included in 2025.6.0 or not - it could be that Wells Fargo corrected their implementation in the interim.

**Comment by abergs** [comment]
https://github.com/bitwarden/clients/pull/14816 was not in 2025.6.0 but is rolling out in 2025.7.0, which haven't hit browsers yet.

So ebay + discord should see an improved behaviour in 2025.7.0

**Comment by pamperer562580892423** [comment]
@abergs:

> but is rolling out in 2025.7.0, which haven't hit browsers yet.

... which not even was released on GitHub yet. 😉

**Comment by holow29** [comment]
> So ebay + discord should see an improved behaviour in 2025.7.0

Did #14816 make it into 2025.7.0? If it did, there is some other issue because eBay and Discord passkeys are still being saved with `"discoverable" : false` even on 2025.7.0 browser.

**Comment by pamperer562580892423** [comment]
> Did [#14816](https://github.com/bitwarden/clients/pull/14816) make it into 2025.7.0?

It did. You can see things like this if you use the "compare" function. https://github.com/bitwarden/clients/compare/browser-v2025.6.1...browser-v2025.7.0

**Comment by holow29** [comment]
> You can see things like this if you use the "compare" function.

Thanks. This is largely true, but certain features (not this one) use server-side feature flags, so it doesn't paint the whole picture unfortunately.

**Comment by tkawachi** [comment]
I'm having trouble with this issue on AWS, too. I hope it gets fixed soon since I can't log into my account.
I'm using macOS Chrome 140.0.7339.81 and Bitwarden chrome extension 2025.8.2.

**Comment by abergs** [comment]
@tkawachi This issue should should be resolved and I recommend you to perhaps re-create the passkey for your AWS account. Or going through some other flow where you enter your username first.

if it does not work - I wonder if amazon has perhaps changed their rpId in the webauthn request in their adoption of the new Webauthn L3 Related Origins feature.

**Comment by tkawachi** [comment]
I am unable to log in with my passkey, and unfortunately, I cannot log in using any other method either, so I am unable to regenerate the passkey. The issue persists even now, and both the passkey exported from Bitwarden as JSON and the rpId in the communication appear unchanged at aws.amazon.com.
<img width="916" height="195" alt="Image" src="https://github.com/user-attachments/assets/52b11941-07ce-433e-808d-4f5fe733b748" />

**Comment by abergs** [comment]
If you export your bitwarden vault, what value does the key have for discoverable? **Don't share** any screenshot of the exported vault contents.

**Comment by tkawachi** [comment]
It's false: `"discoverable": "false",`.

**Comment by royyeah** [comment]
Same issue with signin.aws.amazon.com and Bitwarden extension version 2025.6.1 on Firefox 146.0.1. After noticing the Bitwarden extension version was lagging behind (auto-updates are enabled) I was able to update to 2025.12.0 but still same issue (also after restart).

Also tried to use the mobile app version 2025.12.0 and Safari on my iPhone but this also does not work.

**Comment by kjleitz** [comment]
Same issue and has been happening for months, and cannot access my AWS account as a result. Bitwarden popup on AWS says "No passkeys found for this application" even though the domain is definitely in the websites list and it's not in the excluded domains. Passkey works normally for GitHub login.

- Brave 1.92.144 (Chromium 150.0.7871.186)

- Using Bitwarden extension:
  > Version: 2026.7.0
  > SDK: 'main (3e060f8)'
  > Server version: 2026.8.1

- macOS Sequoia 15.6.1
