### ISSUE TITLE
File attachment upload fails desktop / browser / ios app. "An Error has occured."

### ISSUE THREAD

**Issue by matthlsile** [bitwarden/clients#14160]
### Steps To Reproduce

1. Go to 'Edit' in an login item.
2. Scroll down / Click on 'Attachments'
3. Select File (14 kB .pfx certificate file in my case.)
4. Click on 'Save'

### Expected Result

File get's uploaded as an attachment after clicking on save.

### Actual Result

Red Error card with Error: "An error has occured.  An unhandled server error has occured."
File doesn't get uploaded properly.

### Additional Context

Files also can't be uploaded in browser extension (Firefox, Safari and Chrome tested), iOS Bitwarden and in Webvault on bitwarden.com. No error messages there, though.

### Operating System

Windows, macOS

### Operating System Version

Windows 11 23h2, iOS 18.4, macOS ?

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2025.3.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by S-Kakar** [comment]
Thank you for reporting this issue! We've added this to our internal tracking system.
ID: PM-19935

**Comment by geekitude** [comment]
Hi
Deleted an attachment from an ID element to upload a new one. Lost all the attachment on that ID (about 6 or 8 files) and can't add a single one with same error as above.

**Comment by SohamBhattacharya** [comment]
Hi, still facing the same error (v2025.3.0 snap).

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

I did want to note that this may be caching related, I had tested this on different clients and saw that when I logged in to a new client (in my case the Bitwarden web interface in an incognito/private browsing window) I was able to view those attachments that I had attempted to upload but received an error or appeared to be uploaded unsuccessfully.

@geekitude your behavior matches the issue that is open here: https://github.com/bitwarden/clients/issues/14150

@matthlsile you mentioned this in the above GitHub issue, I believe these behaviors may be related, but in the case that they are separate issues I will be leaving this issue open as well so we can track reports of both of these issues separately.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by geekitude** [comment]
@rmcdowell-bitwarden, thanks for pointing me to the right issue

**Comment by arpanrec** [comment]
I am a long-time bitwarden family plan user. I think this issue is kind of priority. There is something very wrong going on right now. this behavior of the attachments is blocking me from taking a backup of my valut, which is very scary.

![Image](https://github.com/user-attachments/assets/537c3178-ce54-4f89-b52b-35567977b6fe)

The attachment shows up in CLI but i am unable to download them from CLI.

```
subprocess.TimeoutExpired: Command '['bw', 'get', 'attachment', 'r2q53vpynoeflmp8kw1m5jx0vcfjxds5', '--itemid', '88f162b3-1018-4d2e-8f75-af88008652fb', '--output', '/home/arpan/workspace/bitwarden_dump_attachments/88f162b3-1018-4d2e-8f75-af88008652fb/r2q53vpynoeflmp8kw1m5jx0vcfjxds5']' timed out after 10 seconds
````

**Comment by mrkdilkington** [comment]
I'm getting an error when uploading on MacOS (chrome browser and chrome extension) and iOS App. Please fix this asap!

**Comment by Loggsie** [comment]
I'm affected on all platforms too as well as the web vault. With a HTTP 500 error it is likely a database connection and/or write issue. 

At least from the error we can deduce it's a server side fault and not client side.

**Comment by Loggsie** [comment]
> I'm getting an error when uploading on MacOS (chrome browser and chrome extension) and iOS App. In dev tools it says it's an HTTP 500 error. Please fix this asap!

I'm affected on all platforms too as well as the web vault. With a HTTP 500 error it is likely a database connection and/or write issue.

At least from the error we can deduce it's a server side fault and not client side.

**Comment by peterswirl** [comment]
This is a serious blocker for us. This is core functionality in the Bitwarden product. We may be a start up, Bitwarden is not. I certainly hope this is addressed very quickly because this is a serious problem that never should've made it into production.

**Comment by spawnz0** [comment]
Same issue. This is an **absolutely CRITICAL ISSUE**. The Bitwarden Service Health should NOT show healthy. IT SHOULD BE RED AND DOWN. **Literally WE AS PAYING SUBSCRIBERS CANNOT UPLOAD FILES AND USE THE SERVICE.**

**Comment by Qerdo97** [comment]
Confirming issue, on both Web UI and CLI. HTTP Error 500

![Image](https://github.com/user-attachments/assets/7eef8948-cd5c-4508-85be-009414fcb0c7)

![Image](https://github.com/user-attachments/assets/75e114d4-9c75-438b-89ff-8f48d4f08a90)

**Comment by peterswirl** [comment]
There was a release of the Macintosh native client today. It continues to have the problem. Because of the different context of the problem it seems pretty obvious that this is a backend issue.

**Comment by arpanrec** [comment]
https://github.com/bitwarden/clients/issues/14150#issuecomment-2806252373

This issue comment is also true for this issue.

**Comment by tedledbetter** [comment]
This is happening to me as well. Tried deleting an attachment, all files disappeared. Now 500 error on trying to add any.

**Comment by FakeJoe** [comment]
Same issue. Such a critical feature blocks me from doing my job

**Comment by Loggsie** [comment]
I'd be interested to know if Linux Unified (Beta) self hosted is affected? I'm considering porting out until things stabilise again.

**Comment by tedledbetter** [comment]
This started working for me tonight. The vault item in question that had the other attachments disappear now showed a "NULL" item, but I was able to delete that and add back the updated attachments successfully

**Comment by Loggsie** [comment]
> This started working for me tonight. The vault item in question that had the other attachments disappear now showed a "NULL" item, but I was able to delete that and add back the updated attachments successfully

Can confirm the same using the Android app.

**Comment by arpanrec** [comment]
> This started working for me tonight. The vault item in question that had the other attachments disappear now showed a "NULL" item, but I was able to delete that and add back the updated attachments successfully

owo can't risk that if any existing attachment goes 'NULL'. is it same for personal items(Outside of org) as well?

**Comment by peterswirl** [comment]
Folks, I was contacted by support today and was told that this was a backend problem with routing. That is what caused the apparent deletion of attachments and blocked attaching new files. They say it was fixed on Tuesday. I verified it for myself today, Friday, April 18, 2025. I was able to delete and add attachments on our record. Everything worked as expected.

I suggest you recheck to see if you are still having the problem. Hopefully you'll be in the same boat that I am.

**Comment by mvmike** [comment]
Also can add and delete attachments again, even though error messages are still appearing (EU instance).

No sight of previously lost attachments

**Comment by vincentsalucci** [comment]
Hey everyone! We've implemented a server-side mitigation for inserting improperly formatted JSON that can be found [here](https://github.com/bitwarden/server/pull/5656). The changes are expected to be deployed during our next release cycle (week of **May 12th, 2025**). We've been monitoring the Production databases daily for the past several weeks and have not seen any more occurrences. This ticket is going to be closed at this time. Thank you to everyone who provided detailed feedback and data points for replication!
