### ISSUE TITLE
Vault is empty after unlocking browser extension from keyboard shortcut pop-up

### ISSUE THREAD

**Issue by nilshg** [bitwarden/clients#15298]
### Steps To Reproduce

When pressing `Ctrl`+`Shift`+`L` to auto-fill an item and the vault is locked, a pop-up window appears to unlock the extension. Once unlocked, the vault is empty, i.e. there are no logins shown 
 
1. Lock vault 
2. Press `Ctrl`+`Shift`+`L` on a website that has an auto-fillable field 
3. Unlock the vault using the pop-up window that appears
4. See that the vault is empty

![Image](https://github.com/user-attachments/assets/1be0ffa1-0c25-4ae3-a3c5-e8ed3e0c11dc)

To get items to-reappear in the vault it is necessary to completely log out (i.e. not just lock) and log back in, and doing so by clicking on the extension to open it rather than using the keyboard shortcut.

### Expected Result

Vault should not be empty.

### Actual Result

Vault is empty.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

139.0.4

### Environment Versions

Version: 2025.5.0

SDK: 'main (f28b4ef)'

Server version: 2025.6.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

Will you try uninstalling the application, removing any leftover data, powering off and on your device and re-installing? Does this issue still persist?

Guide to the leftover data: https://bitwarden.com/help/data-storage/#on-your-local-machine

Let me know if that helps.

**Comment by nilshg** [comment]
Didn't help - slight difference now is that I get a never-ending "loading" animation rather than the vault is empty message when I log in from the keyboard shortcut:

![Image](https://github.com/user-attachments/assets/17555756-9fbd-4085-b963-bc988341974a)

**Comment by nilshg** [comment]
This seems to have been fixed after the latest update (not sure if FF or Bitwarden or both) - I was asked to give additional permissions to the extension and it now behaves as expected.

**Comment by desk-job** [comment]
This is still broken for me. If anything, it's more broken for me now. 

Earlier, it would show me the seemingly-unending spinning loading animation. I would then check back after 2 minutes to find that I've been signed in and it's loaded the vault successfully (but hasn't autofilled the form with the appropriate credentials). 

However, now it doesn't seem to load it at all. But there's a caveat: if I try to trigger the autofill using `Ctrl` + `Shift` + `L`, it behaves as described above. But if I don't use the keyboard shortcut to trigger autofill and just click on the extension in the Toolbar and then sign in, it signs me in as expected and shows me all the vault items as expected. 

To be clear, I also got the Bitwarden and the Firefox updates, including the Bitwarden update that asked for additional permissions. I'm on Bitwarden version 2025.7.0 and on Firefox version 141.0.2. 

I cannot reopen the issue. Do I need to create a new issue? Please let me know as this is really frustrating and ruins the convenience that seamlessly autofilling forms using your keyboard offers.

**Comment by nilshg** [comment]
I'll just reopen this I guess?

**Comment by desk-job** [comment]
Thanks. Is this still a problem for you @nilshg? I've just been avoiding using the keyboard shortcut as a workaround. It's really not fun.

**Comment by nilshg** [comment]
I thought it wasn't (I'm sure it really wasn't at some point), but now it looks like it's come back in a different form - when I unlock via keyboard shortcut I now get a completely empty box after putting in my password:

<img width="399" height="663" alt="Image" src="https://github.com/user-attachments/assets/c1f7a914-2fa6-424e-981a-e1e4ce2a6bab" />

So neither the empty vault nor the indefinite loading animation from before...

**Comment by desk-job** [comment]
Yeah, I have the exact same issue. Next time when you need to autofill something, I would recommend clicking on the extension in the Toolbar and signing in that way first. It actually loads the vault almost immediately that way. Then press the keyboard shortcut to trigger the autofill. 

It's infinitely less seamless and convenient this way but at least you aren't waiting 10 minutes for the vault to log you in. 

I'm not sure what's happened to Bitwarden recently but there have been heaps of issues with the extension.

**Comment by cmd05** [comment]
Reinstalling the extension on firefox fixed the issue for me

**Comment by nilshg** [comment]
Not for me unfortunately.

**Comment by nilshg** [comment]
This now seems to be fixed again on the latest FF/Bitwarden combination - I'll close this unless others still see it?

**Comment by desk-job** [comment]
It's still broken for me on the latest version of the Bitwarden extension on Firefox, version 2025.10.0. But I don't think this issue being open or closed is making any difference as it hasn't gotten any attention from Bitwarden since their original comment. I've just been using the mouse to sign in instead of relying on the autofill keyboard shortcut. 

Feel free to close it.
