### ISSUE TITLE
"Ask for authorization when using SSH agent" not being used for requests made through agent forwarding

### ISSUE THREAD

**Issue by lsalazarm99** [bitwarden/clients#15695]
### Steps To Reproduce

1. Set up an SSH key that is managed by Bitwarden's SSH agent.
2. In Bitwarden, navigate to settings and set "Ask for authorization when using SSH agent" to "Never."
3. Connect to a remote server via SSH.
4. From the remote server's terminal, execute `ssh git@github.com`.

### Expected Result

Bitwarden should silently allow the use of the SSH key.

### Actual Result

Bitwarden consistently displays a prompt requesting authorization for SSH key usage whenever an application or command in the remote server attempts to use an SSH key managed by Bitwarden's SSH agent.

### Additional Context

When using remote development environments, which heavily rely on SSH connections, developers frequently encounter an issue where **Bitwarden repeatedly prompts for authorization** of SSH key usage. This occurs because popular development applications, such as **Visual Studio Code and JetBrains IDEs**, perform background checks with Git servers to determine if project updates are available.

These applications typically leverage the **SSH agent** to provide the necessary SSH keys for authentication with Git servers. However, if Bitwarden is configured to manage these SSH keys and is integrated with the SSH agent, each background check initiated by the IDE can trigger a separate authorization request from Bitwarden. This leads to a disruptive and inefficient workflow due to the constant interruptions from Bitwarden prompts.

This issue impacts almost any developer utilizing remote workflows and modern IDEs with SSH key management through Bitwarden, significantly hindering productivity.

### Operating System

Windows

### Operating System Version

24H2 (26100.4652)

### Installation method

Other

### Build Version

2025.6.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by lsalazarm99** [comment]
For reference, it seems to be done on purpose.

https://github.com/bitwarden/clients/blob/8dc97ca1a7038a14981aa3176ae41eb835fa4022/apps/desktop/src/autofill/services/ssh-agent.service.ts#L297-L301

I'd understand an initial warning for each remote server, but if I approve it, I'd expect it to respect the settings I've established. 😅 Perhaps, for occasional uses, I'd add an "approve this time only" button.

**Comment by SergeantConfused** [comment]
Hello @lsalazarm99,

Thank you for your report. I have flagged it to the Engineering department; please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

Thank you again,

**Comment by quexten** [comment]
Just noting here, yes it's on purpose, because until https://github.com/bitwarden/clients/pull/14602 merged, there was no way for the agent to know which server is being connected to, so it did not have the data to remember the choice for that specific remote server. Now that it merged, the data is available.

**Comment by Anthony-Alagna** [comment]
Bumping this, highly annoying issue affecting the usability of the agent forwarding feature.

**Comment by Anthony-Alagna** [comment]
> Just noting here, yes it's on purpose, because until [#14602](https://github.com/bitwarden/clients/pull/14602) merged, there was no way for the agent to know which server is being connected to, so it did not have the data to remember the choice for that specific remote server. Now that it merged, the data is available.


@quexten 
pls fix obiwan, you are my only hope <3

**Comment by sheiun** [comment]
It’s indeed a bit troublesome — when working on a larger project, running `git clone --recurse-submodules` requires authorizing multiple times.

**Comment by Anthony-Alagna** [comment]
Currently using a workaround in my remote development environment:

1. Be forced to explicitly not use agent forwarding for git
2. create a config file on your remote development machine `~/.ssh/config`
3. create a dedicated private key for git, something like: `~/.ssh/id_git` 
4. specify git to use your dedicated private key in the config file:
```Host git.YOUR.GIT.SERVER.com
    HostName git.YOUR.GIT.SERVER.com
    User git
    IdentityFile ~/.ssh/id_git
    IdentitiesOnly yes
    ForwardAgent no
    IdentityAgent none
```
 
6. profit, or in this case, break even.

**Comment by moltob** [comment]
I must agree, the nag "Warning: Agent Forwarding" renders the standard developer workflow in VSCode almost useless. To workaround you can reduce the aforementioned config to s/th like:

```
Host <hostname>
    IdentityAgent none
    IdentityFile ~/.ssh/<keyfile>
```

**Comment by jgranzow86** [comment]
Using my mac and running Ansible playbooks on a remote machine that then uses ssh to get into all the machines listed causes this authorization to come up every time for every machine. This is extremely annoying. There needs to be a way to bypass this from coming up. When I'm hitting hundreds of machines using a playbook this is a show stopper for me to have to click authorize for each and every one of the machines for each and every task that runs in the playbook.

**Comment by nickwest** [comment]
I've also run into this issue and would love to see a fix that lets us specify which remote hosts should prompt and which should not.

Sometimes I connect to a dedicated VM where I am the only one with root access, so my socket has no risk of being hijacked and I'd prefer no prompts. Other times I connect to shared servers where the Bitwarden prompts protect my socket from misuse, even if a bad actor with root access attempted to use my open socket.

The current behavior is actually the more cautious default and protects against socket hijacking even if users aren't aware of this risk. But ideally we should be able to configure this per remote host.

Alternatively, setting this per-key would be a good solution too.

**Comment by BrainStone** [comment]
Generally speaking forwarded keys having the same toggle as normal key access would be a start.

But I agree, more fine grained settings wouldn't hurt. Though that absolutely should not hold this back. Rolling out a rough solution first is better than no solution.

**Comment by rcstanciu** [comment]
Any updates on this? This is making the agent forwarding feature unusable in its current form.

**Comment by Trojaner** [comment]
Just imagine the pain you have to go through when a larger git rebase is done and commits need to be re-signed because the git history is being rewritten.

I don't remember how often I had to approve this dialog, but I was prompted endless times (and consecutively), literally for every single commit created since the rebase base commit.

**Comment by CodySwagor** [comment]
Bumping this, this actively drives me insane on the daily.

**Comment by neuronull** [comment]
👋  just want to flag that this issue will be fixed in the v2 release of the Agent

**Comment by ashleyghooper** [comment]
@neuronull it would be great if it could be an option to still prompt, as I believe there is a genuine security risk if someone on the remote server is able to hijack one's ssh agent.

**Comment by neuronull** [comment]
👋 hello, we've released a v2 of the SSH Agent implementation in the `2026.7.0` version, which addresses this issue.
Please download the new release to get the fix. Thank you!

**Comment by ningw42** [comment]
Thank you @neuronull for the amazing work. I tested on the Windows build of `2026.7.0`. `Never` works as expected (no prompt, approved silently), but `Remember until vault is locked` is still the same as `Always`. Is that by design? 

Let me add more details:
1. When on `Never`, and the vault is locked, I have to unlock the vault first. Whenever the vault is unlocked, the ssh key access is approved. 
2. When on `Never`, and the vault is unlocked, the request is approved silently.
3. When on `Remember until vault is locked`, and the vault is locked, I have to unlock the vault first, then approve the request.
4. When on `Remember until vault is locked`, and the vault is unlocked, I still have to approve every ssh key access request.

1, 2, and 3 are totally reasonable behavior. But, for 4, I'd expect I need to approve the very first request (when vault is unlocked), but not the subsequent ones.

**Comment by neuronull** [comment]
👋  hi @ningw42 , thanks for trying it out and for the providing details in your report.

The logic that governs the Ask for Authorization setting _should_ be OS-agnostic. To that end, I've just re-confirmed that `Remember until vault is locked` is working as expected (not as # 4 in your list) , on MacOS. If you're still facing this behavior after my below recommendation, please open a new bug with these details, and also confirm whether or not you are using agent forwarding (which was a factor in the original report on this issue), and we'll dig into it.

In order to be certain that you've cleanly moved over to the v2 of the agent implementation, please completely close and re-open the Bitwarden app, and re-test this scenario # 4. Thank you

**Comment by ningw42** [comment]
Hi, @neuronull, I think I missed the most important information in my previous feedback. Those 4 tests are done on a remote host whose agent is forwarded from local (which is this issue was original talking about, which is also why I forgot to mention it). 

1. I tested the 4 scenarios **locally** on the same Windows host with the same build. All work as expected. The fourth scenario in my original test, now remembers my first approval.
2. I re-ran the same 4 scenarios **remotely with agent forwarded** from the same **Windows** host with the same build (the box is restarted between this test and the previous one). Exactly the same behavior as I reported in https://github.com/bitwarden/clients/issues/15695#issuecomment-5131946800.
3. I ran the same 4 scenarios **locally on a macOS host** with the latest build. All work as expected, the same as what is observed on a Windows host locally.
4. I ran the same 4 scenarios **remotely with agent forwarded** from the same **macOS** host. I have to approve every ssh key access request when I am on `Remember until vault is locked`. Exactly the same behavior as it is on Windows, i.e. the same as https://github.com/bitwarden/clients/issues/15695#issuecomment-5131946800

**Comment by neuronull** [comment]
Thanks for the additional details @ningw42, the symptom is clear now.

Two things:
1. are you self hosting by chance? If yes, you can try setting the v2 feature flag manually with instructions below. This goes in your [data.json file](https://bitwarden.com/help/configure-clients-selfhost/#desktop-apps)
2. try logging out and then quitting the desktop app entirely (make sure it's fully quit and not simply minimized to the tray) and restarting the app

If neither of those work, would you mind opening a new bug report for this? With the v2, the logic for this ask for auth with agent forwarding is totally different so the root cause of the bug is going to be different from this issue's original report running on the v1.


/// data.json

```json
{
	"stateVersion": 82,
	"global_desktopSettings_modalMode": {
		"isModalModeActive": false
	},
// Add this
	"global_config_featureFlagOverrides": {
		"ssh-agent-v2": true
	},
 ...
```

**Comment by ningw42** [comment]
Thank you @neuronull. 

Yes, I am on a selfhosted instance. I should have mentioned it. And yes, your latest instructions fixed the issue for me. I had an empty `global_config_featureFlagOverrides`. 

Edit: I followed the instructions on macOS, and it works too.
