### ISSUE TITLE
Number of login autofill suggestions badge on extension icon disappears

### ISSUE THREAD

**Issue by huntb4646** [bitwarden/clients#15810]
### Steps To Reproduce

1. Go to a website with a saved login.
2. Look at the extension icon

### Expected Result

The badge on the extension icon shows the number of login autofill suggestions associated with the current website.

### Actual Result

The badge is missing.

### Additional Context

Reinstalling the extension makes the badge re-appear temporarily, but then it goes away again after a while. The setting in Appearance named "Show number of login autofill suggestions on extension icon" is enabled. Toggling it off and on does not change the noted behavior or solve the issue.

I have another computer running almost the same setup with extension v2025.6.1 and there is no issue. Definitely seems to be an issue in browser v2025.7.0

https://www.reddit.com/r/Bitwarden/comments/1mbteu1/login_counter_on_extension_is_broken/

### Operating System

macOS

### Web Browser

Brave

### Browser Version

Brave 1.80.124 (Official Build) (x86_64) Chromium: 138.0.7204.168

### Environment Versions

Version: 2025.7.0

SDK: 'main (f2bc708)'

Server version (self-hosted): 2025.7.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cylayabw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by temp10min** [comment]
Yesterday i had the same issue here within Edge on Windows 10 - no counter on the icon, and the icon itself was gray. 

This morning, after the PC was in sleep mode for several hours (no PC nor browser restart performed), it appears fine - blue icon with counter of saved logins on it. 

I also found this post [https://community.bitwarden.com/t/chrome-brave-edge-icon-dont-show-number-of-login-after-last-update-ext/87253](url) which describes the same issue. 

[edit1] I just restarted Edge. At first the icon was in the usual blue color, but with the counter missing. After the browser fully finished loading, the icon turned gray again. 
My Edge session consists of 8 windows with about 500 tabs total, if that matters. 

[edit2] And, after a while, i noticed the icon and counter appearing fine again. The i clicked a link and it broke again.

**Comment by huntb4646** [comment]
This is a bug. There was a huge change to how this badge API worked from v2025.6.1 to v2025.7.0: https://github.com/bitwarden/clients/pull/14801 There is clearly an issue with it.

**Comment by thericle** [comment]
I have the same issue. Sometimes the counter appears, but most of the time it's missing. To be honest, the constant bugs after almost every release are getting quite tiring, at least for me, and the fact that this issue was closed just makes it worse.

**Comment by justindbaur** [comment]
We've received similar reports in other channels, I am reopening and will begin work on it today. It appears the issue is somewhat intermittent hence the initial response of unable to repro.

**Comment by bwbug** [comment]
In my experience, the badge counter appears when the extension is first unlocked, but if a browser web page is refreshed, then the counter disappears (Chrome, extension 2025.7.0).

**Comment by huntb4646** [comment]
I am in a weird state right now where the icon is greyed out (no badges either). It was like this when I started up my browser (after computer died and rebooted). It was greyed out as if I wasn't logged in, even though I was logged in but the vault was locked. Then I unlocked it successfully, but the extension has stayed in the greyed out state since during this browsing session. To be clear, this is only an issue with the icon/badges; I can do everything I normally do as the extension is unlocked.

**Comment by pumi** [comment]
This my post about this issue on bitwarden forum https://community.bitwarden.com/t/chrome-brave-edge-icon-dont-show-number-of-login-after-last-update-ext/87253

**Comment by pamperer562580892423** [comment]
I can add a new nuance to the BW icon issue: also the "opposite problem" seems to exist - the counter showing the number of logins, but the extension already locked itself in the meantime, resulting in this:

<img width="608" height="664" alt="Image" src="https://github.com/user-attachments/assets/83894211-c6f5-4602-a2a9-007fc86d258a" />

PS: The extension window was closed before the screenshot. The icon showed the "1" still, while the extension "locked" itself. Only when I opened the extension window again, I could see that the extension was already locked (= the screenshot)...

PPS: And yeah, extension version 2025.7.0 on Vivaldi, EU server region. And I already loggeed out/in, and even removed/reinstalled the extension.

And as mentioned before: it is not consistent. I would even say, most of the time, it works at the moment. But sometimes, it doesn't (= the BW icon doesn't reflect the current state).

**Comment by bilogic** [comment]
@pamperer562580892423 

Is yours 2025.7.0? Mine shows a lock icon when locked

<img width="394" height="471" alt="Image" src="https://github.com/user-attachments/assets/1bd22a04-9f4e-4bfb-a429-b42773e6bd2e" />

**Comment by bilogic** [comment]
For what it is worth, locking and unlocking brought back the badge, but once I refresh the web page, badge disappears again

<img width="395" height="444" alt="Image" src="https://github.com/user-attachments/assets/f0ae15ce-fcb0-4ece-b35c-c93e2abe4dc6" />

**Comment by pamperer562580892423** [comment]
> Is yours 2025.7.0?

Yep, 2025.7.0. I also added it now to my previous comment.

> Mine shows a lock icon when locked

Oh, sometimes mine does to. But sometimes not, since 2025.7.0.

**Comment by seaartic** [comment]
2025.7.0 has probably solved the following problem https://github.com/bitwarden/clients/issues/14979, but I have the mentioned problem in this report now.

**Comment by huntb4646** [comment]
To clarify my last comment (above): extension goes and stays grey (no badge or lock icon either). I then click it and lock it. That makes it blue again on the current tab; however, just clicking it to open it to unlock makes it grey again. In this state, opening a new tab seems to make it behave correctly - blue with lock icon and this behavior 'fixes' it on the current tab as well. Then I can unlock it and the lock badge goes away correctly. However, unlocking it does not do anything to correct behavior of the badge that shows login suggestion count - that is still missing until I open a new tab. Then on a new tab, the login suggestion count returns temporarily. On the first new tab, it returned. After I opened another, it went away again (and would not come back even for newly-opened tabs). I never saw it return for currently-opened tabs.

**Comment by bluecraank** [comment]
I have the same issue, missing badge!

**Comment by pamperer562580892423** [comment]
Unlocked extension with a BW icon showing "locked" is also possible:

<img width="606" height="661" alt="Image" src="https://github.com/user-attachments/assets/7c3fda8c-ee9d-4ab9-9759-e5ac18e63351" />

&nbsp;

(details to my system/configuration: see [my previous post](https://github.com/bitwarden/clients/issues/15810#issuecomment-3134596080))

**Comment by silversword411** [comment]
I do lots of new installs for new users.

The grey icon is usually brave after new extension install and login. It'll be grey till the browser is restarted.

For the missing numbers again new install, if you lock then unlock, sometimes start working for a short time but then numbers stop. Then vault reload from settings will get it working for a short time then it'll break again. Haven't found repeatable steps yet to replicate. I do see the new icon badge option. There's been 3-4 other options bugs in the past, the way options are saved/loaded must not be consistent and missing tests to validate each option to make sure it works every time there's a code change.

**Comment by PhilipStruthers** [comment]
I saw the number of autofill suggestions badge in the browser (brave) extenstion area disappear in the past few days, when i click on the extenstion icon the autofill suggestion is still present, but the icon no longer shows up on any site with active autofill suggestions

**Comment by bilogic** [comment]
@justindbaur it would be good to let us know if you still need more info. The number of comments here indicate it should be quite reproducible now.

**Comment by PhilipStruthers** [comment]
Issue seems to have been fixed today

**Comment by bwbug** [comment]
Not for me:

<img width="384" height="329" alt="Image" src="https://github.com/user-attachments/assets/3dffc91b-682c-4150-b470-39db0fe38ba9" />

**Comment by silversword411** [comment]
> Issue seems to have been fixed today

What version are you using?

**Comment by tanuj-05** [comment]
I had the same issue, but locking and then unlocking the vault solved it for me

**Comment by bwbug** [comment]
>locking and then unlocking the vault solved it for me

@tanuj-05 Did this solve the issue permanently for you?  If you refresh (re-load) the browser tab for a web page that has a URL match, does the counter remain visible after the page has been refreshed?

In my experience, the badge counter is visible after unlocking the vault, but when refreshing a web page, the counter disappears.  The badge counters can be restored by locking/unlocking the extension, or by doing an autofill, but disappears again on any web page that is re-loaded.

**Comment by mlekas** [comment]
Came here to say this is also happening to me, exactly as described above. The count appears once only at login, then disappears after any action (e.g. refresh page) and the count does not reappear until you lock/unlock app. Count is accurately stated inside the app, it's just the badge counter that doesn't update. I'm running Windows 11 24H2 and this is in the default Edge Browser (build 138.0.3351.121).

![Image](https://github.com/user-attachments/assets/ab0a73c8-ea9e-4fcd-9533-4b36bfcc8057)

<img width="254" height="286" alt="Image" src="https://github.com/user-attachments/assets/5e5ac2ed-cbbb-4b5a-899e-177962816dc6" />

**Comment by silversword411** [comment]
Every second or third release has stupid introduced bugs because the qa team sucks.

Makes you wonder about the code quality related to bitwardens security aspects

**Comment by silversword411** [comment]
There needs to be a Bitwarden stable that I can install for clients that is slow moving and feature reliable. What we have now is perpetual alpha/beta quality releases.

**Comment by MaximumBlast** [comment]
Same problem here

**Comment by cmeil** [comment]
> Every second or third release has stupid introduced bugs because the qa team sucks.
> 
> Makes you wonder about the code quality related to bitwardens security aspects

In my opinion this bug IS a security aspect, as it can sometimes result in the vault being shown as locked when in fact it is not.

**Comment by adriancuadrado** [comment]
I don't have this problem anymore.

* Version: 2025.7.0
* SDK: 'main (f2bc708)'
* Server version: 2025.7.2

Maybe they fixed it already?

**Comment by adriancuadrado** [comment]
> I don't have this problem anymore.
> 
> * Version: 2025.7.0
> * SDK: 'main (f2bc708)'
> * Server version: 2025.7.2
> 
> Maybe they fixed it already?

Nevermind, I just found a website that doesn't show the badge: https://dashboard.tawk.to/

**Comment by reinob** [comment]
The firefox version just got updated to 2025.7.0.. so the issue is now also there :(
Even if it's no big deal (though it could cause security snafus), I find it "amazing" that nothing is being done. It's like they dump a new & buggy version on us and then go on holidays?

**Comment by bwbug** [comment]
> I find it "amazing" that nothing is being done.

Something _is_ being done:

https://github.com/bitwarden/clients/issues/15810#issuecomment-3132570416

https://community.bitwarden.com/t/chrome-brave-edge-icon-dont-show-number-of-login-after-last-update-ext/87253/22

**Comment by sacp** [comment]
Seems to be back for me: 
[Brave 1.80.125 (Official Build) (64-bit)](https://brave.com/latest/)
Chromium: 138.0.7204.184
(Windows 10)

**Comment by bwbug** [comment]
Still not fixed for me.   The issue may _seem_ to be fixed (temporarily!) for some users, because the behavior is ***intermittent*** &mdash; although in my own case, I can reliably reproduce the disappearing badge counter by simply refreshing (<kbd>F5</kbd>) the active browser tab.

**Comment by silversword411** [comment]
Have a vote for Bitwarden Feature Request: [Stable chromium browser extension - Like Ubuntu LTS](https://community.bitwarden.com/t/stable-chromium-browser-extension-like-ubuntu-lts/87526)

**Comment by silversword411** [comment]
Trying to find the commit(s) and responsible person(s) that made this bug in the first place.

And who is supposed to be reviewing, and qa testing before releases are deployed.

Need to be finding the source, and accountability to this systemic problem and shine a light on it. The Bitwarden repos are such a complicated hairball to even understand can anyone help point the way?

**Comment by bwbug** [comment]
> Trying to find the commit(s)

See [upthread comment](https://github.com/bitwarden/clients/issues/15810#issuecomment-3130711485) by @huntb4646.

**Comment by Galixte** [comment]
I encounter the same issue on Opera GX.

Is a chromium fix has been submitted to Opera/Chrome Extension stores?

**Comment by pcostarg** [comment]
I have this issue for a couple of weeks now, at least. Using Vivaldi and the extension from the chrome store.

I have noticed that sometimes the number appears for a split of a second and the disappears.

**Comment by ghost** [comment]
This has been broken for a long while now. Not surprising BW team let this slip with the continued work on the awful redesign.

**Comment by jimbobjonesbob** [comment]
> This has been broken for a long while now. Not surprising BW team let this slip with the continued work on the awful redesign.

I know right. Pitiful

**Comment by lileixuan** [comment]
restart chrome it show the number badge, and then refresh the webpage it disappear.
chrome: 139.0.7258.128
Bitwarden: 2025.7.0

**Comment by pauljames19** [comment]
Having the same exact issue on Brave  (Chromium: 139.0.7258.127) with Bit warden extension 2025.7.0, it only works when I restart my PC for just a few minutes and and breaks. This is so frustrating!

**Comment by rinvelt** [comment]
Same here
Chrome: 139.0.7258.128 
Bitwarden: 2025.7.0

This is getting a bit long in the tooth.

**Comment by Galixte** [comment]
Hi @bitwarden-bot @bitwarden-devops-bot @bitwarden-charlie 

Why the 2025.7.1 isn’t available on Chrome Store and Opera Addons pages?
https://chromewebstore.google.com/detail/bitwarden-password-manage/nngceckbapebfimnlniiiahkandclblb
https://addons.opera.com/fr/extensions/details/bitwarden-free-password-manager/

**Comment by pamperer562580892423** [comment]
@Galixte No one from Bitwarden here, but just another user - but I think, 2025.7.1 was a "Firefox only" release:

<img width="1136" height="577" alt="Image" src="https://github.com/user-attachments/assets/b6eef78d-52d0-490a-8a78-7ca47dab5c52" />

Though I'm not sure myself, why the files for Chrome etc. also were listed / "released"...

**Comment by Galixte** [comment]
> [@Galixte](https://github.com/Galixte) …
> Though I'm not sure myself, why the files for Chrome etc. also were listed / "released"...

Because it’s not an exhaustive changelog.

**Comment by pamperer562580892423** [comment]
@Galixte:

> Because it’s not an exhaustive changelog.

Exactly. It seems to only contain a change for Firefox - so I'm not sure, what a Chrome or Opera version 2025.7.1 would bring you.

<img width="1242" height="375" alt="Image" src="https://github.com/user-attachments/assets/847ffb5d-e029-4c28-bca0-70ea0724f152" />

**Comment by Hukuma1** [comment]
+1. Kind of a bummer it's been this long without a fix.

**Comment by livni** [comment]
Reproduced
Chrome: 138.0.7204.185
Bitwarden: 2025.7.0

**Comment by lileixuan** [comment]
Still have problems.
Bitwarden: 2025.8.0

**Comment by huntb4646** [comment]
This PR looks like it might help the situation once it is merged and then included in a release: https://github.com/bitwarden/clients/pull/16087. I'm not really sure why the other PR was linked to this issue because it was included in browser v2025.8.0, and I don't think it fixes it.

**Comment by fabriziobagala** [comment]
@huntb4646 The badge problem also occurs on Firefox. The ticket I opened was closed because it was considered a duplicate of this one. I am reporting it so you can take a look at it https://github.com/bitwarden/clients/issues/15966

**Comment by TheLinuxGuy** [comment]
Please fix this issue.... it leads to very poor UX and end-users can't tell if a site already has saved credentials on the vault for a URI.

https://community.bitwarden.com/t/where-has-auto-fill-and-save-been-moved-once-again/87888/7

**Comment by ghost** [comment]
> Please fix this issue.... it leads to very poor UX and end-users can't tell if a site already has saved credentials on the vault for a URI.
> 
> https://community.bitwarden.com/t/where-has-auto-fill-and-save-been-moved-once-again/87888/7

If they cared about UX they wouldn't have proceeded with the awful redesign.

**Comment by livni** [comment]
@tavern2782 I don't think this thread is the place to discuss the merits of the redesign.  I personally like the UX redesign, except that it's a tad slower than before, but you and I together are not a correct sampling of the user base. Let BW's product team do it's job and let's stay focused on the bug at hand.

**Comment by KevinNovak** [comment]
+1, also having the this issue where no badge number appears

**Comment by tekdout** [comment]
+1 I also have this issue. It is very disorienting to not see any saved credentials for websites I frequent.

**Comment by rinvelt** [comment]
Still having this issue on 

Bitwarden - 2025.8.1
Chrome - 139.0.7258.139

**Comment by bwbug** [comment]
Same (on 2025.8.1) &mdash; for example, the badge counter always disappears when the browser tab is refreshed.

**Comment by bwbug** [comment]
139.0.7258.139 is the latest stable release of Chrome for Windows.

**Comment by mlekas** [comment]
Still happening on 2025.8.1 via Edge latest stable release (139.0.3405.111), though now the number reappears after switching tabs and switching back. Steps:
1. log into Bitwarden. Icon shows count of logins.
2. refresh website. Icon count disappears.
3. switch to a different tab, and wait ~2sec.
4. switch back to tab. Icon shows count of logins. 
5. goto 2

**Comment by bwbug** [comment]
@mlekas Upon further experimentation, I see pretty much the same behavior in Chrome 139.0.7258.139 with version 2025.8.1 &mdash; the badge counter disappears when a browser tab is refreshed, but reappears after switching browser tabs and switching back (or after locking and unlocking the extension).  In my case, though, I do not need to wait before switching back to the original browser tab.

**Comment by mlekas** [comment]
@bwbug Just checked and you're right, no delay is required when switching between tabs on Edge.

**Comment by Galixte** [comment]
Until this PR will not be merged this issue will continue: https://github.com/bitwarden/clients/pull/16087

**Comment by rinvelt** [comment]
> Until this PR will not be merged this issue will continue: [#16087](https://github.com/bitwarden/clients/pull/16087)

Helpful. Thanks!

**Comment by streetwolf** [comment]
I have the same issue on FX 142.  A workaround for me is holding down the CTRL key while clicking on the reload current page icon on the toolbar.  CTRL-R  doesn't work as a workaround for some reason. The workaround works for all sites but only lasts as long as I don't close Fx.

**Comment by lileixuan** [comment]
> Until this PR will not be merged this issue will continue: [#16087](https://github.com/bitwarden/clients/pull/16087)

This has been merged into the latest version 2025.8.1, but there are still issues. The numbers disappear when the page is refreshed, but they reappear after switching tabs. However, they disappear again upon refreshing.

**Comment by streetwolf** [comment]
Appears this problem has been fixed by the just released Version 2025.8.1 on Firefox at least.

**Comment by huntb4646** [comment]
2025.8.1 is definitely consistently better for me on Brave. However, the issue is not entirely resolved as switching tabs sometimes or reloading the page yields the same issue. As I noted in a previous comment, I believe there are still 1 or 2 unmerged PRs that might actually solve the issue.

**Comment by lileixuan** [comment]
There are still issues. The numbers disappear when the page is refreshed, but they reappear after switching tabs. However, they disappear again upon refreshing.

**Comment by jimbobjonesbob** [comment]
> Appears this problem has been fixed by the just released Version 2025.8.1 on Firefox at least.

appears to be fixed for me in FF as well.. so far ;) (even if refreshing, changing tabs, etc)

**Comment by falolaf** [comment]
Currently I see this a lot:
<img width="35" height="31" alt="Image" src="https://github.com/user-attachments/assets/70ced441-8c85-4c1b-9303-2d9bd9e404df" />

The number seems to appear after BW is locked but I have to switch between tabs. I.e., the number does not show up for the tab that is currently focused when BW lock. 

Firefox: 142.0.1
Bitwarden: 2025.8.1

**Comment by rinvelt** [comment]
Fixed for me in 2025.8.2

Thanks

**Comment by mlekas** [comment]
2025.8.2 on Edge 139.0.3405.125 ARM64, the issue continues (loses count on refresh, repopulates count after tab switch).

**Comment by huntb4646** [comment]
Apparently #16163 (to be included in next release) will supercede #16087 and thus this issue will hopefully finally be fixed then.

**Comment by Galixte** [comment]
> Apparently [#16163](https://github.com/bitwarden/clients/pull/16163) (to be included in next release) will supercede [#16087](https://github.com/bitwarden/clients/pull/16087) and thus this issue will hopefully finally be fixed then.

I can confirm v2025.9.0 released this morning includes PR #16163, take a look in changelog here: https://github.com/bitwarden/clients/compare/web-v2025.8.2...web-v2025.9.0

So, we have to wait for this version to be released: https://github.com/bitwarden/clients/releases

**Comment by MaximumBlast** [comment]
Glad to hear!!

**Comment by tekdout** [comment]
This is good to hear. How do we get the updated extension in Chrome?

**Comment by pamperer562580892423** [comment]
@tekdout:

> How do we get the updated extension in Chrome?

Wait until it gets released would be the first step. It's not even there yet.

**Comment by tekdout** [comment]
> [@tekdout](https://github.com/tekdout):
> 
> > How do we get the updated extension in Chrome?
> 
> Wait until it gets released would be the first step. It's not even there yet.

Thanks mate. Looking forward to this fix.

**Comment by Galixte** [comment]
- Opera extension 2025.9.0 is available and fixes this issue: https://addons.opera.com/fr/extensions/details/bitwarden-free-password-manager/
- Chrome Web Store extensions update isn’t available yet, it’s still on 2025.8.2: https://chromewebstore.google.com/detail/bitwarden-password-manage/nngceckbapebfimnlniiiahkandclblb
- Firefox too: https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/

It's only a matter of days, or even hours, before these become available. ;)  

------------

As if that weren't enough, another problem has cropped up in the latest version with Gmail, definitely… https://github.com/bitwarden/clients/issues/16483

**Comment by rinvelt** [comment]
Chrome extension on web store

**Comment by pamperer562580892423** [comment]
@rinvelt:

> Chrome extension on web store

Yeah, seems to be true since about a few years.

BTW, extension version 2025.9.0 is available in the Chrome Web Store.

**Comment by huntb4646** [comment]
5 browser extension releases, 55 days, 1 close/re-open, and 84 comments later (+ any comments on community forums/Reddit), this issue seems to be resolved.

**Comment by silversword411** [comment]
6th bug down. 

And the countdown starts to the next release without proper QA testing introducing another user facing bug.

Hire a proper QA team that will test new features before release.

:(

**Comment by bilogic** [comment]
WHY IS THIS A THING AGAIN ON 2025.12.0?

**Comment by silversword411** [comment]
> WHY IS THIS A THING AGAIN ON 2025.12.0?

Poor QA.

<img width="570" height="257" alt="Image" src="https://github.com/user-attachments/assets/f748ea86-722e-41f4-af0a-bd6fd0691972" />

Vote for a stable extension

https://community.bitwarden.com/t/lts-and-stable-release-channels-for-bitwarden-client-apps/87526

**Comment by Gerardv514** [comment]
@justindbaur @cylayabw @coroiu  I too am noticing this problem again.

**Comment by pamperer562580892423** [comment]
@bilogic @silversword411 @Gerardv514 Could you share some details about your systems? - So far, I don't see this issue with extension 2025.12.0 on Vivaldi / Windows 11 and it certainly would be helpful to identify if there is a certain pattern or if it can happen _everywhere_...

**Comment by Gerardv514** [comment]
> @bilogic @silversword411 @Gerardv514 Could you share some details about your systems? - So far, I don't see this issue with extension 2025.12.0 on Vivaldi / Windows 11 and it certainly would be helpful to identify if there is a certain pattern or if can happen everywhere...

On a brand new laptop, running latest windows 11 pro, latest chrome browser, also latest bw extension. I've tried logging out of the extension and logging back in but I don't see a blip of any change.

One thing, is that I logged into my chrome account and then everything was automatically redownloaded and sync'd. i did not manually reach out to the store and down load the extension.

**Comment by pamperer562580892423** [comment]
@Gerardv514 I'm on the EU cloud. You're self-hosting Vaultwarden, right?

PS:

> One thing, is that I logged into my chrome account and then everything was automatically redownloaded and sync'd. i did not manually reach out to the store and down load the extension.

Are you saying your extension was somehow "updated" (like re-installed from 2025.12.0 to 2025.12.0 again)?

**Comment by Gerardv514** [comment]
> @Gerardv514 I'm on the EU cloud. You're self-hosting Vaultwarden, right?
> 
> PS:
> 
> > One thing, is that I logged into my chrome account and then everything was automatically redownloaded and sync'd. i did not manually reach out to the store and down load the extension.
> 
> Are you saying your extension was somehow "updated" (like re-installed from 2025.12.0 to 2025.12.0 again)?


In this instance it's not the Vaultwarden container. Utilizing BW US cloud account. 

This is a new computer in which chrome was freshly installed, and then logged into so to sync all of my data. 

I just deleted the extension and reinstalled it and now the numeric on icon is showing.
