### ISSUE TITLE
Browser crash due to huge memory usage when unlocking vault. Version 2025.7.0

### ISSUE THREAD

**Issue by FixItDad** [bitwarden/clients#15899]
### Steps To Reproduce

First of all, thank you for your work on Bitwarden. It has been a great password manager.

1. Click on the BW icon in the toolbar.
2. Type my password and hit enter.

The browser "freezes". The BW extension popup dialog goes black.
Using 'top' from a terminal window, I watch firefox-bin process memory usage grow to over 70% of my 16 GB RAM and it begins to swap to disk.
Eventually the browser crashes or other process are killed due to out of memory.

BW acts as expected when I downgrade to 2025.6.1. Currently the firefox-bin process is using 6% after unlocking.
I do have a memory hard algorithm selected (Argon 2), but the behavior of 2025.7.0 was not exactly what I expected :).

It looks like my extension just updated today so I'm suspecting the new version is not playing well with my Firefox.

### Expected Result

After entering my password for the BW vault, I expect it to pause for a few seconds then display the vault in the popup dialog.

### Actual Result

The browser "freezes". The BW extension popup dialog goes black.
Using 'top' from a terminal window, I watch firefox-bin process memory usage grow to over 70% of my 16 GB RAM and it begins to swap to disk.
Eventually the browser crashes or other process are killed due to out of memory.

### Additional Context

Other extensions: uBlock Origin, Tree Style Tabs, Privacy Badger

### Operating System

Linux

### Operating System Version

Debian 12 (bookworm)

### Web Browser

Firefox

### Browser Version

141.0

### Environment Versions

THIS IS AFTER I DOWNGRADED from 2025.7.0. I was not able to authenticate in order to obtain the information for 2025.7.0

Version: 2025.6.1

SDK: 'main (1fa0f7a)'

Server version: 2025.7.2

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by solonovamax** [comment]
Can confirm that this occurs for me as well, when logging in.
I did not let it get to enough memory for the OOM to kick in, I just terminated the Extensions process (`about:processes`) before that.

Browser: Firefox Developer Edition 141.0b9
OS: Arch Linux 6.15.6-arch1-1 x86_64
Extension version: 2025.7.0

I can provide any additional information necessary for helping to identify the issue.

**Comment by solonovamax** [comment]
unsure if either of these will help at all:

if I use `about:memory` to inspect the memory usage of the extensions, I get the following for bitwarden:
```
│  │  │  ├──2,698,187,520 B (46.24%) -- {446900e4-71c2-419f-a6a7-df9c091e268b}
│  │  │  │  ├──2,698,026,240 B (46.23%) -- recvAPICall
│  │  │  │  │  ├────537,559,680 B (09.21%) ── browserAction.setBadgeText [119991]
│  │  │  │  │  ├────537,555,200 B (09.21%) ── browserAction.setBadgeBackgroundColor [119990]
│  │  │  │  │  ├────537,555,200 B (09.21%) ── browserAction.setIcon [119990]
│  │  │  │  │  ├────537,555,200 B (09.21%) ── sidebarAction.setIcon [119990]
│  │  │  │  │  ├────537,555,200 B (09.21%) ── sidebarAction.setTitle [119990]
│  │  │  │  │  ├──────9,838,080 B (00.17%) ── tabs.query [20]
│  │  │  │  │  ├────────349,440 B (00.01%) ── menusInternal.create [78]
│  │  │  │  │  ├─────────53,760 B (00.00%) ── menusInternal.removeAll [12]
│  │  │  │  │  └──────────4,480 B (00.00%) ── tabs.get
│  │  │  │  └────────161,280 B (00.00%) -- recvAddListener
│  │  │  │           ├───67,200 B (00.00%) ── storage.local.onChanged [15]
│  │  │  │           ├───58,240 B (00.00%) ── windows.onFocusChanged [13]
│  │  │  │           ├───13,440 B (00.00%) ── alarms.onAlarm [3]
│  │  │  │           ├───13,440 B (00.00%) ── tabs.onUpdated [3]
│  │  │  │           └────8,960 B (00.00%) ── tabs.onActivated [2]
```

after logging into the extension, the following log messages are produced:
```
WebAssembly is supported in this environment main.js:856:622882
downloadable font: Glyph bbox was incorrect (glyph ids 4 5 6 7 13 18 21 22 23 28 35 37 38 54 63 65 66 74 75 78 81 82 88 89 94) (font-family: "bwi-font" style:normal weight:400 stretch:100 src index:1) source: moz-extension://fe6f75c5-a379-4561-8522-8fe2197c6845/popup/fonts/bwi-font.c53459659794d90d0237.ttf
WASM SDK loaded in 85ms main.js:1:33077
State version: 72 main.js:1:33077
[KeyService] Deriving master key took 2729ms main.js:1:33077
Using SignalR for notifications background.js:1:885
Window not available in BulkEncryptService, decrypting sequentially background.js:1:885
[CipherService] Decrypting 558 ciphers took 220ms background.js:1:885
[SearchService] Building search index of 558 ciphers took 61ms background.js:1:885
[SignalR] WebSocket connected to wss://notifications.bitwarden.com/hub?access_token=[REDACTED] background.js:1:885
[SignalR] Using HubProtocol 'messagepack'. background.js:1:885
ForegroundSyncService did not receive a message back in a reasonable time. main.js:1:33119
[LockComponent] Sync took 30003ms main.js:1:33077
[LockComponent] Private key regeneration took 1ms main.js:1:33077
[SignalR] Connection disconnected with error 'Error: Server timeout elapsed without receiving a message from the server.'. background.js:1:966
Cannot find menu item with id root background.js:1:926
Cannot find menu item with id autofill 4 background.js:1:926
Cannot find menu item with id autofill-identity 2 background.js:1:926
Cannot find menu item with id autofill-card background.js:1:926
```

**Comment by ikirker** [comment]
I believe I'm also seeing this issue with:

 - **OS:** macOS Sonoma 14.7.5
 - **Browser:** Firefox 141.0 (aarch64)
 - **Extension version:** 2025.7.0

**Comment by dholbert** [comment]
I'm hitting this issue (massive hang after authenticating) as well, starting today, using Firefox Nightly 143.0a1 (2025-08-04) and Bitwarden 2025.7.0, on Ubuntu 25.04.

In my case:
 - The hang eventually stops hanging (after ~20 seconds)
 - I have 2000+ tabs open (all but ~50 of them are unloaded, i.e. restored via session-restore but "dormant" until I view them)
 - (this massive tab count has never caused Bitwarden to hang before, that I've noticed)
 - If I remove start Firefox with the same user-profile but just one window/tab, then there are no issues -- so I think this has to do with *either* my massive tab count, or with some particular tab that I have open that's causing trouble.
 
I captured a performance profile of the hang using the Firefox Profiler, and the backtrace shows that BitWarden is spinning its wheels with this backtrace (listing innermost function first):
```
getUrlObject [Extension "Bitwarden Password Manager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://c9b14213-ffcd-40ee-9488-bf198b862aee/background.js:1:14092]

getUrl [Extension "Bitwarden Password Manager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://c9b14213-ffcd-40ee-9488-bf198b862aee/background.js:1:10201]

getHost [Extension "Bitwarden Password Manager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://c9b14213-ffcd-40ee-9488-bf198b862aee/background.js:1:8842]

matchesUri [Extension "Bitwarden Password Manager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://c9b14213-ffcd-40ee-9488-bf198b862aee/background.js:1:283448]

23254/matchesUri/< [Extension "Bitwarden Password Manager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://c9b14213-ffcd-40ee-9488-bf198b862aee/background.js:1:285555]

some [self-hosted:137:19]

matchesUri [Extension "Bitwarden Password Manager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://c9b14213-ffcd-40ee-9488-bf198b862aee/background.js:1:285502]

23254/filterCiphersForUrl/</< [Extension "Bitwarden Password Manager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://c9b14213-ffcd-40ee-9488-bf198b862aee/background.js:1:667053]
filter [self-hosted:195:21]

23254/filterCiphersForUrl/< [Extension "Bitwarden Password Manager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://c9b14213-ffcd-40ee-9488-bf198b862aee/background.js:1:666837]
next [self-hosted:1253:23]

o [Extension "Bitwarden Password Manager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://c9b14213-ffcd-40ee-9488-bf198b862aee/background.js:1:659025]
```

**Comment by dholbert** [comment]
My profiling shows that Bitwarden's `getUrlObject` time (mentioned in my previous comment) is nearly all spent doing string allocation when constructing URL objects (from script).  Here's where that ends up in C++:
https://searchfox.org/mozilla-central/rev/4fd0d5e4669bfa2d0888b730684d8adea061fd30/dom/url/URL.cpp#37-45

I assume that URL object-allocation is coming from this line in Bitwarden's `getUrlObject` source:
https://github.com/bitwarden/clients/blob/80b74b3300e15b4ae414dc06044cc9b02b6c10a6/libs/common/src/platform/misc/utils.ts#L618


I added some logging to my local Firefox build's `dom/url/URL.cpp` C++ code to print out the text of the URL that we're creating, and it seems we're creating hundreds (or in some cases, thousands) of copies of each URL that's in my Bitwarden vault (i.e. each URL that's associated with one of my saved passwords), along with the URLs of tabs that I have open.  Or something along those lines.


In particular: I left it running for a little while before killing Firefox, and it logged 1668 copies of instances where Bitwarden was instantiating a URL() object for the string "androidapp://com.disney.disneyplus" (which is a URL I have saved in my vault, but obviously was not a URL that I had directly open in this Firefox-on-Linux session).

**Comment by dholbert** [comment]
So it looks like maybe Bitwarden is doing something like iterating all of the open tabs (even those that are dormant) and comparing *each tab's URL* against *all of the URLs in the vault*, perhaps?

Or doing something else that results in the backtrace that I quoted in [my comment above](https://github.com/bitwarden/clients/issues/15899#issuecomment-3153346363) spinning its wheels re-instantiating DOM URL objects for the same URLs from my vault over and over again, thousands of times at least.

**Comment by dholbert** [comment]
Maybe this is a regression from (or related to)  this commit from 3 weeks ago:
https://github.com/bitwarden/clients/commit/b4120e0e3f83e5cbbe9ecb258c9a67d364475158

(CC @nick-livefront )

At least: that commit touched some of the functions in my hang backtrace quoted above (`matchesUri` and `filterCiphersForUrl` at least).

**Comment by Myer** [comment]
Same issue on my side after updating Bitwarden to 2025.7.0.
Noticed freezing as soon as I entered my master password to unlock Bitwarden. Then checked Taskmanager and the memory of Firefox was increasing massively, when it reached ~20GB I killed it.

I also have many tabs open (~1100). I will try to revert to an older version for now.

* Firefox 141.0 (64-Bit)
* Windows 10 22H2 (Build 19045.6093)
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:141.0) Gecko/20100101 Firefox/141.0

Edit: Downgraded to version 2025.6.1 and the isse is gone.

**Comment by dholbert** [comment]
>  Edit: Downgraded to version 2025.6.1 and the isse is gone.

Same for me.

For other affected folks looking for a workaround until this is fixed, here are steps to downgrade:
1. Visit the "see all versions" page for Bitwarden add-on:  https://addons.mozilla.org/firefox/addon/bitwarden-password-manager/versions/
2. Scroll down to 2025.6.1 and click the "Download file" link to the bottom-right.
3. Firefox should show an install-extension prompt; click through to install that version.
4. If you want to stay on that version (and not auto-update to 2025.7.0 again) until this issue is fixed, you can visit `about:addons` and view the Bitwarden addon details there, and adjust `Allow automatic updates` to `Off`.  (Remember to restore that to "Default" or "On" when this issue is addressed, so that you don't miss out on security updates etc. in the future.)

**Comment by Dark-Thoughts** [comment]
Same here I think using flatpak Firefox on Bazzite. I did not check the ram usage but force closed the browser since it was hanging and the fourth time or so the login seemed to work. I do have a lot of tabs inherently open but unloaded and I'm pretty sure the extension updated yesterday, since it asked for notification permissions.

**Comment by pmurray17** [comment]
I have the same problem - When logging in Firefox freezes - Have to end task.

Windows 10
Firefox 141.0
Have many tabs open(approx 2000) 99.99% inactive, using extension Simple Tab Groups.

Downgraded to 2025.6.1 version and now works as expected.

**Comment by FixItDad** [comment]
Some additional details for my setup. I had about 380 tabs open across 4 windows. 

The first attempt where I had an issue, I had just been cleaning out emails from an outlook.office.com tab (used for work). I was deleting ~1000 emails and the delete was taking place in the background when I attempted to unlock BW. I originally thought this was related to the high memory usage, but after restarting Firefox, the BW behavior persisted with mostly dormant tabs.

I'll try to gather some additional info, but it may be a couple of days. Thanks to others for chiming in with good details.

**Comment by Irdiism** [comment]
The extension just updated and i hit the same issue. It is eating 32gb of ram and crashing Firefox. 

OS - Manjaro 
Firefox version: 141.0 (64-bit)
Bw extension:  2025.7.0
Tabs open (mostly inactive) over 1k. 

Let me know if something else is needed to help figure out the issue and ill gladly share it. 

Thanks for working on it.

**Comment by quexten** [comment]
Just to confirm a few details so we can get this fixed:

- ~~Is there any user affected here that is not on Firefox + a Linux distro (I.e mac / windows)~~ i see we have a windows report in this thread too
- Is there any user affected here that did not have *a lot of tabs* open
- Is there any user affected that did not switch their kdf to argon2 with a high memory setting

**Comment by tytan652** [comment]
I'm affected by the issue, I do have a lot of tabs open but my KDF algo is not argon2

**Comment by Dark-Thoughts** [comment]
Can confirm the ram bloat now as well. Basically even after the vault opens Firefox eats up like 15% of my CPU and the ram usage bloats to 11+ GB before it dumps something, a little later it bloatet up to 20+ GB at which point I force quit Firefox.

I did not switch to argon2, since I had to even look up what this is about - unless the setting got changed by default.

**Comment by lando-cal** [comment]
I started getting this last night. I'm a bit busy today, so I don't have much in the way of helpful diagnostics, but since @quexten asked about argon2, I thought I'd mention what may be an outlier in my case.

- I'm not on Argon2. In fact, when logging in to the web vault today to work around this issue for the moment, I see a banner saying "Low KDF iterations. Increase your iterations to improve the security of your account." 
- Checking the key setting shows SHA-256 with 100k iterations, but I'm not sure if that's the actual current setting, or the default for the text box in the UI.
- I'm on Windows 10, 64GB RAM, with a capable processor and GPU. I don't get a crash, and background apps remain functional, but the browser goes unresponsive after clicking login on Bitwarden.
- I generally have 500-1000 tabs in an unloaded state, with 5-50 loaded. Though, this issue happens even when a single tab is loaded.
- There is no issue when logging into the extension with an alternative (Mullvad) browser with only a few tabs (loaded or unloaded) open.

**Comment by ngj5-beasTxx** [comment]
**Issue:** LibreWolf web browser with a lot of tabs (most inactive) becomes unresponsive with abnormal CPU/RAM usage after logging into BitWarden extension version 2025.7.0

**Operating System:** Microsoft Windows 10 Enterprise LTSC 2021 (x64)
**Web Browser:** LibreWolf 141.0-1
**Extension Version:** BitWarden 2025.7.0
**KDF algorithm:** PBKDF2-256

**Temporary Solution:** Downgrade BitWarden extension to 2025.6.1 and disable automatic updates until a new version is released to address this bug. 

**BitWarden 2025.6.1 Extension Download:** https://addons.mozilla.org/firefox/downloads/file/4525374/bitwarden_password_manager-2025.6.1.xpi

**Comment by dholbert** [comment]
> Is there any user affected that did not switch their kdf to argon2 with a high memory setting

I'm not using argon2 -- I just checked https://vault.bitwarden.com/#/settings/security/security-keys to confirm.  I've got PBKDF2-256 with 700K iterations.

**Comment by ikirker** [comment]
> Just to confirm a few details so we can get this fixed:

I'm on macOS (Sonoma 14.7.5), and I haven't changed my KDF algorithm from the default PBKDF2 SHA-256. I do have a lot of tabs open, though.

**Comment by pranavmangal** [comment]
I am also facing this issue since today. Attempting to unlock the vault causes Firefox to hang (something that has never happened before, even with 1000+ tabs) and I had to kill the process manually.

Like many others here, I do have a couple hundred tabs open (mostly suspended).

I am on macOS 15.2, Firefox 141.0, Bitwarden 2025.7.0

**Comment by adhome1** [comment]
Also have lots of Tabs (>1000) and same hang/memory problem.

**Comment by tessus** [comment]
@quexten macOS 15.6 Intel
Firefox 141.0 (64-bit) and 141.0.2 (64-bit)
KDF PBKDF2 in bw
idk how many tabs, but I estimate a few hundred

**Comment by dholbert** [comment]
(For folks wondering how many tabs they have open: [Tab Stats](https://addons.mozilla.org/en-US/firefox/addon/tab-stats/) adds an icon at the right end of your tab-strip that can tell you how many tabs you have open, and offers more info & ways-to-close/deduplicate the tabs that you do have open.)

**Comment by granitlarge** [comment]
This happens to me when using Mullvad Browser, but not when using Google Chrome. I don't have to have any other tabs open for the bug to occur. I'm not using the extension, but vault.bitwarden.com

OS: macOS 14.6.1
Browser: Mullvad Browser 14.5.5 (based on Mozilla Firefox 128.13.0esr) / Google Chrome Version 138.0.7204.184 (Official Build) (x86_64)

**Comment by BlueDevil** [comment]
- Windows 10
- Waterfox 6.5.11, Firefox ESR 128 based
- Probably around 10k tabs, all but ~5 unloaded/discarded

Never had issues before the update to 2025.7.0.
And yes, I should probably try to break my habit and start using bookmarks instead.

**Comment by ec4x** [comment]
I can confirm this problem.

- Fedora 42 / Windows 11
- Firefox 141.0 / 141.0.2
- few hundred tabs open, only like 5 active. Normal memory consumption about 500MB. Upon opening Bitwarden extension the memory usage increases as high as 10GB.

I can confirm it seems like it is related to open tabs. Opening an new window and closing the one with the hundreds of tabs fixes the problem. As soon as I restore the window with more (>500) tabs the problem reoccurs.
Reinstalling didn't fix anything. I can also confirm this problem also occurs with an newly created Bitwarden account without any saved logins (or really anything).

**Comment by MrGamy** [comment]
Can confirm the Issue as well

- Windows 10
- Firefox 141
- Bitwarden 2025.7.0, updated yesterday

unlocking my vault in the browser extension causes a spike of over 10% CPU usage (Ryzen 7 7800X3D). Manually locking the vault drops CPU levels back to normal. This issue first appeared today / after the update yesterday.

for the statistics: 826 tabs spread over 26 windows, 34 currently loaded.



Here's a firefox profiler callback that might help:

`callParentAsyncFunction [resource://gre/modules/ExtensionChild.sys.mjs:928:26]
callAsyncFunction [resource://gre/modules/ExtensionChild.sys.mjs:659:20]
stub [resource://gre/modules/Schemas.sys.mjs:2986:14]
23254/setActionIcon/< [Extension "Bitwarden Passwortmanager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://6a50785e-6f19-4d61-8523-8d4e8502f317/background.js:1:1150577]
next [self-hosted:1253:23]
23254/Bx/< [Extension "Bitwarden Passwortmanager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://6a50785e-6f19-4d61-8523-8d4e8502f317/background.js:1:1149607]
Bx [Extension "Bitwarden Passwortmanager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://6a50785e-6f19-4d61-8523-8d4e8502f317/background.js:1:1149561]
setActionIcon [Extension "Bitwarden Passwortmanager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://6a50785e-6f19-4d61-8523-8d4e8502f317/background.js:1:1150532]
setIcon [Extension "Bitwarden Passwortmanager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://6a50785e-6f19-4d61-8523-8d4e8502f317/background.js:1:1150352]
23254/setState/< [Extension "Bitwarden Passwortmanager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://6a50785e-6f19-4d61-8523-8d4e8502f317/background.js:1:1150034]
next [self-hosted:1253:23]
23254/Bx/< [Extension "Bitwarden Passwortmanager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://6a50785e-6f19-4d61-8523-8d4e8502f317/background.js:1:1149607]
Bx [Extension "Bitwarden Passwortmanager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://6a50785e-6f19-4d61-8523-8d4e8502f317/background.js:1:1149561]
setState [Extension "Bitwarden Passwortmanager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://6a50785e-6f19-4d61-8523-8d4e8502f317/background.js:1:1149989]
23254/startListening/</< [Extension "Bitwarden Passwortmanager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://6a50785e-6f19-4d61-8523-8d4e8502f317/background.js:1:1153343]
next [self-hosted:1253:23]
o [Extension "Bitwarden Passwortmanager" (ID: {446900e4-71c2-419f-a6a7-df9c091e268b}): moz-extension://6a50785e-6f19-4d61-8523-8d4e8502f317/background.js:1:1152310]
promise callback
JSActor message handler`

<img width="3834" height="1675" alt="Image" src="https://github.com/user-attachments/assets/9b2fb8d6-c218-45eb-a117-7669badb8cff" />

**Comment by SpoonOfDoom** [comment]
EDIT: Nevermind, the Firefox update did alleviate the problem for a little bit, but now I'm back to the problematic behaviour. Was probably a coincidence. For completion's sake my info:
Firefox 141.0.2 (around 500 open tabs)
Windows 10 Pro 22H2 (Build 19045.6093)
Bitwarden 2025.7.0

[original post]
I was having the same problems, but I just notices there was a Firefox update to version 141.0.2 available, and that seems to have helped. Although now Bitwarden's icon seems "confused" - while locked it was the grey logo, after logging in it is now displaying the blue logo with the lock in the bottom right corner as if I had locked it, things like that. But at least it doesn't seem to make my browser unusable anymore.

**Comment by Myer** [comment]
Tried it on another PC, updated directly to Firefox 141.0.2 so I can't report how it behaves with 141.0.
With the new Bitwarden version using ~370 tabs it does not crash but still I see memory spikes and generally loading and interacting with the add-on is much slower compared to version 2025.6.1.

This is also on Windows 10 22H2 (Build 19045.6093). This account is using Argon2id with 3 iterations, 64MB and 4 parallelism.

Reverting to version 2025.6.1 still works fine with Firefox 141.0.2 so I will stay there and wait for a fix.

**Comment by bwbug** [comment]
> Although now Bitwarden's icon seems "confused"

@SpoonOfDoom The icon thing is a separate issue (#15810).

**Comment by radfaraf** [comment]
Same issue on a mac m4 mini with 24gb of ram. It only takes a few seconds till it seems to fill up my memory and lock up the machine, making the entire extension completely useable now.

**Comment by granitlarge** [comment]
> This happens to me when using Mullvad Browser, but not when using Google Chrome. I don't have to have any other tabs open for the bug to occur. I'm not using the extension, but vault.bitwarden.com
> 
> OS: macOS 14.6.1 Browser: Mullvad Browser 14.5.5 (based on Mozilla Firefox 128.13.0esr) / Google Chrome Version 138.0.7204.184 (Official Build) (x86_64)

It seems that this only occurs when the security level is set to "safer". If I set it to "standard" the problem disappears...

**Comment by Xiuhtec** [comment]
Can confirm same issue for me here, Windows 11, Firefox Nightly v143.0a1, since updating Bitwarden addon to 2025.7.0. Also have thousands of tabs opened (but inactive/backgrounded) as everyone else with the problem, so likely due to the new version iterating something across all tabs unnecessarily. Will downgrade to 2025.6.1 awaiting fix.

**Comment by lasombra** [comment]
I am seeing the same issue on Fedora 42, Firefox 141.0 and BitWarden 2025.7.0.

As soon as I unlock Firefox becomes unresponsive and memory, RSS, sky rockets between 7-24GB while BitWarden doesn't unlock. I can't even capture any data from Firefox when this happens.

`Exchange messages with programs other than Firefox` is disabled and BitWarden runs on private windows, if that helps.

```
> uname -a
Linux purplehaze 6.15.9-201.fc42.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Aug  2 11:37:34 UTC 2025 x86_64 GNU/Linux

> rpm -qi firefox
Name        : firefox
Version     : 141.0
Release     : 2.fc42
Architecture: x86_64
Install Date: Wed 23 Jul 2025 06:35:40 BST
Group       : Unspecified
Size        : 258717681
License     : LicenseRef-Callaway-MPLv1.1 OR GPL-2.0-or-later OR LicenseRef-Callaway-LGPLv2+
Signature   : (none)
Source RPM  : firefox-141.0-2.fc42.src.rpm
Build Date  : Fri 18 Jul 2025 12:28:57 BST
Build Host  : buildvm-x86-10.rdu3.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
```

**Comment by oletf** [comment]
Same issue here

- Firefox 141.0
- Windows 10 22H2
- Bitwarden extension 2025.7.0

Downgrading as suggested.

**Comment by DadasupR** [comment]
> Edit: Downgraded to version 2025.6.1 and the isse is gone.

@Myer Thanks for workaround !

**Comment by lautaropiatti** [comment]
Same issue here

- Firefox 141.0.2
- Windows 10 22H2
- Bitwarden Extension v 2025.7.0

**Comment by ashemedai** [comment]
Firefox 141.0.2, Windows 11 (24H2), Bitwarden 2025.7.0.

I got a few thousands of tabs open (welcome to doing a lot of research work). Trying to unlock Bitwarden resulted in my browser going from ~5-6 GiB to over 32 GiB before I terminated it. Also one or two of the CPU cores seem to get completely pegged during the unlock process.

Downgrading to 2025.6.1 instantly solved the problem.

**Comment by ronnyadsetts** [comment]
Just another "me too". Thousands of (inactive) tabs open. Browser goes unresponsive when vault unlock is done and task manager shows huge amounts of RAM in use. Reverting Bitwarden addon to 2025.6.1 restores functionality. I suggest pulling the latest version of the addon.

**Comment by Rob--W** [comment]
Hi, I'm a Firefox engineer here. Here is a STR, a profile and a preliminary analysis of the problem, which hopefully helps in resolving the issue.

I've created a test case that can be used to reliably reproduce the issue. I've described the STR below, and here is a shared profile: https://share.firefox.dev/4m4Ld57. The recording spans the period from when the popup was opened, a login was entered (at the 5 second mark), the popup was closed (around 27 seconds) and looking at `about:processes` to witness the CPU usage. The profile includes screenshots.

From a glance at the profile, the extension appears to be repeatedly calling extension APIs in very quick succession. You can see this by clicking on the "Parent Process" bar, and then the "Marker Table" tab, and enter "api_call" in the input field.
- While the popup is open, after a login, `tabs.query` is called many times. I counted 1009 calls, coincidentally the same as the number of tabs. It's not clear why exactly you're querying so many tabs individually, it seems that one query should be enough.
- When the popup is closed, the extension repeatedly calls `browserAction.setIcon`, `sidebarAction.setIcon`, `browserAction.setBadgeText`, `sidebarAction.setTitle`, `browserAction.setBadgeBackgroundColor`. In the almost 30 seconds of the profile, I see that this group of APIs is called 53k times.
- The total number of all extension API calls in this profile is 266k! And these are relatively expensive APIs, which impacts the performance.

STR:

Setup once: Prepare new Firefox profile with many tabs and Bitwarden installed:
   1. Launch Firefox with a new profile directory, whether from `about:profiles` or via the CLI with: `mkdir profdir; firefox -profile profdir`
   2. Visit https://profiler.firefox.com and click on the button to enable the profiler (for later use).
   3. Create many tabs (they don't even have to be loaded, can be in discarded state). Here is an example that automatically create 1000 discarded tabs: [open-many-tabs-ext.zip](https://github.com/user-attachments/files/21619948/open-many-tabs-ext.zip). Load this extension via about:debugging and click on the extension button (Extensions button > Open many tabs).
   4. Go to about:preferences and check the "Open previous windows and tabs" checkbox.
   5. Install Bitwarden add-on from https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/ (tested with version 2025.7.0)
   6. (pin BW extension button to toolbar for ease of access)
   7. Create a Bitwarden account with a throwaway email and password.
   6. Click on BW button and log in (optional: save the credentials in Firefox's built-in password manager).
   7. Visit `about:processes` and observe that Firefox and Extensions process are both using 100% CPU.

Reproduce again without the elaborate setup:
   1. Quit Firefox if it was open, and re-open it again. It should start with 1000 tabs and BW installed.
   2. (optional, if profiling:)
       - Install the "open many tabs" extension again, to make sure that there is an extension with a persistent background page; this is needed to keep the Extensions process alive later.
       - Click on the profiler button to start profiling (shortcut: Ctrl+Shift+1)
   3. Click on the BW button and try to log in.
   4. Visit `about:processes` and witness the CPU of Firefox and Extensions being at 100%.
   5. Visit `about:addons` and disable the BW add-on. Witness at `about:processes` that the CPU (and memory usage) goes down to normal levels.
   6. (optional, if profiling:) Click on the profiler button and stop profiling (shortcut: Ctrl+Shift+2).

Expected:
- No 100% CPU

Actual:
- 100% CPU of Firefox and Extensions process.

**Comment by jethron** [comment]
So it sounds like [BadgeService](https://github.com/bitwarden/clients/blob/8ae015f2d8463658ae605686dc68f70c15cf877a/apps/browser/src/platform/badge/badge.service.ts#L50) is the culprit?

I'm not sure why it wants to update the badge for every single tab at once eagerly every change, shouldn't you only need to do it for the active tab on [tabs.onActivated](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onActivated), or once per window, rather than per-tab every time?

`calculateStates` enumerating and sorting `states` every time when called in a loop over every tab also doesn't look great.

**Comment by xhorntail** [comment]
> > Although now Bitwarden's icon seems "confused"
> 
> [@SpoonOfDoom](https://github.com/SpoonOfDoom) The icon thing is a separate issue ([#15810](https://github.com/bitwarden/clients/issues/15810)).

Separate, yes. Decoupled, I'm not so sure. That issue references merge #14801 

That merge appears to be (to my admittedly infantile fluency in the project) the only merge within the last four months that touches `BrowserApi.tabsQuery()` much (if at all). ([See notes](https://github.com/bitwarden/clients/issues/15899#issuecomment-3160394550) by FF engineer, @Rob--W )

There also appears to have been some [speculation on the matter of multi-tab performance](https://github.com/bitwarden/clients/pull/14801#discussion_r2172365330) in pre-merge discussion. Not to say I'm confident that said speculation is actually relevant to the fix.

Hopefully this provides at least a crumb of foundation, and can save a bit of time for whoever (with actual project knowledge) picks this up.

Lastly, to affirm the [sentiment of another user](https://github.com/bitwarden/clients/issues/15810#issuecomment-3148300939) in #15810:
> There needs to be a Bitwarden stable that I can install for clients that is slow moving and feature reliable. What we have now is perpetual alpha/beta quality releases.

My own thoughts have mirrored this for the past 6 months or so of releases.

**Comment by bwbug** [comment]
>> There needs to be a Bitwarden stable that I can install for clients that is slow moving and feature reliable. What we have now is perpetual alpha/beta quality releases.

For anybody interested in this, the best way to get Bitwarden's attention would be to vote for the following feature request in the Bitwarden Community Forum:\*

https://community.bitwarden.com/t/lts-and-stable-release-channels-for-bitwarden-client-apps/87526/

&nbsp;

----------


\*<sub>For those new to the Community Forum, please note that it is based on the Discourse platform, which assigns user "trust levels" that define your forum privileges; to unlock the ability to vote for feature requests, you must advance from "new user" (TL0) to "basic user" (TL1).  To be promoted to TL1, you must first spend some time on the forum reading comments in various threads.</sub>

**Comment by dwolff** [comment]
For the record: I've just updated Firefox to the latest version on my Ubuntu box to 141.0.3 and the problem isn't happening anymore. The only detail is that, after I login, the Bitwarden icon on the toolbar remains the same (the blue shield with the black lock on the lower right) - that was different on earlier versions, where the black lock would disappear after a successful login.

Maybe @Rob--W has something to do with it? :)

**Comment by zesty** [comment]
me too: MANY tabs open

verified that it works no problem in a clean/refreshed profile with a single tab open

got the downgrade from: https://addons.mozilla.org/firefox/addon/bitwarden-password-manager/versions/

ref w/ instructions: https://github.com/bitwarden/clients/issues/15899#issuecomment-3153870449

firefox: 141.0.3
OS: Ubuntu 24.04.3 LTS

**Comment by dwolff** [comment]
> For the record: I've just updated Firefox to the latest version on my Ubuntu box to 141.0.3 and the problem isn't happening anymore. The only detail is that, after I login, the Bitwarden icon on the toolbar remains the same (the blue shield with the black lock on the lower right) - that was different on earlier versions, where the black lock would disappear after a successful login.
> 
> Maybe [@Rob--W](https://github.com/Rob--W) has something to do with it? :)

Also, for the record, looking at what @zesty just posted: I have a lot of tabs opened and I'm using the same old profile (2+ years old).

**Comment by FeMaster1** [comment]
Firefox 141.0.3
Windows 10
Bitwarden 2025.7.0
Tabs: 1000's

Firefox udated to 141.0.3 for me tonight, and I can confirm that with Bitwarden 2025.7.0, the problem still exists.

I was under the impression that the Firefox update is what caused the problem as everything had been working fine until this evening. After filing a support request I was pointed in this direction. I now see that it was actually Bitwarden that must have updated this evening and caused the memory consumption issue. I have rolled back to 2025.6.1 for the time being, which is working perfectly for me, while I await the fixed version to show up in the Mozilla / Firefox Extensions "store".

**Comment by julemand101** [comment]
Since it is not clear from the issue report, a fix have been made and are part of the hotfix 2025.7.1 (https://github.com/bitwarden/clients/commits/browser-v2025.7.1/) which are now available as Firefox extension and should be updated automatically or can manually be updated by trigger a check for extension updates.

I have only quickly verified the issue and it seems to have fixed the problems I had with the extension.

**Comment by StentMan** [comment]
Was 2025.7.1 supposed to fix this issue? I don't think it did.
I'm still experiencing the same RAM usage issue.

**Comment by DadasupR** [comment]
@julemand101 thanks !
Fixed here with Bitwarden 2025.7.1 Firefox 141.0.3 & Windows 10 and tons of tabs

**Comment by DadasupR** [comment]
> Was 2025.7.1 supposed to fix this issue? I don't think it did. I'm still experiencing the same RAM usage issue.

No more crash here, you can use about:memory to free up memory usage.
I have 6.8Gb ram used by tabs and only 350Mb used for extension with the update 2025.7.1 (but many other extension than Bitwarden too).

**Comment by lasombra** [comment]
2025.7.1 fixed it for me, but unlocking still triggers a sustained CPU peak and the unlocking process takes longer than 2025.6.1, but it's working.

**Comment by Dark-Thoughts** [comment]
Latest version fixed it for me. No noticeable performance hits on my end either while checking the system monitor.

**Comment by trmartin4** [comment]
Hello!  As you have noted, we believe this has been resolved with the release of `2025.7.1` version of the extension.

We do still have more improvements planned in the performance, as noted by @lasombra:

> unlocking still triggers a sustained CPU peak and the unlocking process takes longer than 2025.6.1, but it's working.

We will be addressing those very soon, but we wanted to get a version out quickly that addressed the extremely high memory consumption and crashing.

Thank you for your patience as we worked through this.  We will keep this issue open until we address with the follow-up work as well.

**Comment by nollinvoyd** [comment]
I originally posted here.[https://community.bitwarden.com/t/fill-in-problem-after-update-today/87493/14](url)

One user there mentions they were never affected, but doesn't use Firefox.  

I use Firefox 141, and the symptoms I experience seem to indicate to me the extreme memory usage issue,  I do have a ton of tabs, so I suppose that might be an irritation of sorts, but I must to revert to v2025.6.1, which still works fine.  

For me, both updates that follow 2025.6.1 are not usable. Same symptoms.  

Never gets beyond this

![Image](https://github.com/user-attachments/assets/8aff336e-f94f-4f3d-93de-78956e4a81d4)

Disables my toolbar buttons. No menu.

![Image](https://github.com/user-attachments/assets/eeae2955-aa2a-4ee1-bbd8-94776c0d6470)
Disables/crashes the browser

**Comment by Keiyuu** [comment]
Unfortunately 2025.7.1 doesn't fix it for me.
I went back to 2025.6.1, which was the last version without the issue.

Windows 10
Firefox 141.0.3 (64-bit)
About 10k tabs

**Comment by zesty** [comment]
> We will be addressing those very soon, but we wanted to get a version out quickly that addressed the extremely high memory consumption and crashing.

There is a "freeze" and/or resource consumption every time autofill is used, not just on unlock/login in the fixed version — temporary and recovering, but very noticeable.

EDIT: I must be more patient than I thought: it takes 20+ seconds to recover

**Comment by StentMan** [comment]
My feedback was lacking any information, sorry about that.
Updating to 2025.7.1 didn't solve the memory issue for me. Tried it with Firefox 141.0.2 and after the update to 141.0.3 on Windows 10.
According to Tab Session Manager I have 5880 tabs open.
Currently using 2025.6.1 with auto update off as a workaround.

**Edit:** Since it's so consistently easy to recreate (and rollback to the stable version), let me know if there's any more information you need to help track it down (logs, screenshots, etc.).

**Comment by hhyyrylainen** [comment]
I can login again with version `2025.7.1` however it takes 35 seconds and over 4.5 GB of RAM use on the web extensions process of Firefox. That would kind of be usable *but* the same delay (and memory use) happens *each time* I try to fill in a password. That's totally ridiculous as it is faster to manually type in everything except the longest passwords than to auto fill them.

**Comment by nollinvoyd** [comment]
Firefox 141.03, Win 10

I just ran some amateur experiments using 125.7.1

First with a clean install, with not nearly the "excessive" amount of tabs in my default profile.  No perceptible problems.

Then, my default profile, with the session removed.  No tabs.  No problems. 

Last, session restored to the default profile.  Attempted master password app login.  That gear just spun, until I stopped it.  I then opened Bitwarden in the sidebar, to try to input the master password there.  However, it was "already" logged in.  

However, I was still not able to use "fill" on the BItwarden website until I reverted back to v2025.6.1.

**Comment by alexonpeace** [comment]
Yeah, I wouldn't exactly call `2025.7.1` a fix
`2025.6.1` is still infinitely faster

**Comment by megamorphg** [comment]
Wish I found this issue out before I spent the past days rebuilding my main profile completely from scratch. I thought it was some renegade about:config or extension conflict. Oh well, at least now my main profile is faster. Downgraded to 2025.6.1 and works fine.

Why does Bitwarden 7 extension even care about the number of tabs when triggering auto-fill? I have ~2 thousand tabs but 99% hidden and unloaded.

FYI: Bitwarden hangs up and freezes Firefox extensions and browser processing for me for minutes whenever:
- first login to vault
- pressing autofill keyboard shortcut
- pressing fill from the vault menu

Only non-freezing way to use it was after logging in making sure to copy the password and paste.

**Comment by killerbee13** [comment]
2025.7.1 still has this problem for me, unlocking bitwarden causes it to load for for nearly a minute and brings bitwarden memory use from 486MB (already 4x higher than next highest extension) to 4170MB. Eventually, this time, the extension dropped back down to about 452MB, which is the first time I haven't had to kill the extension to bring the browser back to normal responsiveness. I have 7448 tabs currently 'open' but almost all are discarded via auto tab discard extension.

**Comment by ashemedai** [comment]
Agreed, 2025.7.1 is an improvement in that it doesn't lock the browser. But almost every time I unlock or autofill it will peg one of my 16 cores (AMD Ryzen 7 7800X3D) for 100% and memory increases by 4 GiB. It will take ¬20 seconds before I can log in or autofill.

**Comment by StentMan** [comment]
I just saw v2025.8.1 was released. Did that one fix the issue?

**Comment by EvilBMP** [comment]
Just tried it in Firefox (v142.0.1 - around 450 Tabs open) and it is better - doesn't seem to freeze the browser anymore - but still got higher RAM usage compared to v2025.6.1

**Comment by DadasupR** [comment]
> I just saw v2025.8.1 was released. Did that one fix the issue?

Still unusable on low perfs hardware (i5-8350 + 16Gb Ram) with FF v142.0.1 and approx 200 tabs.

**Comment by tessus** [comment]
> i5-8350 + 16Gb Ram

I wouldn't consider this low perf hardware. What do the bitwarden devs think a browser extension should require? A 128-core threadripper with 256GB of RAM? There is clearly still an issue and instead of reverting the commit that caused this, 4 releases later the massive resource usage is still prevalent. Btw, 2025.8.2 doesn't fix it either.

**Comment by DadasupR** [comment]
> > i5-8350 + 16Gb Ram
> 
> I wouldn't consider this low perf hardware. What do the bitwarden devs think a browser extension should require? A 128-core threadripper with 256GB of RAM? There is clearly still an issue and instead of reverting the commit that caused this, 4 releases later the massive resource usage is still prevalent. Btw, 2025.8.2 doesn't fix it either.

I agree with you but it was just in comparison to my other post where I indicate that v2025.7.1 fixed the crash problem for my "high perfs" config I7-6700 + 64Gb ram and more than 2k tabs here:

https://github.com/bitwarden/clients/issues/15899#issuecomment-3167315005

But this is without taking into account the rest of the additional load which also runs on the machines.

**Comment by alexonpeace** [comment]
> > i5-8350 + 16Gb Ram
> 
> I wouldn't consider this low perf hardware. What do the bitwarden devs think a browser extension should require? A 128-core threadripper with 256GB of RAM? There is clearly still an issue and instead of reverting the commit that caused this, 4 releases later the massive resource usage is still prevalent. Btw, 2025.8.2 doesn't fix it either.

Agreed, I feel they just gave up on Firefox lately.

**Comment by EvilBMP** [comment]
> Agreed, I feel they just gave up on Firefox lately.

My colleagues use different browsers - Chrome, Brave, Opera. They have issues as well with the latest version and many open tabs. As all of them are Chromium based, I think it's not only a Firefox issue.

**Comment by ashemedai** [comment]
FWIW, version 2025.8.2 of the extension with Firefox 142.0.1 works speedily again for me.

**Comment by StentMan** [comment]
> FWIW, version 2025.8.2 of the extension with Firefox 142.0.1 works speedily again for me.

Thank you for letting us know.

**Comment by tessus** [comment]
> 2025.8.2 of the extension works speedily again for me

Hmmm, it doesn't fix it for me. I guess I will have to run more tests on different OS and browser versions.

Update: I've tested 2025.9.0 on multiple OS and browsers and it seems that the issue has been resolved. A big shout out to the devs!

**Comment by FixItDad** [comment]
Running 2025.9.0 now and no issues seen after some initial testing. Thanks to all who contributed and implemented the fix.

**Comment by TapGhoul** [comment]
I will mention - with a large database, it can still take time to unlock. I have 2 accounts, one with under 50 entries and one with over 200, and the one with over 200 takes longer to unlock than the version prior to the one for this bug, while the one with under 50 is smooth as before the aforementioned version, so there is likely still some kind of performance regression here.
That being said, it is generally more stable.

**Comment by megamorphg** [comment]
Just upgraded from 2025.6.0 to 2025.9.0 and it is just as fast (if not faster) on both of my laptops, one with 2000+ tabs and the other with 300 tabs. And hundreds of Bitwarden entries.
So I think it's working fine, too!

@TapGhoul you might want to look into other root causes

**Comment by SpoonOfDoom** [comment]
Can confirm, seems to be working fine for me as well. Thanks to everyone reporting back, and to the people fixing it of course!

**Comment by TapGhoul** [comment]
@megamorphg I have no idea, because rolling back doesn't have the lag on unlock. Though if it is the tabs, that could be it - I have most tabs suspended (firefox native behaviour) but I have around 2400 tabs or so, but the fact this doesn't happen on the old version leads me to believe that may not be related.

**Comment by DadasupR** [comment]
> I will mention - with a large database, it can still take time to unlock. I have 2 accounts, one with under 50 entries and one with over 200, and the one with over 200 takes longer to unlock than the version prior to the one for this bug, while the one with under 50 is smooth as before the aforementioned version, so there is likely still some kind of performance regression here. That being said, it is generally more stable.

Thanks ! 
Switched on default view (filter in addon) personal vault instead of organisation vault 1200 vs 4000 entries in db make a good difference !
Tested with another user with only 300 entries is very faster.
Whether it's a single tab or multiple, it's remarkable.
