### ISSUE TITLE
Web v2025.8.0 does not start with Docker

### ISSUE THREAD

**Issue by CirnoT** [bitwarden/clients#16116]
### Steps To Reproduce

Web v2025.08.0 contains https://github.com/bitwarden/clients/pull/15270 which breaks Docker environments with `LOCAL_GID` and `LOCAL_UID` unset. Embedded `entrypoint.sh` attempts to create new user and group `bitwarden`, with UID/GID 65534, however used Alpine image already occupies these IDs with user `nobody` and group `nogroup`.

### Expected Result

Container starts properly

### Actual Result

```
chown: unknown user/group bitwarden:bitwarden
chown: unknown user/group bitwarden:bitwarden
chown: unknown user/group bitwarden:bitwarden
chown: unknown user/group bitwarden:bitwarden
error: failed switching to "bitwarden:bitwarden": unable to find user bitwarden: no matching entries in passwd file
```

Additionally, while `addgroup` command fails, its error is suppressed due to `|| true`. Removing suppression provides actual (and this time useful) error message:
```
addgroup: gid '65534' in use
adduser: unknown group bitwarden
```

### Operating System

Linux

### Web Browser

Chrome

### Build Version

v2025.08.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by Flow86** [comment]
Hi,

see https://github.com/bitwarden/server/issues/6233,

If you have a uid.env file using e.g LOCAL_GID=1 you also run into that error.

In the old archived [web](https://github.com/bitwarden/web/blob/ee4afdd0f215ddbfdd0e90bd229dfde6b4a4bffb/entrypoint.sh#L24) entrypoint it did a groupmod if groupadd did not work

**Comment by kraaas** [comment]
I have the same issue
47413e84312e   ghcr.io/bitwarden/web:2025.8.0             "/entrypoint.sh"   14 minutes ago   Restarting (1) 16 seconds ago

error: failed switching to "bitwarden:bitwarden": unable to find user bitwarden: no matching entries in passwd file
chown: unknown user/group bitwarden:bitwarden
chown: unknown user/group bitwarden:bitwarden
chown: unknown user/group bitwarden:bitwarden
chown: unknown user/group bitwarden:bitwarden

**Comment by Flow86** [comment]
I solved my issue by changing the LOCAL_UID/GID in env/uid.env together with changing the host users UID/GID to something not present in the container. don't forget to chgrp/chown your local data directory then properly too

**Comment by Esotrik** [comment]
I have the same issue after updating to v2025.08.0

**Comment by asch8505** [comment]
I have the same issue with v2025.08.0

**Comment by dducm** [comment]
I have the same issue with v2025.08.0

**Comment by wargamez** [comment]
Same here

**Comment by Snowrisk** [comment]
Changing the LOCAL_UID/GID in env/uid.env to the bitwarden-user UID/GID with a following restart (bitwarden.sh restart) worked for me.

**Comment by kraaas** [comment]
> Changing the LOCAL_UID/GID in env/uid.env to the bitwarden-user UID/GID with a following restart (bitwarden.sh restart) worked for me.

this one solve the issue for me also, as my bitwarden user is not named "bitwarden". Ususally UID/GID of the the bitwarden user is 1000

**Comment by Esotrik** [comment]
> Changing the LOCAL_UID/GID in env/uid.env to the bitwarden-user UID/GID with a following restart (bitwarden.sh restart) worked for me.

The uid.env is empty for me. What is supposed to be in there?

**Comment by kraaas** [comment]
the commented entries were old values:

```
#LOCAL_UID=65534
#LOCAL_GID=65534
LOCAL_UID=1000
LOCAL_GID=1000
```

**Comment by neydah700** [comment]
Same problem UID/GID values in env/uid.env are correct.

**Comment by bglf83** [comment]
I noticed that the new bitwarden self hosted documentation requires the creation of a "bitwarden" account in the process. I went back and did this and also created the group. I used the UID and GID from the account and group in the UID.env file and this seems be ok now.

I have been running bitwarden self-hosted for a few years, i am not sure if those things were always required or not.  My UID and GID  were also both set to 65534.


https://bitwarden.com/help/install-on-premise-linux/

**Comment by CirnoT** [comment]
> I noticed that the new bitwarden self hosted documentation requires the creation of a "bitwarden" account in the process. I went back and did this and also created the group. I used the UID and GID from the account and group in the UID.env file and this seems be ok now.

It has been there since at least 2022, however the issue is still valid as 65534 is used whenever Docker is executed as `root`, which is always the case for [Windows](https://bitwarden.com/help/install-on-premise-windows/) deployments.

**Comment by danieled-it** [comment]
Checked and I already had since years a decent `env/uid.env` file with:
```bash
LOCAL_UID=1055
LOCAL_GID=100
```
(typical Synology setup)

```bash
bitwarden@DiskStation:/$ id
uid=1055(bitwarden) gid=100(users) groups=100(users),101(administrators),65543(docker)
```

And these are clearly being picked up:

```bash
bitwarden@DiskStation:/$ docker inspect --format '{{range .Config.Env}}{{println .}}{{end}}' bitwarden-web
LOCAL_GID=100
ASPNETCORE_ENVIRONMENT=Production
globalSettings__selfHosted=true
globalSettings__baseServiceUri__vault=http://localhost
globalSettings__pushRelayBaseUri=https://push.bitwarden.com
LOCAL_UID=1055
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
APP_UID=1654
ASPNETCORE_HTTP_PORTS=8080
DOTNET_RUNNING_IN_CONTAINER=true
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
DOTNET_VERSION=8.0.19
ASPNET_VERSION=8.0.19
ASPNETCORE_URLS=http://+:5000
```

But still getting the failure described in the issue, for now the only way I found to keep my service up and running was to tweak the `docker/docker-compose.yml` putting back web to version 2025.7.2 and no, it didn't pick the change I tried to apply to `docker/docker-compose.override.yml`.

**Comment by DimebagCFH** [comment]
Thanks for sharing the solution
If we changed the UID/GID to 1000 i.e., no risk of any security breach or things like that ?

**Comment by EdouardVanbelle** [comment]
Hello, on my side I created a local `bitwarden` account,
ensured that this user belongs to the `docker` group
chown the bitwarden data path to this user
and mapped the corresponding UID/GID in env/uid.env

you can obtain id though the command
```
# id bitwarden
uid=1003(bitwarden) gid=1003(bitwarden) groups=1003(bitwarden),100(users),117(docker)
```

This solved the issue and fixed my old "root" installation

**Comment by bglf83** [comment]
> Thanks for sharing the solution If we changed the UID/GID to 1000 i.e., no risk of any security breach or things like that ?

I think you would want to create a restricted account that only has rights to the required directories, then use the UID and GID from that account.

**Comment by CirnoT** [comment]
@danieled-it You're hitting same issue but for different reason. Your `bitwarden` user does not have dedicated group, instead using built-in group `users` with GID 100. That GID is taken on Alpine images too, which breaks in same way as described in original issue.

**Comment by danieled-it** [comment]
@CirnoT you are the real MVP, gotta admit I totally missed _that particular detail_ and indeed creating a dedicated group for it and adjusting the `uid.env` file did the trick.

**Comment by heliohenriques** [comment]
Same issue here.
Changed the UID and GID to the values collected from id -u and id -g and not solved the problem.

**Comment by KaiLeoKor** [comment]
Same Issues here on a Self-Hosted Windows installation.
How would one go about applying any of these fixes in Windows?

**Comment by jp3301** [comment]
I also have been unable to resolve this on Windows

**Comment by CirnoT** [comment]
Suggested workaround for Windows installations would be to stay on previous version until this is resolved in #16124 and new release containing fix is out.

Alternatively, if you absolutely must update to 2025.8.0, you might modify `docker\docker-compose.yml` as such:
```diff
  web:
    image: ghcr.io/bitwarden/web:latest
    container_name: bitwarden-web
    restart: always
    volumes:
      - ../web:/etc/bitwarden/web
+   user: 65534:65534
    env_file:
      - global.env
      - ../env/uid.env
```

This will run `web` container as `nobody:nogroup` and skip problematic check in entrypoint. Do not use this fix on Linux deployments, unless you know that you have been running as `65534` before. Make sure to remove this workaround as soon as fix is out.

**Comment by bradwilson** [comment]
Alternatively, I was able to roll the web container back to `ghcr.io/bitwarden/web:2025.7.2` and left the rest of everything running on `:2025.8.0`. I haven't found any issues (yet), but if I do, I'll use the `user:` trick.

**Comment by e42sh** [comment]
> Alternatively, I was able to roll the web container back to `ghcr.io/bitwarden/web:2025.7.2` and left the rest of everything running on `:2025.8.0`. I haven't found any issues (yet), but if I do, I'll use the `user:` trick.

I did that also for the nginx container. Worked for me.

**Comment by dr3st** [comment]
How i fixed it ($ANYDIR is any dir, for example: /opt/bitwarden)

- create local user on machine (e.g. UID 2001, GID 2001, maybe)
- $ANYDIR/bitwarden.sh stop
- edit $ANY_DIR/bwdata/env/uid.env and set:
```
LOCAL_UID=2001
LOCAL_GID=2001
```
- chown -R 2001:2001 $ANY_DIR/bwdata
- $ANYDIR/bitwarden.sh start

The script may inform you about running script as root. If you want to remove the warning, just execute the script as nonroot, but with permission to exec docker commands (usermod -a -G docker $USERNAME)....

Why this may fix:

The reason is, the web container runs addgroup and adduser (see /entrypoint.sh) with UID/GID 65534, which may be problematic, while "nobody:nobody" already exist with this ID (when LOCAL_UID/LOCAL_GID is 0).
So just set the LOCAL_UID, LOCAL_GID, because the file (uid.env) will be used in bwdata/docker/docker-compose.yml, and the web container can work with this ID instead of 65534...

Hope this can help anyone to fix it :)

**Comment by Acrobutt** [comment]
> Hope this can help anyone to fix it :)

Appreciate your help. This works!

**Comment by aj-bw** [comment]
Hi all! This issue should be resolved in the latest self host release -> https://github.com/bitwarden/self-host/releases/tag/v2025.8.1

**Comment by rikwijnen** [comment]
I just updated to 2025.8.2 and the problem is back;

chown: unknown user/group bitwarden:bitwarden
chown: unknown user/group bitwarden:bitwarden
chown: unknown user/group bitwarden:bitwarden
chown: unknown user/group bitwarden:bitwarden
error: failed switching to "bitwarden:bitwarden": unable to find user bitwarden: no matching entries in passwd file

**Comment by CirnoT** [comment]
Confirmed. For some reason fix did not get backported to v2025.8.2.
