### ISSUE TITLE
Issue running desktop app after upgrade to `2025.11.0`

### ISSUE THREAD

**Issue by yermulnik** [bitwarden/clients#17375]
### Steps To Reproduce

1. Download `Bitwarden-2025.11.0-amd64.deb` from https://github.com/bitwarden/clients/releases/tag/desktop-v2025.11.0
2. Install using APT package manager
3. Try to start the app

### Expected Result

Desktop app starts without issues.

### Actual Result

App doesn't start.
Running it directly from CLI, reveals the cause:
```shell
> bitwarden
[3111444:1114/000039.147684:FATAL:sandbox/linux/suid/client/setuid_sandbox_host.cc:169] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Bitwarden/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
[3111447:0100/000000.174665:ERROR:content/zygote/zygote_linux.cc:660] write: Broken pipe (32)
```

### Additional Context

The suggested solution (`sudo chmod 4755 /opt/Bitwarden/chrome-sandbox`) fixes the issue.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.5 LTS

### Installation method

Other

### Build Version

2025.11.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cylayabw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by folknor** [comment]
There's lots and lots of information about this issue here: https://github.com/electron/electron/issues/42510

**Comment by yermulnik** [comment]
What's the TL;DR for the deb packages from that long thread? Would it be possibly feasible to add `chmod 4755 /path/to/file` as a `postinst` step to get this resolved automatically or at least to spit out a message from the same `postinst` step to let users know what they have to do if the file has incorrect permissions? 🤔

**Comment by mochy83** [comment]
sudo chmod 4755 /opt/Bitwarden/chrome-sandbox

It works!

**Comment by benhaube** [comment]
I can confirm that the Bitwarden-2025.11.0-x86_64.rpm package also has this issue. I was also able to fix the issue with the command: `sudo chmod 4755 /opt/Bitwarden/chrome-sandbox`. 

I came to report the bug and instead found it already reported.

**Comment by krallus** [comment]
I run BitWarden via AppImage, so my workaround was running with the "--no-sandbox" option:
```
./Bitwarden.AppImage --no-sandbox
```

**Comment by ricjuhnl** [comment]
Still have this issue with the 2025.11.2.deb package:

```sh
[9224:1120/083749.839643:FATAL:sandbox/linux/suid/client/setuid_sandbox_host.cc:169] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Bitwarden/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
```

**Comment by borque** [comment]
I also still have this problem with 2025.11.1!
Is the chmod-workaround the official solution, or will there be a better one in the near future with a new release?

For reference: #17408

Edit: corrected typo in version (was 2025.1.2 should be 2025.1.1)

**Comment by pamperer562580892423** [comment]
@borque and @ricjuhnl Did you get those 2025.11.2 versions from a specific Pull Request?

I only ask, because there is **no** official desktop app 2025.11.2 release yet.

PS: Ah, okay - I think I found it myself. You are certainly referring to this post: https://github.com/bitwarden/clients/issues/17443#issuecomment-3555393675

**Comment by borque** [comment]
@pamperer562580892423 
For my post this was a typo, I tried it with the official 2021.11.1 appimage.
I corrected my post above.

**Comment by nubesurrealista** [comment]
I'm still having this issue in 2025.11.2, on debian 12 with the .deb release

**Comment by trmartin4** [comment]
Thank you for your patience as we investigated this issue.  This will be fixed with #17509, which will be in the next desktop release.  We'll be closing this ticket since PR has merged.  If you would like to try the fix in advance of the release, the artifacts can be found on the [latest build](https://github.com/bitwarden/clients/actions/runs/19714131584).

**Comment by ivan-hc** [comment]
Hi @trmartin4 I'm happy to see that the latest artifact here works https://github.com/bitwarden/clients/actions/runs/19714131584

However, in the meantime, the latest build in releases/latest is still broken, and some tools, like my package manager, "[AM](https://github.com/ivan-hc/AM)", keeps distributing the broken release.

Basically, we remove the `--no-sandbox` flag from the desktop file, since running Electron apps without a sandbox is unsafe.

Bitwarden AppImage worked until the previous release, and luckily I have found this issue that explain what happens.

My question is, since the fixed artifacts are ready, **why don't you upload them in releases/latest or as pre-release?**

I suggested to the user that have had this issue to downgrade BitWarden to the previous release https://github.com/ivan-hc/AM/issues/1938 , but this is a workaround, not a solution.

A quick fix in releases would be appreciated. I would be able to keep my users updated with the last build in a more secure way.

Thanks in advance.

**Comment by emphases2398** [comment]
I'm on Fedora 43 (Gnome 49) using the RPM. This issue still persists in Bitwarden-2025.11.2-x86_64.rpm.  Running `sudo chmod 4755 /opt/Bitwarden/chrome-sandbox` partially fixes the issue, but the app doesn't render decorations properly on Gnome. The title bar doesn't follow theming preferences and doesn't show the window control button(s).

**Comment by benhaube** [comment]
> I'm on Fedora 43 (Gnome 49) using the RPM. This issue still persists in Bitwarden-2025.11.2-x86_64.rpm. Running `sudo chmod 4755 /opt/Bitwarden/chrome-sandbox` partially fixes the issue, but the app doesn't render decorations properly on Gnome. The title bar doesn't follow theming preferences and doesn't show the window control button(s).

Really? That is interesting. Maybe it is a GNOME-specific issue that is unrelated. I am on Fedora 43 KDE Plasma Desktop Edition, and I do not have the UI rendering issue you mentioned. The window decorations and title bar render and follow my system theme. The scroll bar does not, but that has always been the case.
 
<img width="1080" height="759" alt="Image" src="https://github.com/user-attachments/assets/a5caf6db-6ba7-4450-8e77-7c278fdb5dba" />

Being that GTK handles window decorations on the client side and Qt handles them on the server side, I would be willing to bet that it is an issue only affecting desktops that use GTK.

**Comment by JohnCWood** [comment]
I am running Bitwarden-2025.11.2-x86_64.AppImage on Ubuntu 22.04.5 and Gnome 42.9. I am running into the same issue. Running the appimage with --no-sandbox fixes the issue.

**Comment by Caraffa-git** [comment]
Same issue with KDE Neon (Ubuntu 24.04 + KDE Plasma 6.5.3) and the `Bitwarden-2025.11.2-amd64.deb`  package - `sudo chmod 4755 /opt/Bitwarden/chrome-sandbox` still works

**Comment by yermulnik** [comment]
After the laptop restart, the issue has returned and needed to apply `chmod` again to make it start. `v2025.11.2`.

> Thank you for reporting this issue! We've added this to our internal tracking system. ID: PM-28220 Link (for internal use): [bitwarden.atlassian.net/browse/PM-28220](https://bitwarden.atlassian.net/browse/PM-28220)

~@trmartin4 Can the Bitwarden team please provide an update on this? Thank you.~

Oh, I somehow missed the post at https://github.com/bitwarden/clients/issues/17375#issuecomment-3582817445 🤦🏻 Apologies for the unnecessary noise 🙏🏻

**Comment by krallus** [comment]
Just a quick note that I confirmed this issue is fixed in release:
```
Version 2025.12.0
SDK 'main (0107af7)'
Shell 37.7.0
Renderer 138.0.7204.251
Node 22.20.0
Architecture x64
```
