### ISSUE TITLE
25.11.0 - Safari Extension Broken on MacOS

### ISSUE THREAD

**Issue by sfsfs3fs** [bitwarden/clients#17399]
### Steps To Reproduce

After updating to, or clean installing the latest Bitwarden update 25.11.0 on MacOS 26.6 Developer Beta 2, the Safari Extension is broken. The main Bitwarden separate app works, however.

### Expected Result

Safari extension to load normally.

### Actual Result

Safari extension will not load, appears to hang and displays a white background with a spinning loading wheel.

### Screenshots or Videos

https://private-user-images.githubusercontent.com/123140191/514582665-4eadbf0b-22e8-4809-aa98-3047b3db3566.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMxNTA3MTQsIm5iZiI6MTc2MzE1MDQxNCwicGF0aCI6Ii8xMjMxNDAxOTEvNTE0NTgyNjY1LTRlYWRiZjBiLTIyZTgtNDgwOS1hYTk4LTMwNDdiM2RiMzU2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExNFQyMDAwMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjgyNjBhYmMwZjE3NzA3NTZmYzkzZTA4MzY4N2JkMzA2ODVkYTc3NjY3NTgwZTczMjY3YWFmODJjMTZmZWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wI8XrqnA51F4s1ffWUqgWGyoJu9hv0kjbNTuWVI5lnQ

### Additional Context

The prior Bitwarden update (25.10.0) was working fine on MacOS 26.2 Developer Beta 2, so I don't believe it is necessarily strictly related to the Developer Beta.

### Operating System

macOS

### Operating System Version

Developer Beta Version 26.2 Beta (25C5037j)

### Web Browser

Safari

### Browser Version

26.2 (21623.1.13.11.3)

### Environment Versions

Version 2025.11.0 (50947)

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by pamperer562580892423** [comment]
@sfsfs3fs Thanks for putting this in the correct category...

You wrote something of "clean installation", so I guess you already made sure that after deinstallation the [local storage](https://bitwarden.com/help/data-storage/#on-your-local-machine) of the extension was deleted before you reinstalled it? (if you do it now: make sure you can login afterwards, i.e. that you have your master password and 2FA at hand)

Did you also try to disable and re-enable the extension?
And did you "Allow access to file URLs" (--> Manage extension)?

There were reports those things worked in some cases: https://community.bitwarden.com/t/browser-extension-stuck-while-loading/85550/

(PS: I'm just another user, not a Bitwarden employee.)

Another PS: The screenshot here is not a visible image but just an invalid link.

**Comment by sfsfs3fs** [comment]
@pamperer562580892423 yes, by clean install I'm referring to the removal of all Bitwarden local storage prior to reinstallation from the Mac App Store. 

Yes, I did try to disable and re-enable the browser extension.

> And did you "Allow access to file URLs" (--> Manage extension)?

I don't believe this option is available macOS/Safari version of the extension.

Thank you for the heads up to both, fixed the screenshot!

**Comment by jtodddd** [comment]
Hi there,

This has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by jacobsanders** [comment]
Same issue here. Started happening in Safari after updating to 25.11.0 from the Mac App Store. macOS 26.1 on a Mac mini.

Chrome extension still works as it did before, but the Safari extension just keeps spinning.

**Comment by yocuri** [comment]
Happened to be first-time installer today and noticed this with Safari extension (MacOS 26.1)

Thank you for reporting.

**Comment by 1c383r9** [comment]
omg safari extenson got broken again!! here's monterey!!!

**Comment by c0rychu** [comment]
Same issue on macOS 26.1.
Break after updating Bitwarden via the App Store.

**Comment by luciancj** [comment]
[Warning] `WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error: (main.js, line 494)
 – TypeError: Unexpected response MIME type. Expected 'application/wasm'
TypeError: Unexpected response MIME type. Expected 'application/wasm'

Using MacOS Sequoia 15.7.2, self-hosted with Vaultwarden

**Comment by pamperer562580892423** [comment]
@luciancj:

> [Warning] WebAssembly.instantiateStreaming failed because your server does not serve wasm [...] Using MacOS Sequoia 15.7.2, self-hosted with Vaultwarden

When your server is Vaultwarden, you should report it there. (and check if there is a server update available for you there)

**Comment by pdcastro** [comment]
> _When your server is Vaultwarden, you should report it there._

For what it is worth, the same warning/error message is displayed when not using Vaultwarden. Here’s what I get when right-clicking the grey area of the extension popup window and selecting “Inspect Element”:

![Image](https://github.com/user-attachments/assets/9f45ad05-daa8-4421-9369-6e45ada32ab2)

**Comment by Michael1260** [comment]
I confirm : Tahoe 26.11, Safari 26.1 Server self hosted (with Vaultwarden in Yunohost). FF extension is OK

**Comment by pamperer562580892423** [comment]
> I confirm :

What exactly?

> Tahoe 26.11,

I thinkt the latest Tahoe version is 26.1 ?!

> Safari 26.1 Server self hosted (with Vaultwarden in Yunohost).

Which Vaultwarden server version?

> FF extension is OK

The official Firefox extension is still on 2025.1**0**.0... Are you referring to that one? - And this issue here is about Safari extension 2025.1**1**.0.

**Comment by ericfjosne** [comment]
Confirmed as well on my end on macOS 26.1, Bitwarden 25.11.0 installed from App Store, on Apple Silicon machine.
Chrome extension is still working, but doesn't seem to be updated yet (still on version 2025.10.0).

Also worth noting that starting the macOS Bitwarden app results in a blank screen.

<img width="729" height="550" alt="Image" src="https://github.com/user-attachments/assets/959708fd-895d-4fde-aa37-4ec766330c0a" />

**Comment by Michael1260** [comment]
> > I confirm :
> 
> What exactly?

Blank screen with the safari's extension

> 
> > Tahoe 26.11,

Yes, double key ... 26.1 :-)

> 
> I thinkt the latest Tahoe version is 26.1 ?!
> 
> > Safari 26.1 Server self hosted (with Vaultwarden in Yunohost).
> 
> Which Vaultwarden server version?

2025.7.0

> 
> > FF extension is OK
> 
> The official Firefox extension is still on 2025.1**0**.0... Are you referring to that one? - And this issue here is about Safari extension 2025.1**1**.0.

Yes, it's just trying to help to see where is the bug ... FF extension is working.

**Comment by pamperer562580892423** [comment]
> > Which Vaultwarden server version?
> 
> 2025.7.0

Ah, interesting. Version 1.34.3 then? Good to know, as that is the latest Vaultwarden version at the moment. 👍

> Yes, it's just trying to help to see where is the bug ... FF extension is working.

Aha, okay!

**Comment by ericfjosne** [comment]
> Confirmed as well on my end on macOS 26.1, Bitwarden 25.11.0 installed from App Store, on Apple Silicon machine. Chrome extension is still working, but doesn't seem to be updated yet (still on version 2025.10.0).
> 
> Also worth noting that starting the macOS Bitwarden app results in a blank screen.
> 
> <img alt="Image" width="729" height="550" src="https://private-user-images.githubusercontent.com/4800868/514777669-959708fd-895d-4fde-aa37-4ec766330c0a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMyNDE1NTEsIm5iZiI6MTc2MzI0MTI1MSwicGF0aCI6Ii80ODAwODY4LzUxNDc3NzY2OS05NTk3MDhmZC04OTVkLTRmZGUtYWEzNy00ZWM3NjYzMzBjMGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTExMTVUMjExNDExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjA2ZTU1YjRhZTFlZTEzY2U0YWY3ZGE0ZWU4Y2Q4OTQ0OGVjNjZkOTAzYzFmMzgzNjJjMDRkOWFmYjE2MDY3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mJTKdfnd0DR2dvxV0SXLnm8VhmAB6itkzSNl-IIC7cE">

Just wanted to flag that opening up the Bitwarden app now works as expected. The issue with the Safari extension unfortunately remains.

**Comment by pamperer562580892423** [comment]
Did any of you change your [KDF](https://bitwarden.com/help/kdf-algorithms/) from PBKDF2 to Argon2?

**Comment by DanCornett** [comment]
I also have found that the **Safari extension** is failing to open (circle just spins) on 26.1 with the BitWarden update to Version 2025.11.0 (50947) ... while the Mac app still works (and the Firefox extension works).

**Comment by DanCornett** [comment]
> Did any of you change your [KDF](https://bitwarden.com/help/kdf-algorithms/) from PBKDF2 to Argon2?

No.

**Comment by cwallwey** [comment]
> Did any of you change your [KDF](https://bitwarden.com/help/kdf-algorithms/) from PBKDF2 to Argon2?

Not for my personal master key, but for the admin token.

**Comment by gbaranski** [comment]
> Did any of you change your [KDF](https://bitwarden.com/help/kdf-algorithms/) from PBKDF2 to Argon2?

I experience the same issue, and I have a very fresh install of MacOS 15.6.
I've tried looking into the logs, but there's not really anything relevant.

<img width="1068" height="718" alt="Image" src="https://github.com/user-attachments/assets/042280cc-4fc8-4695-bf34-bc8c67cdd9e8" />

**Comment by Dylno85** [comment]
Hello, I'm using Mac OS X Monterey with Safari 17.6 and I have the same problem. Here's the console message:

"Extension request contains input items but the extension point does not specify a set of allowed payload classes. The extension point's NSExtensionContext subclass must implement `+_allowedItemPayloadClasses`. This must return the set of allowed NSExtensionItem payload classes. In future, this request will fail with an error."

**Comment by aDefrawy** [comment]
Same here, the extension not loading for me after updating Bitwarden yesterday :(
Desktop app is okay!

Bitwarden version 2025.11.0 (50947)
Safari Version 26.1 (21622.2.11.11.9)
macOS 26.1

**Comment by trmartin4** [comment]
Thank you all for the reports.  We have identified what we believe is the root cause for this and are working on a solution.

**Comment by dpfaber** [comment]
I am experiencing the same issue: Bitwarden Safari extension fails to load and displays "spinning wheel" icon without resolving. Mac  Tahoe 26.1 Bitwarden Extension version 2025.11.0.  This OS is running on a Macbook Air M2. My vault KDF was set to Argon 2 quite a long time ago with no problems.

**Comment by dp466** [comment]
got the same issue with a fresh install of macOS
the desktop app work fine but not the extension as other reported

**Comment by packshott** [comment]
epic fail

**Comment by cwallwey** [comment]
Is there a way to revert to an earlier version (2025.10.0?) until this issue is resolved?

FYI: Commenting here triggers the `issue_comment` workflow, and it errors with “User does not have the necessary access.” Not sure if intended.

**Comment by jay-dizzale** [comment]
Same issue here. Fresh Install of Bitwarden Version 2025.11.0 (50947)

Window remains blank, cannot be moved, developer tools cannot be opened, no reaction after 10 Minutes.

<img width="963" height="801" alt="Image" src="https://github.com/user-attachments/assets/29baa706-d870-4ec5-b844-38c8cfb2492c" />

**Comment by aDefrawy** [comment]
@cwallwey I managed to downgrade by downloading and installing October's release `Bitwarden-2025.10.0-universal-mac.zip` for MacOS from the [releases page](https://github.com/bitwarden/clients/releases/tag/desktop-v2025.10.0). Works fine again until the fix is released!

**Comment by glomme** [comment]
> [@cwallwey](https://github.com/cwallwey) I managed to downgrade by downloading and installing October's release `Bitwarden-2025.10.0-universal-mac.zip` for MacOS from the [releases page](https://github.com/bitwarden/clients/releases/tag/desktop-v2025.10.0). Works fine again until the fix is released!


For me here too. After downgrade extension was working fine again.
So also waiting for the fix.

**Comment by 1c383r9** [comment]
> [@cwallwey](https://github.com/cwallwey) I managed to downgrade by downloading and installing October's release `Bitwarden-2025.10.0-universal-mac.zip` for MacOS from the [releases page](https://github.com/bitwarden/clients/releases/tag/desktop-v2025.10.0). Works fine again until the fix is released!



> > [@cwallwey](https://github.com/cwallwey) I managed to downgrade by downloading and installing October's release `Bitwarden-2025.10.0-universal-mac.zip` for MacOS from the [releases page](https://github.com/bitwarden/clients/releases/tag/desktop-v2025.10.0). Works fine again until the fix is released!
> 
> For me here too. After downgrade extension was working fine again. So also waiting for the fix.

Thx for the workaround.

I tried it but there's no bitwarden extension options at all in safari. I'm on safari 17.6. 

Dunno if i'm wrong at something

---

Got it working! Check the option of "allow unsigned extensions"(Dunno if this is the correct English translation) from the developer settings tab.

<img width="1884" height="964" alt="Image" src="https://github.com/user-attachments/assets/7385f10d-ca0e-4002-86b3-9524d7815fe6" />

**Comment by renglm** [comment]
Same situation here, but
macOS 15.7.2 with Safari 26.1 (20622.2.11.119.1)

**Comment by renglm** [comment]
And my message triggered a page alert from github:


_[Respond / Check PR run / Check](https://github.com/bitwarden/clients/issues/17399#logs)
failed 3 minutes ago in 4s

1s
Current runner version: '2.329.0'
Runner Image Provisioner
Operating System
Runner Image
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions-cool/check-user-permission@7b90a27f92f3961b368376107661682c441f6103' (SHA:7b90a27f92f3961b368376107661682c441f6103)
Uses: bitwarden/gh-actions/.github/workflows/check-run.yml@refs/heads/main (a059fa3f763d974b4e699332017a4c0a4949cf29)
Complete job name: Respond / Check PR run / Check
0s
Run actions-cool/check-user-permission@7b90a27f92f3961b368376107661682c441f6103
[Action Query] The user: renglm permission is read.
[Action Require] The renglm permission check is false.
<<< ───────────────────────────────────────────────────────────────────────────────────────────── >>>
│  ████████╗██╗  ██╗ █████╗ ███╗   ██╗██╗  ██╗███████╗    ██╗   ██╗███████╗██╗███╗   ██╗ ██████╗    │
│  ╚══██╔══╝██║  ██║██╔══██╗████╗  ██║██║ ██╔╝██╔════╝    ██║   ██║██╔════╝██║████╗  ██║██╔════╝    │
│     ██║   ███████║███████║██╔██╗ ██║█████╔╝ ███████╗    ██║   ██║███████╗██║██╔██╗ ██║██║  ███╗   │
│     ██║   ██╔══██║██╔══██║██║╚██╗██║██╔═██╗ ╚════██║    ██║   ██║╚════██║██║██║╚██╗██║██║   ██║   │
│     ██║   ██║  ██║██║  ██║██║ ╚████║██║  ██╗███████║    ╚██████╔╝███████║██║██║ ╚████║╚██████╔╝   │
│     ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝     ╚═════╝ ╚══════╝╚═╝╚═╝  ╚═══╝ ╚═════╝    │
│                                                                                                   │
│    █████╗  ██████╗████████╗██╗ ██████╗ ███╗   ██╗███████╗       ██████╗ ██████╗  ██████╗ ██╗      │
│   ██╔══██╗██╔════╝╚══██╔══╝██║██╔═══██╗████╗  ██║██╔════╝      ██╔════╝██╔═══██╗██╔═══██╗██║      │
│   ███████║██║        ██║   ██║██║   ██║██╔██╗ ██║███████╗█████╗██║     ██║   ██║██║   ██║██║      │
│   ██╔══██║██║        ██║   ██║██║   ██║██║╚██╗██║╚════██║╚════╝██║     ██║   ██║██║   ██║██║      │
│   ██║  ██║╚██████╗   ██║   ██║╚██████╔╝██║ ╚████║███████║      ╚██████╗╚██████╔╝╚██████╔╝███████╗ │
│   ╚═╝  ╚═╝ ╚═════╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝       ╚═════╝ ╚═════╝  ╚═════╝ ╚══════╝ │
<<< ────────────────────────────────────────────────────────────────────────────────── by xrkffgg >>>
0s
Run echo "User ${GITHUB_TRIGGERING_ACTOR} does not have the necessary access for this repository."
User renglm does not have the necessary access for this repository.
Current permission level is read.
Job originally triggered by renglm.
Error: Process completed with exit code 1.
0s
Cleaning up orphan processes_

**Comment by joshua-richards** [comment]
Same fault here with Safari 26.1 (21622.2.11.11.9)

**Comment by michettik** [comment]
Perhaps I've missed something but I'm having a tough time understanding how this issue wasn't identified and resolved during testing long before Apple went GA with this release.  And the fact that you're trying to close my ticket is really disappointing.

**Comment by cwallwey** [comment]
> [@cwallwey](https://github.com/cwallwey) I managed to downgrade by downloading and installing October's release `Bitwarden-2025.10.0-universal-mac.zip` for MacOS from the [releases page](https://github.com/bitwarden/clients/releases/tag/desktop-v2025.10.0). Works fine again until the fix is released!

This morning, the app notified me that an update to 2025.11.0 was available and that I should restart the app to install it. Can someone please explain to me how I can prevent the app from updating automatically? Thx.

**Comment by vidalpascual** [comment]
Fresh Install of Bitwarden Version 2025.11.0, and same problem here... :(

**Comment by technicalflaw** [comment]
As a new subscriber, I’m asked myself this multiple times already. First impressions count. 

> Perhaps I've missed something but I'm having a tough time understanding how this issue wasn't identified and resolved during testing long before Apple went GA with this release. And the fact that you're trying to close my ticket is really disappointing.

**Comment by plotlessplot** [comment]
Same issue here, with macOS 26.1, Safari 26.1 (21622.2.11.11.9) and Bitwarden 2025.11.0 (50947).

**Comment by DanCornett** [comment]
> > [@cwallwey](https://github.com/cwallwey) I managed to downgrade by downloading and installing October's release `Bitwarden-2025.10.0-universal-mac.zip` for MacOS from the [releases page](https://github.com/bitwarden/clients/releases/tag/desktop-v2025.10.0). Works fine again until the fix is released!
> 
> This morning, the app notified me that an update to 2025.11.0 was available and that I should restart the app to install it. Can someone please explain to me how I can prevent the app from updating automatically? Thx.

Two things to do:
1.  If you have BitWarden in/from the App Store, turn off autoupdate in the App Store preferences.
2. Delete the BitWarden files, empty the Trash, and restart before installing the ...10.0 version

Then ignore any prompts from the app itself to update (at least until the fixed update is completed).

**Comment by cwallwey** [comment]
> Then ignore any prompts from the app itself to update (at least until the fixed update is completed).

@DanCornett Thank you for your detailed explanation. I downgraded to version 2025.10.0 released on GitHub. Unfortunately, the app seems to download available updates automatically and install them with the next app launch.

That's why the downgrade only lasts until the app is restarted - for whatever reason - and there is apparently nothing I can do about it.

**Comment by DanCornett** [comment]
> [@DanCornett](https://github.com/DanCornett) Thank you for your detailed explanation. I downgraded to version 2025.10.0 released on GitHub. Unfortunately, the app seems to download available updates automatically and install them with the next app launch.
> 
> That's why the downgrade only lasts until the app is restarted - for whatever reason - and there is apparently nothing I can do about it.

I wasn't detailed enough: you need to delete ALL the BitWarden files before downloading & installing the new version.  The Safari extension is not kept in the Applications folder, so just deleting that application is not enough.  I used "Find Any File" to search the disk for all the "BitWarden" files and delete them all first.  _("EasyFind" is another alternative to find files wherever they may be scattered.)_

**Comment by cwallwey** [comment]
@DanCornett Thanks. I guess I wasn't detailed enough either. 😉 I did the same (`sudo find / -iname "*bitwarden*" -delete`), then restarted the Mac and installed version 2025.10.0 from GitHub. Nevertheless, the app downloads the update to the current version in the background and installs it automatically with the restart of the app.

**Comment by DanCornett** [comment]
Did you make sure the extension was out of Safari too?  I checked that before doing the Mac restart.

**Comment by cwallwey** [comment]
Yes. I turned it off in Safari, also turned off 'Share Across Devices', and ended Safari. Then I did all the uninstall steps and restarted the Mac.

**Comment by ErikAbele** [comment]
> Perhaps I've missed something but I'm having a tough time understanding how this issue wasn't identified and resolved during testing long before Apple went GA with this release. And the fact that you're trying to close my ticket is really disappointing.

This here is the basic reason:

"That PR affects 23 files, more than 260 lines of code changed, and **the review was approved 6 minutes after being marked Ready for Review**. **_This does not indicate a serious level of oversight._** It has now caused a bug that is making the app unusable in browsers for a large proportion of your userbase."

https://github.com/bitwarden/android/issues/6107#issuecomment-3536871023

There is simply ZERO oversight... it began about a year ago and it's at a state now where I seriously recommend switching to something else if your security is worth anything to you.

**Comment by pamperer562580892423** [comment]
It seems the fix for this issue was just released: https://github.com/bitwarden/clients/releases/tag/desktop-v2025.11.1

**Comment by thelfensdrfer** [comment]
> It seems the fix for this issue was just released: https://github.com/bitwarden/clients/releases/tag/desktop-v2025.11.1

Doesn't work for me and honestly, I don't want to try to delete random files to see if it works then. I will wait for a permanent fix.

<img width="1352" height="949" alt="Image" src="https://github.com/user-attachments/assets/4c739ce5-cd45-4c9f-a037-13a5e780d4f4" />

**Comment by dpfaber** [comment]
Installation failed. This is NOT a fix. It's been four days already. Time to consider other options.

**Comment by michettik** [comment]
This is such a massive productivity drain, I cannot continue like this.  

Looking at 1Password and Proton Pass.  Suggestions anyone?

**Comment by Darit-GitHub** [comment]
Confirming that version 2025.11.1 (universal macOS build) fixed the issue on my MacBook Air M4.  
The app launches normally now and the loading loop is gone.  
Thanks for the quick update!

**Comment by CzarHey** [comment]
Can confirm that 2025.11.1 works on both Apple silicon and Intel running macOS Tahoe. I did encounter an issue where the desktop app continued to show a blank screen despite having installed the update, which breaks the ability to unlock with biometrics in non-Safari browsers. The solution was to do a complete reinstall of Bitwarden:

1. Go to the `Applications` folder, then move `Bitwarden.app` into the trash.
2. Delete Bitwarden's preferences files.
  * If using the Mac App Store version, go to `~/Library/Containers`, then move any folders named "Bitwarden" into the trash.
  * If using the standalone version, go to `~/Library/Application Support`, then move the "Bitwarden" folder into the trash.
3. Empty the trash.
4. Reinstall the app, either standalone or through the App Store.

Once done, I was prompted to log in, complete 2FA, and was back in.

**Comment by Kosette** [comment]
FYI, after updating desktop client to v2025.11.1 from AppStore, the Safari extension works normally without loading loop, even the extension itself is v2025.11.0.

**Comment by c0rychu** [comment]
> Thank you all for the reports. We have identified what we believe is the root cause for this and are working on a solution.

@trmartin4, May I ask what the root cause is? Thanks for fixing the bug, btw.

**Comment by chnyangjie** [comment]
Thanks to Bitwarden on my phone, I found the password to comment on this issue — otherwise, I wouldn’t have been able to log into GitHub LOL 😂

**Comment by ericfjosne** [comment]
Updated to the 2025.11.1 version from the App Store, mac silicon, os version 26.1.

Problem is fixed 🎉

Thanks for the fix.

**Comment by Dylno85** [comment]
Hello,
I just updated to version 2025.11.1 from the Apple Store, but the problem persists. The extension still doesn't work. I completely uninstalled and reinstalled it, but it didn't help.
Are other people experiencing this issue?
I'm using macOS Monterey sur un iMac fin 2015, modèle 17,1

**Comment by santhoshsram** [comment]
On `Safari Version 26.0.1 (21622.1.22.11.15)` and `Bitwarden Version 2025.11.0 (50947)` - I till see the spinning wheel issue. Tried
- uninstall / reintsall
- clear local storage of extension

Still stuck

**Comment by santhoshsram** [comment]
> On `Safari Version 26.0.1 (21622.1.22.11.15)` and `Bitwarden Version 2025.11.0 (50947)` - I till see the spinning wheel issue. Tried
> 
> * uninstall / reintsall
> * clear local storage of extension
> 
> Still stuck

Updated to 2025.11.1 from mac app store and I don't see the issue anymore.

**Comment by 1c383r9** [comment]
> Hello, I just updated to version 2025.11.1 from the Apple Store, but the problem persists. The extension still doesn't work. I completely uninstalled and reinstalled it, but it didn't help. Are other people experiencing this issue? I'm using macOS Monterey sur un iMac fin 2015, modèle 17,1

+1 Monterey.

2025.11.1 still doesnt work in Safari

**Comment by mmmarsbarrr** [comment]
Just adding that I'm experiencing the same issue. MacOS 15.7.1 (24G231) / Safari Version 26.0.1 (20622.1.22.118.4) / MacBook Pro M3 Max. Tried deleting extension cache. Would be great to have the option to uninstall the safari extension separately without having to uninstall the entire Bitwarden application.

**Comment by pamperer562580892423** [comment]
@mmmarsbarrr 

> Would be great to have the option to uninstall the safari extension separately without having to uninstall the entire Bitwarden application.

Maybe. But that wouldn't work in this case here, as indeed **only the Bitwarden application (desktop app) got the update (to 2025.11.1)** so that the extension (which officially still seems to be on 2025.11.0 afterwards) can work again.

**Comment by sfsfs3fs** [comment]
The latest MacOS Bitwarden release 2025.11.1 resolves this issue.

**Comment by DanCornett** [comment]
I downloaded 2025.11.1 from Apple's Store and it now works for me; I only deleted the previously installed 2025.10.0

**Comment by mmmarsbarrr** [comment]
The updated version now works for me on MacOS 15.7.1 (24G231) / Safari Version 26.0.1 (20622.1.22.118.4) / MacBook Pro M3 Max. I didn't have to uninstall the app either, just closed Safari and updated via the AppStore.

**Comment by NiccoloGranieri** [comment]
Unfortunately it doesn't work for me, the spinning wheel look and feel changed a bit, but I still get the same result (see screenshot attached). Below, my system info:

- macOS  26.1
- Safari Version 26.1 (21622.2.11.11.9)
- Bitwarden Version 2025.11.1 (51183) - App Store

Even uninstalled (using Hazel, thus purging files) and reinstalled to see if it would fix it, it doesn't.

<img width="492" height="742" alt="Image" src="https://github.com/user-attachments/assets/0e12cda1-4294-4ee3-aecd-70da39db40f7" />

**Comment by Homer-Rivera** [comment]
I updated to 2025.11.1 from the App Store as well, and I still have an issue.  I noticed the browser extension shows version 2025.11.0, while the app shows version 2025.11.1.  Is there some kind of cache issue with the extension?  I also deleted the app, rebooted, and reinstalled.

<img width="985" height="709" alt="Image" src="https://github.com/user-attachments/assets/e0f1e38f-b686-4f82-823c-4d5bdb9bee14" />

**Comment by pamperer562580892423** [comment]
@Homer-Rivera:

> I also deleted the app, rebooted, and reinstalled

Did you make sure, that the [local storage](https://bitwarden.com/help/data-storage/#on-your-local-machine) of the desktop app and extension was deleted before reinstalling?

**Comment by Homer-Rivera** [comment]
> [@Homer-Rivera](https://github.com/Homer-Rivera):
> 
> > I also deleted the app, rebooted, and reinstalled
> 
> Did you make sure, that the [local storage](https://bitwarden.com/help/data-storage/#on-your-local-machine) of the desktop app and extension was deleted before reinstalling?

Yes, I did remove the folders listed on the page.

I also opened a new ticket.  

https://github.com/bitwarden/clients/issues/17616

**Comment by nlinux** [comment]
same issue here, on a fresh install

**Comment by pamperer562580892423** [comment]
@nlinux:

> same issue here, on a fresh install

Which version of the desktop app? -- 2025.11.2 was released a few hours ago.

**Comment by heykea** [comment]
Same, Desktop App says "Version 2025.11.2 (51375)" and Safari lists the extension as 2025.11.0. Chrome says 2025.11.1

**Comment by NiccoloGranieri** [comment]
Agree with @ekovarski, same situation. Desktop App says "Version 2025.11.2 (51375)" and Safari lists the extension as 2025.11.0

**Comment by jcubed59** [comment]
I was experiencing the spinning wheel when attempting to using the Bitwarden Safari extension. The following are a summary of my troubleshooting efforts:

* I cleared the local storage with no effect.
* I disabled and reenabled the Bitwarden Safari extension with no effect.
* I disabled the Bitwarden Safari extension, cleared the local storage, uninstalled Bitwarden, downloaded Bitwarden from the Apple Store, and installed Bitwarden with no effect. The same spinning wheel.
* I followed the same procedure described in the preceding bullet, except, I downloaded Bitwarden from the Bitwarden website. After installing Bitwarden the Bitwarden Safari extension is an available extension, but after selecting (checking box) the extension I am directed to a Bitwarden webpage explaining how to enable the extension. Moreover, the extension is not seen in the Safari browser. The extension is not available and I have to use the Bitwarden app.

My Current Configuration:
MacBook Air M2 running macOS Tahoe 26.1 using Safari Browser Version 26.1 (21622.2.11.11.9) and Bitwarden Version 2025.11.2 (51375).

**Comment by digger240** [comment]
Having the same issue.
Mac Sonoma 14.5
Safari Version 17.5 
Bitwarden 2025.11.2

works fine on Firefox

**Comment by zach-bray** [comment]
Having same issue after updating Bitwarden using AppStore. Tried all the same uninstalling and clearing all lcoal storage to no avail.

**Comment by ADiogoA** [comment]
Same issue here.
bitwarden version 2025.11.2
macOS Monterey
Safari version 17.6

**Comment by glomme** [comment]
Blank Safari app
bitwarden version 2025.11.2
safari app version : 2025.11.0
macOS Tahoe (26.1)
Safari version 26.1

![Image](https://github.com/user-attachments/assets/a109d8d7-b73c-4334-86d6-e6175389a2a6)

UPDATE: Was solved with new download of Bitwarden universal app from the Bitwarden homepage.

**Comment by digger240** [comment]
my issue continues...
downloaded new version of the Bitwarden universal app and also the extension. still see the spinning and a lock 
on the bitwaren icon on Safari.
It all works great on Firefox.

**Comment by pamperer562580892423** [comment]
There seems to be a relevant post from a BW developer (@jlf0dev) with some instructions in a similar issue: https://github.com/bitwarden/clients/issues/17616#issuecomment-3608081991
