### ISSUE TITLE
Unable to save attachments / Fresh self-hosted Families Organization Installation

### ISSUE THREAD

**Issue by PetrosStavrakakis** [bitwarden/clients#17402]
### Steps To Reproduce

1. Add Login
2. Add File Attachment

### Expected Result

Add a File to a login succesfully.

### Actual Result

Error in bitwarden-api Container

### Additional Context

Hi to all,
I using the two-weeks Trial for the Families Organization.
I am selfhosting Bitwarden at Home in a PVE LXC Container with Ubuntu 25.04. 
Installation works smoothless with the Linux Standard Deployment Documentation.

Versions of Software used:
Docker 29.0.1, build eedd969.
containerd containerd.io v2.1.5 fcd43222d6b07379a4be9786bda52438f0dd16a1
Web UI Version 2025.11.1+28469e0
Desktop Client is:
-----
Version 2025.11.0
SDK 'main (8ef7951)'
Shell 37.7.0
Renderer 138.0.7204.251
Node 22.20.0
Architecture x64
------

The Caddy-Implementation on OpnSense on my "DialUp" is used as a reverse_proxy for Bitwarden.
The LicenseFile was succesfully imported via Admin Console
So far so good. 
Importing Login Data works. Adding an Organization works too.
Adding a File Attachment to a login throws following error

---------------
fail: Bit.Api.Utilities.ExceptionHandlerFilterAttribute[0]
      => SpanId:20057fd40d414adc, TraceId:e58a01ad1e1fe6ac98ac651d4516520f, ParentId:0000000000000000 => ConnectionId:0HNH42RFM5D6Q => RequestPath:/ciphers/7b12671c-2a3c-4bf8-af7c-b3960071a477/attachment/suut07frt7ejttgsr0tuvngxz099dvl2 RequestId:0HNH42RFM5D6Q:00000001 => IpAddress:::ffff:172.19.0.9 UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.7204.251 Safari/537.36 DeviceType:6 Origin:6 ClientVersion:2025.11.0 => Bit.Api.Vault.Controllers.CiphersController.PostFileForExistingAttachment (Api)
      Unhandled exception
      System.IO.IOException: Unexpected end of Stream, the content may have already been read by another component. 
         at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.MultipartReader.ReadNextSectionAsync(CancellationToken cancellationToken)
         at Bit.Api.Utilities.MultipartFormDataHelper.GetFileAsync(HttpRequest request, Func`2 callback) in /source/src/Api/Utilities/MultipartFormDataHelper.cs:line 109
         at Bit.Api.Vault.Controllers.CiphersController.PostFileForExistingAttachment(Guid id, String attachmentId) in /source/src/Api/Vault/Controllers/CiphersController.cs:line 1425
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

--------------
Adding a login to a fresh install without importing data and trying to save an  attachment does not work either.

At work i self-host a Bitwarden Server with a business Enterprise Licence. 
The Version currently deployed there is Bitwarden Server 2025.10.1 with WebVersion 2025.10.1.
In this Installation saving the attachments works flawlessly and i am worried if i upgrade the installation at work it will blow.

I don't think i did something wrong with the new installation...As I said "by the book".

Can someone help me with this?

With kind regards,
Petros Stavrakakis

### Operating System

Linux

### Operating System Version

Ubuntu 25.04

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2025.11.0 SDK 'main (8ef7951)' Shell 37.7.0 Renderer 138.0.7204.251 Node 22.20.0 Architecture x64

### Issue Tracking Info

- [x] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by pamperer562580892423** [comment]
... maybe I misread it, but: what is your server version **at home**?

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by PetrosStavrakakis** [comment]
> ... maybe I misread it, but: what is your server version **at home**?

At home i installed the Server via the Linux Standard Deployment (bitwarden.sh).
 In the Script it states:
COREVERSION="2025.11.0"
WEBVERSION="2025.11.1"
KEYCONNECTORVERSION="2024.8.0"

**Comment by nthorez-mtg** [comment]
Hi. Same problem here.
Since update from 2025.10.1 to 2025.11.0 (docker install mode, update via bitwarden.sh), we are not able to upload any attachments from client (desktop and web). It appears that the files are deleted immediately.

From docker containers `bitwarden-admin` logs :
```
fail: Bit.Core.Utilities.LoggingExceptionHandlerFilterAttribute[0]
bitwarden-admin          |       => SpanId:24a0e880129419bc, TraceId:f96088a854f6b4ffc5c2b5ad07d12170, ParentId:0000000000000000 => ConnectionId:0HNH5LTQ25IV3 => RequestPath:/admin/login RequestId:0HNH5LTQ25IV3:00000001 => Bit.Admin.Auth.Controllers.LoginController.Index (Admin)
bitwarden-admin          |       Unhandled exception
bitwarden-admin          |       MailKit.Security.AuthenticationException: 535: 5.7.8 Username and Password not accepted. For more information, go to
bitwarden-admin          |       5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-42b53f2084dsm32287204f8f.42 - gsmtp
bitwarden-admin          |        ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Username and Password not accepted. For more information, go to
bitwarden-admin          |       5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-42b53f2084dsm32287204f8f.42 - gsmtp
bitwarden-admin          |          --- End of inner exception stack trace ---
bitwarden-admin          |          at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
bitwarden-admin          |          at Bit.Core.Services.MailKitSmtpMailDeliveryService.SendEmailAsync(MailMessage message, CancellationToken cancellationToken) in /source/src/Core/Services/Implementations/MailKitSmtpMailDeliveryService.cs:line 112
bitwarden-admin          |          at Bit.Core.Services.MailKitSmtpMailDeliveryService.SendEmailAsync(MailMessage message) in /source/src/Core/Services/Implementations/MailKitSmtpMailDeliveryService.cs:line 45
bitwarden-admin          |          at Bit.Core.Services.HandlebarsMailService.SendPasswordlessSignInAsync(String returnUrl, String token, String email) in /source/src/Core/Services/Implementations/HandlebarsMailService.cs:line 488
bitwarden-admin          |          at Bit.Admin.Auth.IdentityServer.PasswordlessSignInManager`1.PasswordlessSignInAsync(String email, String returnUrl) in /source/src/Admin/Auth/IdentityServer/PasswordlessSignInManager.cs:line 37
bitwarden-admin          |          at Bit.Admin.Auth.Controllers.LoginController.Index(LoginModel model) in /source/src/Admin/Auth/Controllers/LoginController.cs:line 43
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
bitwarden-admin          | fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
bitwarden-admin          |       => SpanId:24a0e880129419bc, TraceId:f96088a854f6b4ffc5c2b5ad07d12170, ParentId:0000000000000000 => ConnectionId:0HNH5LTQ25IV3 => RequestPath:/admin/login RequestId:0HNH5LTQ25IV3:00000001
bitwarden-admin          |       An unhandled exception has occurred while executing the request.
bitwarden-admin          |       MailKit.Security.AuthenticationException: 535: 5.7.8 Username and Password not accepted. For more information, go to
bitwarden-admin          |       5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-42b53f2084dsm32287204f8f.42 - gsmtp
bitwarden-admin          |        ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Username and Password not accepted. For more information, go to
bitwarden-admin          |       5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-42b53f2084dsm32287204f8f.42 - gsmtp
bitwarden-admin          |          --- End of inner exception stack trace ---
bitwarden-admin          |          at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
bitwarden-admin          |          at Bit.Core.Services.MailKitSmtpMailDeliveryService.SendEmailAsync(MailMessage message, CancellationToken cancellationToken) in /source/src/Core/Services/Implementations/MailKitSmtpMailDeliveryService.cs:line 112
bitwarden-admin          |          at Bit.Core.Services.MailKitSmtpMailDeliveryService.SendEmailAsync(MailMessage message) in /source/src/Core/Services/Implementations/MailKitSmtpMailDeliveryService.cs:line 45
bitwarden-admin          |          at Bit.Core.Services.HandlebarsMailService.SendPasswordlessSignInAsync(String returnUrl, String token, String email) in /source/src/Core/Services/Implementations/HandlebarsMailService.cs:line 488
bitwarden-admin          |          at Bit.Admin.Auth.IdentityServer.PasswordlessSignInManager`1.PasswordlessSignInAsync(String email, String returnUrl) in /source/src/Admin/Auth/IdentityServer/PasswordlessSignInManager.cs:line 37
bitwarden-admin          |          at Bit.Admin.Auth.Controllers.LoginController.Index(LoginModel model) in /source/src/Admin/Auth/Controllers/LoginController.cs:line 43
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
bitwarden-admin          |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
bitwarden-admin          |          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
bitwarden-admin          |          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
bitwarden-admin          |          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
bitwarden-admin          |          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

From nginx access.log :
```
10.20.2.5 - - [18/Nov/2025:11:31:46 +0000] "POST /api/ciphers/7ddbafb3-ae72-491a-b4fe-b39900b9a37c/attachment/v2 HTTP/2.0" 200 1317 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.7103.177 Safari/537.36" "-"
10.20.2.5 - - [18/Nov/2025:11:31:46 +0000] "GET /api/ciphers/7ddbafb3-ae72-491a-b4fe-b39900b9a37c/details HTTP/2.0" 200 1276 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:145.0) Gecko/20100101 Firefox/145.0" "-"
10.20.2.5 - - [18/Nov/2025:11:31:46 +0000] "POST /api/ciphers/7ddbafb3-ae72-491a-b4fe-b39900b9a37c/attachment/cr81bfeonn55avawsb84vwuoupihbw8r HTTP/2.0" 500 174 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.7103.177 Safari/537.36" "-"
10.20.2.5 - - [18/Nov/2025:11:31:46 +0000] "DELETE /api/ciphers/7ddbafb3-ae72-491a-b4fe-b39900b9a37c/attachment/cr81bfeonn55avawsb84vwuoupihbw8r HTTP/2.0" 200 701 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.7103.177 Safari/537.36" "-"
10.20.2.5 - - [18/Nov/2025:11:31:46 +0000] "GET /api/ciphers/7ddbafb3-ae72-491a-b4fe-b39900b9a37c/details HTTP/2.0" 200 938 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:145.0) Gecko/20100101 Firefox/145.0" "-"
```

On client interface, we have this message : The cipher you are updating is out of date. Please save your work, sync your vault and try again.

Sync and log out, log won't correct this issue.

**Comment by PetrosStavrakakis** [comment]
As i see there is already a pull request in the server github section:

https://github.com/bitwarden/server/pull/6590

So a bugfix is on the way. :-)

**Comment by guillaumekoto** [comment]
I am waitting this fix.... Issue occure in our self-hosted instance. Hundreds users can't upload attachments!
I opened a support ticket (we have Business licences) and no solutions are provided ....

**Comment by PetrosStavrakakis** [comment]
> I am waitting this fix.... Issue occure in our self-hosted instance. Hundreds users can't upload attachments! I opened a support ticket (we have Business licences) and no solutions are provided ....

Hi.
The fix was commited yesterday.
https://github.com/bitwarden/server/commit/a724c933dc8572880828803f8160b8555de7283e

**Comment by guillaumekoto** [comment]
This release isn't not yet available with the standard update process:
./bitwarden.sh updateself
./bitwarden.sh update

**Comment by theofficialgman** [comment]
it generally takes a couple of weeks to a month for fixes to land in a release even if the release is made after the fix is committed to main it may not be present in a release until the next cycle.

I believe bitwarden uses the `rc` branch which is frequently force pushed to prepare the next release tag. This commit has be pushed to that `rc` branch as well so I expect it to make it in the next `2025.11.1` release

**Comment by ariane-bitwarden** [comment]
The fix has been cherrypicked to the rc branch and will go out with the next server release.

**Comment by guillaumekoto** [comment]
It's a critical bug for our users. Any ETA for this next release? 
It will appreciate to reduce the time between the fix and the release. It's anoying to discover this kind of regression in updates!

**Comment by cstisa** [comment]
Dear all,

Have you got some new with new release incluing this bugfix as this is critical for us and i think for other users.

Best Regards,

**Comment by schuettecarsten** [comment]
I have a similar issue, I cannot update TOTP secrets. When I try to save them, the browser client crashes and goes back to the login screen. The client shows an server error.

**Comment by pamperer562580892423** [comment]
> The fix has been cherrypicked to the rc branch and will go out with the next server release.

The next server release is now there: https://github.com/bitwarden/server/releases/tag/v2025.11.1 (PS: though not yet on https://github.com/bitwarden/self-host/releases) -- so in theory, the fix could be available now. (@ariane-bitwarden ?!)

**Comment by JasonAbruzzoIDN** [comment]
It has been two weeks, TWO WEEKS... any update?

**Comment by cstisa** [comment]
Hello, 

Thanks for the release , could we have the container images availables on GHCR for this release ? 

Thank You

Best Regards,

**Comment by schuettecarsten** [comment]
I really hope that this issue is fixed and that this release also accepts our license. Latest dev and beta builds dropped my Family test license, so I did not roll it out to the production environment.

**Comment by maxvisser** [comment]
IMO better to remove 2025.11 from release channels if you notice issues as this. As uploading attachments seems as a critical feature.

**Comment by guillaumekoto** [comment]
Always unavailable via ./bitwarden.sh updateself && ./bitwarden.sh update ...
We paid a business plan and this bug has critical impact on our production.
The official support redirect my request to this ticket. It's not suitable !

**Comment by guillaumekoto** [comment]
When will be available the update ???

**Comment by Simone-Tombolini** [comment]
Hi there,

I just updated to version 2025.11.1 and the bug is sill there, somebody have any news?

Self-hosted on Linux.

Best regards

**Comment by guillaumekoto** [comment]
No more informations... blackout at Bitwarden????

**Comment by ariane-bitwarden** [comment]
The self-hosted release of 2025.11.1 was released today (12/3): https://github.com/bitwarden/self-host/releases/tag/v2025.11.1

**Comment by guillaumekoto** [comment]
3 weeks to fix a critical bug in production for self-hosted users who paid Business Plan...

**Comment by vinnyperella** [comment]
> The self-hosted release of 2025.11.1 was released today (12/3): https://github.com/bitwarden/self-host/releases/tag/v2025.11.1 
 
@Simone-Tombolini 

Fixed in this version.

**Comment by schuettecarsten** [comment]
@djsmith85 unfortunately, it's not fixed. When I try to upload or modify attachments on the Organisation vault, the client logs out. Attachments are usable on my personal vault.

**Comment by PetrosStavrakakis** [comment]
@schuettecarsten :
Thats odd. I updated our self-hosted Instance at work and afterwards I tried to save attachments in a few entries of my personal vault as in the organizational vault with the Windows and Linux Client, Android App and via the Browser. Worked perfectly.
I updated all the Clients to the latest Version.

**Comment by BlackDex** [comment]
This seems to still be an issue for Self-Hosted (lite) instances. I tried both `:latest` and `:dev` just to be sure.

It only happens for Owner or Admin users of an Org and tries to add an attachment to an item via the `Password Manager` interface on an Org owned item. If a normal users of that same Org tries this it works fine, and also personal owned items work fine.

@djsmith85, this issue probable needs to be reopened.

```json
{
    "message": "An unhandled server error has occurred.",
    "validationErrors": null,
    "exceptionMessage": null,
    "exceptionStackTrace": null,
    "innerExceptionMessage": null,
    "object": "error"
}
```

```
Firefox/147.0 DeviceType:10 Origin:10 ClientVersion:2025.12.2 => Bit.Api.Vault.Controllers.CiphersController.PostAttachment (Api)
      Unhandled exception
      System.InvalidCastException: Unable to cast object of type 'Bit.Core.Vault.Models.Data.CipherOrganizationDetails' to type 'Bit.Core.Vault.Models.Data.CipherDetails'.
         at Bit.Core.Vault.Services.CipherService.CreateAttachmentForDelayedUploadAsync(Cipher cipher, String key, String fileName, Int64 fileSize, Boolean adminRequest, Guid savingUserId, Nullable`1 lastKnownRevisionDate)
         at Bit.Api.Vault.Controllers.CiphersController.PostAttachment(Guid id, AttachmentRequestModel request) in /source/src/Api/Vault/Controllers/CiphersController.cs:line 1364
         at lambda_method1420(Closure, Object)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by justindbaur** [comment]
@BlackDex Have you switched over to the new image name for lite? https://bitwarden.com/help/install-and-deploy-lite/ The latest version of lite right now is `2025.12.2` which should have the fix in it.

**Comment by BlackDex** [comment]
> [@BlackDex](https://github.com/BlackDex) Have you switched over to the new image name for lite? https://bitwarden.com/help/install-and-deploy-lite/ The latest version of lite right now is `2025.12.2` which should have the fix in it.

Yes, I'm using lite from ghcr.io, and the dev version i used did report v2025.12.2 as web-vault already, so that should also be correct.

I can probably try the latest lite version tomorrow.

**Comment by BlackDex** [comment]
@justindbaur, sorry, took a bit longer for me to have some time and test this again.
I'm using `ghcr.io/bitwarden/lite:latest`

<img width="291" height="129" alt="Image" src="https://github.com/user-attachments/assets/59104e6e-f989-4fd1-a852-986d3c871664" />

And uploading as an `Owner` or `Admin` fails on organizational owned items via the `Password Manager` interface.
Via the `Admin Console` interface, it works just fine, no issues.

Do note that the uploaded file does get attached, though the server returns a `500`, and the item isn't refreshed, and it looks like the upload has failed.
