### ISSUE TITLE
Password Protected Encrypted JSON Export Missing Folders

### ISSUE THREAD

**Issue by GurpreetKang** [bitwarden/clients#3555]
### Steps To Reproduce

1. Create a **_password protected_** Encrypted JSON export using the instructions here: https://bitwarden.com/help/cli/#export

### Expected Result

If you decrypt the file it should have folder entries in the "folders" array.

If you import it into a new/blank account it should create Folders.

### Actual Result

The "folders" array is empty.

Individual items in the vault may have a UUID in the "folderId" field, but since the "folders" array is empty folders cannot be recreated and information has been lost in the export.

_Note: Folders are correctly exported with a plaintext export._

### Operating System

Windows

### Operating System Version

Microsoft Windows 11 Pro, 10.0.22000 Build 22000

### Shell

PowerShell

### Build Version

2022.9.0

**Comment by alexpearce92** [comment]
Does this affect the unencrypted json export too?

**Comment by GurpreetKang** [comment]
No.

**Comment by djsmith85** [comment]
With the release of 2022.10 including several fixes and improvements around the exports, plus seeing some reports on the forums which indicate this has been fixed. @GurpreetKang Could you please test with 2022.10 and report back, if it's working please close this issue.

**Comment by GurpreetKang** [comment]
@djsmith85 
CLI v2022.10.0 (Win11) downloaded from GitHub: Issue still exits.

Once decrypted the JSON has:
`"folders": []`

**Comment by GurpreetKang** [comment]
Also, the unencrypted output does not contain Folders.  Previously on my system it did, though others (see above) reported that it also didn't.

**Comment by oeloo** [comment]
I have the most uptodate BW CLI, v2022.10 and have deeply tested the unencrypted Json export feature.
Around 1 time out of 5 the .JSON you get is missing folders: you get just: 
`{
 "encrypted": false,
 "folders": [],
 "items": [
    { (...)`
So people reporting it works are correct, but they were lucky. The truth is that 1 time out 5 it is not working (I have repeated this test more than 60 times of the last 5 hours).

**Comment by ingorichter** [comment]
I have the v2020.10 version and the folder are all missing. Not even 1 time out of 5 I have the folder in my export :-|

**Comment by oeloo** [comment]
THe fact that this important is still not fixed shows nothing good about this software: people will lose part of their data due to this.

**Comment by dbosompem** [comment]
Hi all, sorry for any inconveniences caused. I will communicate this to the team and we will make sure to take a second look at this issue. Appreciate your patience!
