### ISSUE TITLE
Enterprise Login (SAML2.0) in Ubuntu 22.10

### ISSUE THREAD

**Issue by alex005005** [bitwarden/clients#3931]
### Steps To Reproduce

1. Go to 'bitwarden Desktop' - either snap or AppImage doesn't work
2. Click on 'Enterprise Login'
3. Perform Login via SAML using (Chrome, Chromium, Firefox)
4. wait for Callback from Browser and Open with (xdg-open, directly to AppImage mounted ./bitwarden)

### Expected Result

Bitwarden Desktop logs ins

### Actual Result

1. Snap: New Instance of Bitwarden Desktop Opens
2. AppImage: Nothing

### Operating System

Linux

### Operating System Version

Ubuntu 22.10

### Installation method

Direct Download (from bitwarden.com), Snap

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TheBestPessimist** [comment]
This happens on windows as well for the portable version

**Comment by alex005005** [comment]
Actuall was reporter once already here https://github.com/bitwarden/desktop/issues/1156

**Comment by alex005005** [comment]
@Krychaz the issue still persists

**Comment by alex005005** [comment]
Tested the .deb Version. Works fine there. So something is broken with you snap package it seems.

**Comment by elfranne** [comment]
This issue is still present. Where did you find the debian version ?

I solved the issue by using the flatpak version: https://flathub.org/apps/com.bitwarden.desktop

**Comment by quexten** [comment]
Hi,

the reasons for snap and appimage being broken are completely different, however both are fixed by https://github.com/bitwarden/clients/pull/10548 , and the corresponding server pull request linked in the PR. It will be included in the next release. Please feel free to re-open should you still encounter issues.

**Comment by jskillin-idt** [comment]
Snap 2024.8.2 appears to still have issues. Is a later release expected to fix this?
