### ISSUE TITLE
Browser extension 2023.3 broke our webpage

### ISSUE THREAD

**Issue by darnasii** [bitwarden/clients#5107]
### Steps To Reproduce

i'm not sure. We can't let you access to our website, it's behind VPN, for organization purposes.

### Expected Result

Resolve the problem with new extension.

### Actual Result

We have a problem with our webpage - it's our implementation of LMS (Lan Management System). On 2023.3 extension, when there are multiple autofill options, webpage the site crashes and the processor spikes to 100%. Nothing can be clicked, nothing can be done. Disabling the autocomplete option does not help, only disabling the plugin or downgrading it to version 2023.2.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome, Microsoft Edge, Firefox, Opera, Brave, Vivaldi

### Browser Version

Newest

### Build Version

2023.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by joshtrichards** [comment]
Is it based on this - https://lms.org.pl/about.php?lang=en ?

If so - does it occur for you with the online demo: https://lms.org.pl/demo.php ?

If so, that might be a way to provide the steps to reproduce it.

**Comment by darnasii** [comment]
Got a short video of what is happening. Website freeze short after full load.

https://user-images.githubusercontent.com/129312219/228611571-0d52138f-a455-443b-bccc-4ab87cd8d1ef.mp4

**Comment by joshuabjordan** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by chennin** [comment]
I observe 100% CPU on [Elite: Dangerous Shipyard](https://edsy.org/). Repro: Click any ship name, then click the power priority numbers (circled below). They go 1-5; see how fast they change and what the CPU does with and without the BW extenstion enabled.

![image](https://user-images.githubusercontent.com/2653277/228689283-babc528f-5628-4531-9333-3542f6746cdd.png)

I use Firefox (111.0.1) on Windows 10, with BW extension Version 2023.3.0.

FF performance capture with BW enabled:

![image](https://user-images.githubusercontent.com/2653277/228690021-6a3df96b-2108-4ede-8ebd-fff45ff7901c.png)

And without BW extension:

![image](https://user-images.githubusercontent.com/2653277/228690082-db42356b-1736-46e7-a4f6-4106dd8b3318.png)


Let me know if this actually isn't related and I should open a new issue.

**Comment by darnasii** [comment]
Got some more stuff from dev tools in Chrome. Maybe will help with problem. Extension starts with "nngceck..." is BitWarden 2023.3 version.
![dev2](https://user-images.githubusercontent.com/129312219/228808783-4efc61c5-8fc7-4c63-92aa-a7465bf4daab.png)
![dev1](https://user-images.githubusercontent.com/129312219/228808789-72d3e417-7f1a-4a08-a2cb-9e02261fa1d3.png)

**Comment by darnasii** [comment]
On 2023.2 - no autofill, no problem.
![dev4](https://user-images.githubusercontent.com/129312219/228815206-c935b8c5-a4ad-47c2-8e9e-07c448ec7ad8.png)
![dev3](https://user-images.githubusercontent.com/129312219/228815210-2dee338b-680a-43fe-addd-5a46a2dfa167.png)

**Comment by vlad-infra-admin** [comment]
Same here. I had to disable extension. It broke some pages of our internal resources

**Comment by KoalaG** [comment]
I have also been experiencing this issue, but with our instance of bestpractical.com Request Tracker. The results pages have a lot of hidden fields that become visible when the user clicks on the field. The browser will freeze for up to 13 seconds once the page loads. Disable the extension and everything is fine.

**Comment by bcardellini** [comment]
Seeing this issue as well.  On Edge with bitwarden extension 2022.3, TTI for pages in our internal system is 9.1s.  With bitwarden extension disabled TTI is 2.7s.

**Comment by anthmage** [comment]
Seems like GestioIP, a self-hosted IPAM management solution, falls victim as well, specifically when interacting with search boxes and dropdowns. Reverting to 2023.2 for now as it seems it was introduced in 2023.3.

**Comment by clangenb** [comment]
I can also observe this when reviewing the files of a massive GitHub pull request, see https://github.com/encointer/encointer-wallet-flutter/pull/1101/files#

**Comment by NoiseEee** [comment]
I am also having to disable BitWarden all of a sudden because our internal app pages lose interactivity and CPU spikes

**Comment by trmartin4** [comment]
Thank you all for your feedback.  We have been able to replicate this issue internally and are working on a hotfix release of the browser extension that will address the performance issues described above.  I will update this thread when the new version is released.

**Comment by trmartin4** [comment]
The performance issue has been addressed with version `2023.3.1`.

**Comment by MarkProDev** [comment]
Although this has been reported as fixed, we are still seeing the issue with the 2023.3.1 browser extension installed in Chrome on Windows 10 only.  When there are a large number of elements on the page (we have a select control with potentially over 13,000 options in it).  We can see that the algorithm is looping through the DOM but there is probably no need for it to look inside <select> elements.  If this can't be addressed soon, is there any way we can just force Bitwarden to deactivate itself for specific URLs?

**Comment by joshtrichards** [comment]
@MarkProDev : Chrome has the ability to set an extension to only read/write data for a web site "OnClick" which might be helpful for your goal. It can be found in Chrome's by right-clicking the extension's icon and selecting `Manage Extension`.

**Comment by Tipoff4317** [comment]
@Brettflan 

It seems to take 6-7 days once they release it to github for it to be approved (as recommended app) on Firefox.  This time, it took 7 days, and 2023.3.1 is available now.
