### ISSUE TITLE
Windows Hello prompt opens in background

### ISSUE THREAD

**Issue by Sethz** [bitwarden/clients#5287]
### Steps To Reproduce

1. Go to 'Bitwarden Desktop App'
2. Click on [Unlock with Windows Hello]

### Expected Result

Windows Hello prompt (Windows Security Window) should open in foreground 

### Actual Result

Windows Hello prompt (Windows Security Window) should opens in background

### Additional Context

I commented here aswell #

### Operating System

Windows

### Operating System Version

11 Pro 10.0.22621 Build 22621

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.3.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Noggington** [comment]
I am having same issue - just updated to version  2023.4.0 and now Windows Hello launches behind the Bitwarden desktop window.

Previous version of BitWarden did not cause this behavior - the Windows Hello always popped up on top.

Windows 11 Pro Canary Build - V 25352.1
Bitwarden 2023.4.0
Installation Method : Update prompt from Bitwarden Desktop app after machine was restarted and app reloaded.

**Comment by MGibson1** [comment]
We are using a more secure method of prompting for Windows Hello, but unfortunately it defaults to being in the background, as a separate window.

We have some mitigations in place to pull the window to the foreground, but it's not a guarantee. Windows' API currently lacks the ability to set a parent windows for these kinds of requests. We're putting together upstream requests for improvement.

Can you give some more context? Does the popup _never_ come to the front, or does it take a moment to be recognized and pulled forward? If it's taking a moment to come forward, that's the intended behavior barring changes upstream.

**Comment by Noggington** [comment]
I just tried it again with the desktop app - and it is coming up behind - and unfortunately it doesn't come to the front when its left to its own devices. 

I have left it for a minute with no window hello coming to front.

When I click on the windows hello prompt in the task bar - it comes to the front and then activates and logs in with my face.

![image](https://user-images.githubusercontent.com/88229234/235610163-ab37fdee-541f-4986-9ab5-ac4a2d3c63f7.png)

![image](https://user-images.githubusercontent.com/88229234/235610239-58940612-715f-49cf-a291-29ad5006d7fc.png)

**Comment by kraighamady** [comment]
I get a constant loop even when I bring it to the foreground, verify, then get a 'something went wrong' and it keeps trying again and again.

**Comment by bahronheim** [comment]
> I get a constant loop even when I bring it to the foreground, verify, then get a 'something went wrong' and it keeps trying again and again.

That is the exact issue I had, but I just fixed it for myself.
To fix it I:
Went into the Desktop app.
Disabled Windows Hello and closed the settings window.
Tried to open biometric unlock from browser plugin to confirm it was really disabled.
Re-enabled Windows Hello from BW Desktop app settings menu.

It started working from that point on.

**Comment by Jnss98b** [comment]
> > I get a constant loop even when I bring it to the foreground, verify, then get a 'something went wrong' and it keeps trying again and again.
> 
> That is the exact issue I had, but I just fixed it for myself. To fix it I: Went into the Desktop app. Disabled Windows Hello and closed the settings window. Tried to open biometric unlock from browser plugin to confirm it was really disabled. Re-enabled Windows Hello from BW Desktop app settings menu.
> 
> It started working from that point on.

Tried this and it did not fix it for me

**Comment by kraighamady** [comment]
> > I get a constant loop even when I bring it to the foreground, verify, then get a 'something went wrong' and it keeps trying again and again.
> 
> That is the exact issue I had, but I just fixed it for myself. To fix it I: Went into the Desktop app. Disabled Windows Hello and closed the settings window. Tried to open biometric unlock from browser plugin to confirm it was really disabled. Re-enabled Windows Hello from BW Desktop app settings menu.
> 
> It started working from that point on.

This did work for me though I needed to restart the app (I may have needed to reboot, but can't remember if I did).

**Comment by Jnss98b** [comment]
I just straight up reinstalling the desktop client and that fixed it for me

**Comment by ados8** [comment]
Hi all,
I've had this issue for ages regarding Windows Hello on multiple devices.
I'm not sure if it's Birwarden specific as its mainly primarily the app I use for Hello authentication other than lock screen.

Anyway, it was annoying enough that I made a simple app that mitigates it completely.
It's freely available here: [https://github.com/ados8/Hellofy](url)
May it make your lives easier 😉.

**Comment by Jnss98b** [comment]
> @Jnss98b @kraighamady. Did this start happening right after updating to 2023.4.0?
> 
> I'll need to look into the upgrade path for loops that might cause repeatedly prompting. Do you happen to know the versions you were upgrading from?

I'm not sure but I have 2023.4.0 right now and I don't have that problem. I think it happened around winter of last year for me and like I said I reinstalled and it was fixed, although it took 2 tries

**Comment by geoffbon** [comment]
> We have some mitigations in place to pull the window to the foreground, but it's not a guarantee. Windows' API currently lacks the ability to set a parent windows for these kinds of requests. We're putting together upstream requests for improvement.

Is there any news on the upstream request getting actioned?  I still see the originally described behavior, i.e. the Windows Hello window opens in the background and does not come to the front.

**Comment by devkhan** [comment]
Just adding more info in case it helps in debugging.

The issues exists in one of my systems, with the following versions:

### System 1
```
Windows:

Edition	Windows 11 Home Single Language
Version	23H2
Installed on	‎09-‎05-‎2024
OS build	22631.3880
Experience	Windows Feature Experience Pack 1000.22700.1020.0

Bitwarden:

Version 2024.7.1
Shell 31.2.0
Renderer 126.0.6478.127
Node 20.15.0
Architecture x64
```

But it works completely fine (foreground prompt):

### System 2

```
Windows:

Edition    Windows 11 Pro
Version    23H2
Installed on    10-07-2024
OS build    22631.3958
Serial number    5CD350CJJN
Experience    Windows Feature Experience Pack 1000.22700.1026.0

Bitwarden:

Version 2024.6.4
Shell 29.4.2
Renderer 122.0.6261.156
Node 20.9.0
Architecture x64
```

Just want to point out that it wasn't working on System 1 ever since I first set it up (in May 2024), but system 2 was setup in July and it still works in it.

**Comment by ados8** [comment]
This bugged me so much that a while ago I created a Windows app to "fix" it.
It was done to just get the job done and is just mitigating the problem but it works.
Been using for over a year and keeps the window in focus enough to use the app and plugin.

**Comment by TheGoldenMan99** [comment]
Same issue here, please fix it. As Face unlock requires a user input, this bug renders it unusable. Because when manually selection the windows hello from the background, the unlock works but it fails to connect the unlock to Bitwarden posing an endless loop of unlocks that all fail. For me Windows hello is completely broken for now.

**Comment by quexten** [comment]
@TheGoldenMan99 (and other users experiencing this issue) Is this still occurring for you? 

This one is tricky to reproduce, so #11257 tries to improve our workaround to the upstream issue, which *might* fix things.

A few more questions:
Is it *always* in the background, or just sometimes?
Does running in administrator mode fix things for you? (Please just do this once to try, don't use this as a permanent solution).

**Comment by archon810** [comment]
Just found this issue because Bitwarden on a new laptop with Win11 (Thinkpad X1 Carbon 13 gen) with Bitwarden for Windows (v2024.12.1) installed and communicating with the extension in Chrome (v2024.12.2) never pops up the Hello dialog and I always find it in the background. It's very annoying and frustrating, to be honest.

**Comment by quexten** [comment]
Hi all! It seems a Windows update is supposed to fix this. At the same time a fix for this issue for Bitwarden desktop, and the browser extensions is also added here https://github.com/bitwarden/clients/pull/12255, and will be included in an upcoming release.

**Comment by oneisall8955** [comment]
Both the browser plug-in and the desktop application are upgraded to the latest version. The browser plug-in behaves normally, but the problem still occurs in the browser.

```txt
Version: 2025.3.0
SDK: 'main (6008e90)'
Server version: 2024.2.0
```

**Comment by Aalivexy** [comment]
The desktop can pop up to the foreground normally, but the Chrome plug-in still does not work

Chrome Ext
```
Version: 2025.3.1
SDK: 'main (6008e90)'
Server version：2025.1.0
```

Desktop
```
Version 2025.2.1
SDK 'main (6008e90)'
Shell 34.0.0
Renderer 132.0.6834.83
Node 20.18.1
Architecture x64
```

**Comment by Gnomey123** [comment]
I'm having the same issue, but with the Firefox Extension:

Firefox version:
136.0.4 (64-bit)

Firefox Bitwarden Ext:
Version: 2025.2.0
SDK: 'main (28c7e29)'


Windows Desktop Bitwarden:

Version 2025.2.1
SDK 'main (6008e90)'
Shell 34.0.0
Renderer 132.0.6834.83
Node 20.18.1
Architecture x64


Windows Version:

OS Name	Microsoft Windows 11 Pro
Version	       10.0.22631 Build 22631
Processor       AMD Ryzen 9 7940HS w/ Radeon 780M Graphics, 4001 Mhz, 8 Core(s), 16 Logical Processor(s)
OS Build         22631.5039




> The desktop can pop up to the foreground normally, but the Chrome plug-in still does not work
> 
> Chrome Ext
> 
> ```
> Version: 2025.3.1
> SDK: 'main (6008e90)'
> Server version：2025.1.0
> ```
> 
> Desktop
> 
> ```
> Version 2025.2.1
> SDK 'main (6008e90)'
> Shell 34.0.0
> Renderer 132.0.6834.83
> Node 20.18.1
> Architecture x64
> ```

**Comment by kristianpinke** [comment]
Issue persists nowadays with version:
2025.2.1
6008e90
34.0.0
132.0.6834.83
20.18.1
x64

For business reasons I am using 1Password on the same machine and there the integration with Windows Hello is flawless, without any background start at all.

**Comment by Violaine70** [comment]
Issue still exists. Windows Hello is never brought to foreground.

Desktop: 2025.3.1
Brave extension: 2025.3.2
OS: W11 Pro 24H2 26100.3775

**Comment by thomasddn** [comment]
Hi lads,

The issue will persist as long as this issue hasn't been closed. Let me quote from @quexten's [comment](https://github.com/bitwarden/clients/issues/5287#issuecomment-2580118833):

> I will close this issue once the release including this fix is out.

**Comment by dechaoz05** [comment]
Same issue. Please fix asap.

**Comment by epmode** [comment]
I am also having this issue in the Firefox/Waterfox addon, but not in the desktop client.


**Desktop**
Version 2025.3.0
SDK 'main (50fa17)'
Shell 34.0.0
Renderer 132.0.6834.83
Node 20.18.1
Architecture x64

**Addon**
Version: 2025.3.2
SDK: 'main (50f5a17)'
Server version: 2025.4.3

**OS**
W11 Pro 23H2 22631.5189

**Comment by JamesDBartlett3** [comment]
I found a workaround, but it's not pretty... 🫤

Here's an AutoHotkey v1 script that runs in the background and watches for CredentialUIBroker.exe (the Windows Hello dialog). Whenever the dialog appears, the script automatically pushes it to the front. The script uses 2-3MB of RAM all the time, but the CPU load is so small, it registers as 0% in Task Manager.

[Keep_CredentialUIBroker_OnTop.ahk.txt](https://github.com/user-attachments/files/20052286/Keep_CredentialUIBroker_OnTop.ahk.txt)

Download the file, rename it to remove the .txt at the end (GitHub won't let users upload .ahk files directly), and then run it in AutoHotkey v1. If you want it to launch on login, add it to your startup folder (`shell:startup`).

**Comment by FroggMaster** [comment]
> I found a workaround, but it's not pretty... 🫤
> 
> Here's an AutoHotkey v1 script that runs in the background and watches for CredentialUIBroker.exe (the Windows Hello dialog). Whenever the dialog appears, the script automatically pushes it to the front. The script uses 2-3MB of RAM all the time, but the CPU load is so small, it registers as 0% in Task Manager.
> 
> [Keep_CredentialUIBroker_OnTop.ahk.txt](https://github.com/user-attachments/files/20052286/Keep_CredentialUIBroker_OnTop.ahk.txt)
> 
> Download the file, rename it to remove the .txt at the end (GitHub won't let users upload .ahk files directly), and then run it in AutoHotkey v1. If you want it to launch on login, add it to your startup folder (`shell:startup`).

The internet is a magical place. I'm having this exact problem and I figured I would google it to see if it's a known issue before I wrote a script exactly like this monitor and pull the authentication window to the front. 

Thanks for sharing your workaround. 🐸

**Comment by mwdle** [comment]
Is it just me or is this finally fixed in the last few days? The Windows Hello prompt just appeared in the _foreground_ for me and worked how I'd expect it should. I relocked my vault and again the prompt appeared in the foreground and not the background. Is anyone else seeing this behave as expected now?

Bitwarden Extension Version: 2025.3.2 | SDK: 'main (50f5a17)' | Server version: 2025.4.3

I'm running on Brave Browser Version 1.78.94 | Chromium: 136.0.7103.60 on Windows 11 Pro Version 10.0.26100

**Comment by deepdvd** [comment]
> I found a workaround, but it's not pretty... 🫤
> 
> Here's an AutoHotkey v1 script that runs in the background and watches for CredentialUIBroker.exe (the Windows Hello dialog). Whenever the dialog appears, the script automatically pushes it to the front. The script uses 2-3MB of RAM all the time, but the CPU load is so small, it registers as 0% in Task Manager.
> 
> [Keep_CredentialUIBroker_OnTop.ahk.txt](https://github.com/user-attachments/files/20052286/Keep_CredentialUIBroker_OnTop.ahk.txt)
> 
> Download the file, rename it to remove the .txt at the end (GitHub won't let users upload .ahk files directly), and then run it in AutoHotkey v1. If you want it to launch on login, add it to your startup folder (`shell:startup`).

This AutoHotkey script is awesome! I found out that you don't need to have it Persistent, so I commented out the first line with a semicolon.  Now it runs once and exits, but still makes CredentialUIBroker.exe always on top!

```
;#Persistent
SetTitleMatchMode, 2
SetTimer, KeepOnTop, 1000

KeepOnTop:
WinSet, AlwaysOnTop, On, CredentialUIBroker.exe
return
```

**Comment by play150** [comment]
I'm also having this issue of Windows Hello popping under instead of on top! Microsoft Edge extension 2025.6.1 ! It has never once popped up on top for me.

**Comment by X012C** [comment]
I'm also having this issue of Windows Hello popping under instead of on top! firefox extension .

**Comment by FroggMaster** [comment]
I've written a FOSS application in C++ that does the same as the AHK script above. There's nothing wrong with the AHK method, but some games that I play will prevent me from launching if AHK scripts are detected so as an alternative I wrote this C++ application.

You can get it here: [AuthAlwaysOnTop](https://github.com/FroggMaster/AuthAlwaysOnTop/releases/latest)

**Comment by oneisall8955** [comment]
@FroggMaster

Awesome ! Thanks for sharing, it works great !

**Comment by jonatino** [comment]
When it opens in the background often times my auth will not work. If my face is detected while the window is in the background the auth will fail and show this yellow text. The only way to make it work again is close bitwarden and hope to focus the auth window before it detects my face. It's super annoying.

<img width="699" height="590" alt="Image" src="https://github.com/user-attachments/assets/e0eb0497-ed45-4fec-8708-67a813f6274e" />

**Comment by Aalivexy** [comment]
https://github.com/Aalivexy/bwbio

Good news, I think I may have found the root of the problem, at least I can make it appear in the foreground stably.

The core of the problem lies in this code, which works fine on the client side because the bitwarden client has focus when biometric authentication is required. However, in the browser, SetForegroundWindow may be denied.

```rust
/// Searches for a window that looks like a security prompt and set it as focused.
/// Only works when the process has permission to foreground, either by being in foreground
/// Or by being given foreground permission https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow#remarks
pub fn focus_security_prompt() {
    let class_name = s!("Credential Dialog Xaml Host");
    let hwnd = unsafe { FindWindowA(class_name, None) };
    if let Ok(hwnd) = hwnd {
        set_focus(hwnd);
    }
}

pub(crate) fn set_focus(window: HWND) {
    unsafe {
        let _ = SetForegroundWindow(window);
        let _ = SetFocus(Some(window));
    }
}
```

But I didn't find this problem directly. In fact, I didn't think about it that way at first. Since I couldn't stand this terrible experience and didn't want to run another Electron app in the system background, I re-implemented a native messaging app for biometrics that supports Bitwarden's browser extension. It is less than 1MB in size and takes up 1MB of memory. I also encountered the same problem as the official app at first, the pop-up window could not be automatically pinned to the top, but after searching and trying, I found a solution:

```rust
fn center_security_prompt() {
    let hwnd = unsafe { FindWindowW(w!("Credential Dialog Xaml Host"), None) };
    if let Ok(hwnd) = hwnd {
        unsafe {
            let fg_hwnd = GetForegroundWindow();
            let cur_id = GetCurrentThreadId();
            let fg_id = GetWindowThreadProcessId(fg_hwnd, None);
            let _ = AttachThreadInput(cur_id, fg_id, true);
            let _ = SetForegroundWindow(hwnd);
            let _ = BringWindowToTop(hwnd);
            let _ = SetFocus(Some(hwnd));
            let _ = AttachThreadInput(cur_id, fg_id, false);
        }
    }
}
```

It's a bit of a hack, but it works. However, my app still requires manual import of the key and manual setup of the browser extension. Maybe I'll make an automatic setup later when I have time.

**Comment by Exostenza** [comment]
This is insane that this problem has been going on for three years! I just migrated to bitwarden and bought premium which doesn't even have the phishing filter available as advertised in the Firefox plugin which is already a huge disappointment and then I find out that half the time the Windows Hello fingerprint prompt pops up in the background and I have to tab over to it or click on it in the task bar to get it to the foreground. 

What is going on with this company? Do they have any idea how to make a program that not only works as intended while also having advertised features of the paid version actually available when you buy it - obviously not. 

Regretting my purchase.

Edition	Windows 11 Pro
Version	25H2
Installed on	‎2026-‎03-‎24
OS build	26200.8117
Experience	Windows Feature Experience Pack 1000.26100.297.0

Firefox 149.02
Bitwarden Firefox Extension 2026.3.1
Bitwarden Windows Application 2026.3.1

**Comment by JpTiger** [comment]
Following. Would be nice to have a fix.

**Comment by themaninthesuitcase** [comment]
Also getting this since enabling Windows Hello with face detection. 

Now getting errors in the client which is new in the last week or so:

<img width="1430" height="839" alt="Image" src="https://github.com/user-attachments/assets/84aeebc7-9291-411a-9a74-091753032102" />

<img width="481" height="643" alt="Image" src="https://github.com/user-attachments/assets/7d734bd7-6075-46bd-9fef-369e3b58bad1" />


Edition	Windows 11 Pro
Version	25H2
Installed on	‎21/‎05/‎2025
OS build	26200.8655
Experience	Windows Feature Experience Pack 1000.26100.315.0

Chrome Plugin
Version: 2026.5.1
SDK: 'main (e13c4fc)'
Server version: 2026.6.0

Windows Client:
Version 2026.5.0
SDK 'main (e13c4fc)'
Shell 39.8.5
Renderer 142.0.7444.265
Node 22.22.1
Architecture x64

**Comment by Aalivexy** [comment]
I think we have a real solution now. The new version of the Windows SDK provides the `KeyCredential.RequestSignForWindowAsync` method to specify the foreground window.

https://github.com/microsoft/windows-rs/issues/3896

https://github.com/bitwarden/clients/pull/19968

**Comment by Miicker** [comment]
Is there any update? I still have this issue and it's very annoying. I bought a fingerprint scanner just for bitwarden, only to found out that it's slower then having to enter my pin.

**Comment by Aalivexy** [comment]
> Is there any update? I still have this issue and it's very annoying. I bought a fingerprint scanner just for bitwarden, only to found out that it's slower then having to enter my pin.

The upstream windows-rs has not released a new version for nearly a year. We need to wait for Microsoft to publish the RequestSignForWindowAsync API into windows-rs, but Microsoft seems to be encountering some issues in this regard.

**Comment by Aalivexy** [comment]
Personally, I think this is actually not Bitwarden's problem—it's that Microsoft provided this API too late. This should have been launched together with Windows Hello, but Microsoft didn't, so Bitwarden had to implement some workarounds. Even though Microsoft finally completed the API this year, they have still been dragging their feet on providing updates for the Rust SDK, resulting in Rust having no good way to use this API now.

**Comment by dpelechsw** [comment]
I’m seeing this as well on Windows 11 with Bitwarden Desktop 2026.8.0 and the browser extension 2026.7.0.

When I trigger **Unlock with biometrics** from Vivaldi, the Windows Hello fingerprint prompt opens in the background instead of receiving focus, so I have to Alt+Tab to it manually. The same setup works correctly in Google Chrome, and Windows Hello also surfaces correctly when unlocking the Bitwarden desktop app directly.

Vivaldi 8.1.4087.75 (Chromium 150.0.7871.253), Windows 11 25H2 (Build 26200.9168).

**Comment by KraXen72** [comment]
I’m seeing this as well on Windows 11 with Bitwarden Desktop 2026.8.0 and the browser extension 2026.7.0.

When I trigger **Unlock with biometrics** from Vivaldi, the Windows Hello fingerprint prompt opens in the background instead of receiving focus, so I have to Alt+Tab to it manually. The same setup works correctly in Google Chrome, and Windows Hello also surfaces correctly when unlocking the Bitwarden desktop app directly.

Vivaldi 8.1.4087.75 (Chromium 150.0.7871.253), Windows 11 25H2 (Build 26200.9168).

**Comment by Exostenza** [comment]
I started using bitwarden after I got hacked due to the Firefox password manager being subpar and liked bitwarden so much I was going to switch my mother to it as she has had password issues in the past. Well, stove the start when I go to unlock with biometrics using the Firefox extension the windows hello window comes up in the background and I have to alt tab to get it up. Now, for me this is a minor annoyance but for my boomer mother it's a complete deal breaker. I posted about this when I switched over at least 6 months ago, if not longer, and there's been zero progress regarding it so I haven't migrated my mother over. I bought myself pro to help support and get the 2fa, phishing, and other perks when I first migrated and was going to do the same for my mother but this issue has persisted so I won't put her on it. 

I guess I'll have to find another password manager for her that brings up the biometric unlock to the foreground so she can actually use it. That sucks because I really like bitwarden but it seems like if they can't fix something as rudimentary as that then what else is broken? I hope I never have to find out.
