### ISSUE TITLE
BitWarden doesn't automatically ask for Windows Hello on app start (when setting is enabled.)

### ISSUE THREAD

**Issue by jboutin** [bitwarden/clients#6172]
### Steps To Reproduce

1. Open BitWarden > **File** > **Settings** >
2. Check to enable "**Unlock With Windows Hello**", as well as "**Ask for Windows Hello on app start.**"
3. Close **Settings**, and Exit BitWarden (**File** > **Quit BitWarden**)
4. Re-open BitWarden, and verify it no longer automatically asks for Windows Hello. You can manually click "**Unlock with Windows Hello**" and it'll then ask for your pin/biometrics... but it no longer automatically asks.

### Expected Result

Prior to updating to `2023.8.2`, when you had "**Ask for Windows Hello on app start.**" enabled, when you restarted your computer, or reopened BitWarden, it would automatically prompt you for your Windows Hello.

### Actual Result

Enabling the setting doesn't appear to do anything.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/5445867/60903618-e143-4f45-aa1a-3effbd92f1af)

### Additional Context

**Version Info:**
- **Version:** 2023.8.2
- **Shell:** 24.1.1
- **Renderer:** 112.0.5615.50
- **Node:** 18.14.0

### Operating System

Windows

### Operating System Version

Windows 10 22H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bundyland** [comment]
Same problem here since latest update.

**Comment by charlene-johnson** [comment]
I am getting that same issue. I did not know that the app recently updated, but this has been happening to me the past few days.

**Comment by ajaybhargav** [comment]
Same issue. Unless Bitwarden app is restarted, I am not even able to unlock firefox extension via Windows Hello. Not sure if you guys face the same issue. Debug console shows desktop app and extension is communicating and exchanging messages though.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by stefanwascoding** [comment]
Same issue on macOS with "Ask for Touch ID on launch".

**Comment by vrosu** [comment]
I'm on 2023.8.3 and this happens for me as well.
One of the things I tried was to disable the setting, restart the app, then enable it back again, then restart the app, but it did not solve it.
I'm on Windows 11 23H2, 22631.2271 (beta ring).

**Comment by Nicojii** [comment]
Happened to me also. Still happens with newest version 2023.8.3.

**Comment by bundyland** [comment]
Problem still remains with version **2023.8.4** as well.

**Comment by xxhh1112** [comment]
eee

**Comment by vrosu** [comment]
Aaaand 2023.9.1

**Comment by jboutin** [comment]
Bumping because this is **STILL** broken.

**Comment by bundyland** [comment]
Problem remains on 2023.9.3

**Comment by ComotoJC** [comment]
Windows Hello & therefore also "biometrics" for browser plugin have been totally broken for a while.  This is not fixed.

**Comment by jboutin** [comment]
This still is broken **Version 2023.10.1**

**Comment by JuicyFran0** [comment]
I can confirm this issue is stull happening, not in the desktop app but with the browser plugin.

**Comment by Nicojii** [comment]
> I can confirm this issue is still happening, not in the desktop app but with the browser plugin.

Still on desktop as well :(

**Comment by gaiking-uk** [comment]
## BitWarden Update [Unofficial]
I asked BitWarden Support is there was any update on this issue, and they said...

> - This issue along its counterpart on MacOS system is currently **under engineering review**
> - Unfortunately **we do not have a release date** [at the moment]
> - However, the **priority of the bug is high**
>
> -- BitWarden Support, 13 Nov 2023
> 
> ![BitWarden-Support (Small)](https://github.com/bitwarden/clients/assets/37931190/f921a835-c021-4d96-9ad4-658b5c83ad1c)

**Comment by vladcudoidem** [comment]
I still have this problem on macOS.

**Comment by dMailonG** [comment]
2023.10.2 extension still broken.

**Comment by ali-agh** [comment]
I am facing the same problem.

**Comment by gaiking-uk** [comment]
## Workaround (kinda)

When I emailed BitWarden Support for an update on this last month, I even pointed out how potentially trivial the fix for this is -- as in essence BitWarden just needs to automatically click the **Unlock with Windows Hello** button when it opens. So, as we're now entering month 4 without a fix I made a crude workaround to do just that...

Feel free to use [BitWarden.exe](https://1drv.ms/u/s!Aljv4VucY46c22_g_ToK02aBwWGd?e=Ct004g). It is a compiled AutoHotKey script that...
- Launches `C:\Program Files\Bitwarden\Bitwarden.exe`
- Waits 3 seconds
- Sends the keystrokes `{Tab}{Tab}{Enter}` (which tabs to the **Unlock with Windows Hello** button and activates it)

```ahk
Run, "C:\Program Files\Bitwarden\Bitwarden.exe"
Sleep 3000
Send {Tab}{Tab}{Enter}
```

***

**FULL DISCLOSURE**: This is admittedly a bit of a crude hack but just wanted to share it in case anyone else was getting similarly fed-up of this and wanted an interim fix. Also, note that this file will be flagged by various engines on virustotal.com (11 at time), do not feel under any pressure to use if you feel un-easy -- I considered setting up a repo but (a) is a quick/dirty hack, and (b) am not sure how to give compile instructions other than just running the above code through the AHK2EXE compiler TBH.

**Comment by Lozian3D** [comment]
I do not believe this has been fixed.  I have version 2023.12.1 running on Windows 11 23H2 and still with all the correct settings, it does not prompt for Windows hello on start.

**Comment by Nicojii** [comment]
> I do not believe this has been fixed. I have version 2023.12.1 running on Windows 11 23H2 and still with all the correct settings, it does not prompt for Windows hello on start.

"This fix has passed our QA process and will be included in the 2024.1 release."

https://github.com/bitwarden/clients/pull/6400#issuecomment-1854482232

**Comment by nrgbistro** [comment]
Using version 2024.1 on windows 11 (fresh installation for both windows and bitwarden), I am still experiencing this issue. I can successfully enable windows hello integration in the desktop app and I can also log in with the Chrome extension. However, when I restart the bitwarden desktop app (or my laptop), the windows hello integration breaks. The Chrome extension can't display the hello unlock prompt, and the desktop client doesn't create the prompt or even show the 'unlock with windows hello' button. I'm using self-hosted vaultwarden, but I don't see how that would affect client integration with windows hello.

**Comment by gaiking-uk** [comment]
| Version | **2024.1.0** |
| --- | --- |
| Result | **✅ Fixed**  *potentially (see notes)* |
| Environment | Windows 11 23H2 | Desktop App |
| Notes | Building on @nrgbistro's post -- I only use Windows Hello to login to the desktop app (my BitWarden browser extension logs in with a PIN), however so far it seems to be working - I have restarted `BitWarden.exe` multiple times and it has auto-prompted for Windows Hello login each time as expected. I will post an update if further testing throws up any issues. |

**Comment by nrgbistro** [comment]
After reinstalling Bitwarden on Windows and disabling then enabling login with windows hello, the integration from the browser to the desktop application seems to be stable. I'll edit this comment if I notice any issues in the future.

**Comment by StinkyTACO** [comment]
Unless I'm dense this still doesn't work.

**Comment by Anokino** [comment]
### **Issue marked as closed, but the problem is still there...**

Bitwarden 2024.7.1
Windows 11 24H2

Bitwarden does not prompt for windows hello on start, and browser extension can't prompt windows hello either.

**Comment by player637204** [comment]
It is working now with the latest Version:

Version **2024.8.1**
Shell 31.3.1
Renderer 126.0.6478.185
Node 20.15.1
Architecture x64

**As soon as I open the Browser Add-In, Windows Hello is starting automatically.**

---
Browser Add-In might be 2024.8.1 already but desktop app not, then its not working.
Make sure to update the desktop app.

**Comment by nicolafarina** [comment]
Same issue is back on 2025.2.0.

**Comment by Moonstone3010** [comment]
In addition, when you click Unlock with biometrics, the window opens in the background rather than in the foreground.

**Comment by SethGottlieb** [comment]
Issue still persistent on latest version as of today
