### ISSUE TITLE
Linux Desktop Client blanks out when entering vault key

### ISSUE THREAD

**Issue by KPS-MWT** [bitwarden/clients#6560]
### Steps To Reproduce

1. Install Bitwarden 2023.9.1 or earlier through DEB package
2. generate vault with vault key
3. Update to 2023.9.2 through DEB package
4. Start Bitwarden
5. Try to enter vault

### Expected Result

Vault key entered and vault unlocked

### Actual Result

Bitwarden client blanks out completely. Can be restored by "view" -> "reload", but vault unlock try causes same result

### Screenshots or Videos

[Bildschirmaufzeichnung vom 12.10.2023, 11:39:17.webm](https://github.com/bitwarden/clients/assets/54021702/b0798474-3b63-4bad-b139-00405989ac43)

### Additional Context

Uninstalling 2023.9.2 and reinstalling 2023.9.1 makes everything working ok again.

Output from Shell when Bitwarden is run from there:

(node:39123) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
(node:39123) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:47194:55)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/opt/Bitwarden/resources/app.asar/main.js:47156:12)
    at BiometricsService.init (/opt/Bitwarden/resources/app.asar/main.js:47193:16)
    at Main.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:53805:46)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/Bitwarden/resources/app.asar/main.js:53702:58)
(node:39123) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
11:42:59.090 › Error: No password found
11:42:59.143 › Error: No password found
11:42:59.193 › Error: No password found
11:42:59.194 › Error: No password found
11:42:59.194 › Error: No password found
11:42:59.240 › Error: No password found
11:42:59.275 › TypeError: Cannot read properties of undefined (reading 'osSupportsBiometric')
    at BiometricsService.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:47199:55)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/opt/Bitwarden/resources/app.asar/main.js:47156:12)
    at BiometricsService.osSupportsBiometric (/opt/Bitwarden/resources/app.asar/main.js:47198:16)
    at BiometricsService.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:47209:58)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/Bitwarden/resources/app.asar/main.js:47157:58)
11:42:59.276 › TypeError: Cannot read properties of undefined (reading 'osSupportsBiometric')
    at BiometricsService.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:47199:55)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/opt/Bitwarden/resources/app.asar/main.js:47156:12)
    at BiometricsService.osSupportsBiometric (/opt/Bitwarden/resources/app.asar/main.js:47198:16)
    at DesktopCredentialStorageListener.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:47383:59)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:47311:71
    at new Promise (<anonymous>)
11:42:59.277 › Error: No password found
11:43:00.186 › Error: No password found
[39123:1012/114301.905771:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
11:43:01.975 › Error: No password found
11:43:02.202 › Error: No password found
11:43:02.685 › Error: No password found
11:43:02.931 › Error: No password found
11:43:03.213 › Error: No password found
[39157:1012/114304.117925:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!

### Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.9.2 Shell 26.3.0 Renderer 116.0.5845.228 Node 18.16.1 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jusevitch** [comment]
I can confirm this on Ubuntu 20.04 for version 2023.9.2. When I start typing my master password in the field, the window blanks out. Menus are accessible, but the app itself is unusable.

**Comment by jdhaines** [comment]
I'm seeing this behavior, but user interaction doesn't seem to affect it.  I can open the application and just wait 3-5 seconds to see the "crash".  Menus are still clickable, but the central UI is just blank.  If I keep my mouse cursor on the screen it seems to wait not exhibit the "crash" but one mouse-out and mouse-back kicks it off.  The current AppImage seems to be `2023.8.2` and doesn't exhibit this behavior.

My error is similar to above:

<details>
<summary>Logs</summary>
<pre class="notranslate">
(node:262630) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
(node:262630) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:47194:55)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/opt/Bitwarden/resources/app.asar/main.js:47156:12)
    at BiometricsService.init (/opt/Bitwarden/resources/app.asar/main.js:47193:16)
    at Main.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:53805:46)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/Bitwarden/resources/app.asar/main.js:53702:58)
(node:262630) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
(node:262630) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
    at new Menubar (/opt/Bitwarden/resources/app.asar/main.js:45540:131)
    at MenuMain.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:45594:56)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/Bitwarden/resources/app.asar/main.js:45564:58)
(node:262630) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
</pre>
</details>

**Comment by willmartian** [comment]
Thanks for the bug report! I am able to reliably reproduce on Ubuntu 22.04.2 with both the deb and AppImage. It looks like this might have been caused by our [recent Electron update](https://github.com/bitwarden/clients/pull/6511). The team is looking into a resolution now.

Potentially related: https://github.com/electron/electron/issues/32760

**Comment by LeeRoyManea** [comment]
Same Issue on newest Fedora Beta

**Comment by lukeab** [comment]
Same issue on AppImage and flatpack installs on ubuntu 23.04, even just login screen when first setting up, enter email field shows for 3/5 seconds then blanks out, using the menu, view->reload shows it again for 3 to 5 seconds and blanks again

Command line Trace

```bash
luke@luke-strix-670e-f-7900x3d  ~/opt/Bitwarden  ./Bitwarden-2023.9.2-x86_64.AppImage
(node:64111) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
(node:64111) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:47194:55)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:47156:12)
    at BiometricsService.init (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:47193:16)
    at Main.<anonymous> (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:53805:46)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:53702:58)
(node:64111) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:64111) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
    at new Menubar (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:45540:131)
    at MenuMain.<anonymous> (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:45594:56)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:45564:58)
(node:64111) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
10:01:00.528 › Checking for update
10:01:01.028 › Update for version 2023.9.2 is not available (latest version: 2023.9.2, downgrade is disallowed).
```

**Comment by Findarato** [comment]
What version should we be running as I am still getting this crash with the most recent published version?

**Comment by abysso2** [comment]
> What version should we be running as I am still getting this crash with the most recent published version?

2023.9.1 works like a charm

**Comment by larouxn** [comment]
> > What version should we be running as I am still getting this crash with the most recent published version?
> 
> 2023.9.1 works like a charm

Indeed seems like an issue with 2023.9.2. As mentioned above, most likely related change is the Electron bump: https://github.com/bitwarden/clients/pull/6511.

**Comment by juliocesarpg92** [comment]
I installed the previous version as commented before, but now the window don't even open. I'm just getting this on the console. 

```
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 12:22:28.454: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:22:28.455: Failed to load module "canberra-gtk-module"
``` 

to update i used the next hash
```
flatpak update --commit=c78a73925d4c7bc6c4bf3c0139b4cc3ec44af20fdbfcc005320453b45a524366 com.bitwarden.desktop
``` 
also try with the version 2022.8.4

**Comment by atraxsrc** [comment]
Same issue on Pop_os, using browser extention for now

**Comment by Jon-Kle** [comment]
Same problem here on Fedora Linux 38 (Workstation Edition) with the flatpack version.
I upgraded to Version 2023.9.2 and now it crashes after a short period of time after starting it.

**Comment by stephane-klein** [comment]
Same issue here: https://discussion.fedoraproject.org/t/bitwarden-flatpak-crash-typeerror-cannot-read-properties-of-undefined-reading-ossupportsbiometric/92674

**Comment by hal1961** [comment]
Meantime whenever Bitwarden-2023.9.1-x86_64.AppImage starts it automatically upgrades itself to the buggy Bitwarden-2023.9.2-x86_64.AppImage. I didn't find any setting to disable this behaviour. Also tried to set the file read only for everyone and changed the owner to root instead: even launched as normal user the file is replaced as well. Any hint to prevent the automatic update, at least until a fix is released?

**Comment by pjgg** [comment]
I can reproduce with Fedora 38

**Comment by rogue5oul** [comment]
I have the same behavior with flatpak version:
Version 2023.9.2
Shell 26.3.0
Renderer 116.0.5845.228
Node 18.16.1
Architecture x64

Running PopOS 22.04

**Comment by Grizz69** [comment]
I have had problems using Blend OS and Fedora38  both installed via Flatpak. AppImage does the same thing.  Recent since yesterday. I have uninstalled and reinstalled including different OS.  Only thing that seems to work is the browser extension, and I hate browser extensions. Currently using Fedora Silverblue 38.

**Comment by Ejjaffe** [comment]
Same issue on a fresh install of Linux Mint 21.2 Cinnamon 5.8.4, for both the .appimage and the .deb;  like above, I also saw the same error message in the command line, although they did happen *before* the page disappeared:
> ```shell
> luke@luke-strix-670e-f-7900x3d  ~/opt/Bitwarden  ./Bitwarden-2023.9.2-x86_64.AppImage
> (node:64111) DeprecationWarning: file property is deprecated and will be removed in v5.
> (Use `bitwarden --trace-deprecation ...` to show where the warning was created)
> (node:64111) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
>     at BiometricsService.<anonymous> (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:47194:55)
>     at Generator.next (<anonymous>)
>     at /tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:47160:71
>     at new Promise (<anonymous>)
>     at biometrics_service_awaiter (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:47156:12)
>     at BiometricsService.init (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:47193:16)
>     at Main.<anonymous> (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:53805:46)
>     at Generator.next (<anonymous>)
>     at fulfilled (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:53702:58)
> (node:64111) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:64111) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
>     at new Menubar (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:45540:131)
>     at MenuMain.<anonymous> (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:45594:56)
>     at Generator.next (<anonymous>)
>     at fulfilled (/tmp/.mount_BitwarZFVBrF/resources/app.asar/main.js:45564:58)
> (node:64111) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
> 10:01:00.528 › Checking for update
> 10:01:01.028 › Update for version 2023.9.2 is not available (latest version: 2023.9.2, downgrade is disallowed).
> ```

I looked into my `journalctl` and saw that there was actually a segfault and a core dump when the screen went white. I'm not sure how helpful this is, but here's the start of one of them:

```
bitwarden[16870]: segfault at 15a580001048 ip 0000564261c47f03 sp 00007ffe60b32450 error 27 in bitwarden[56425e2c5000+79cb000]
systemd-coredump[16925]: Process 16870 (bitwarden) of user 1000 dumped core.
                                                      Found module bitwarden with build-id: f5155371198e2958d1d28aa0316948e7e34b2dce
                                                      #0  0x0000564261c47f03 n/a (bitwarden + 0x58dcf03)
...
```

**Comment by leodip** [comment]
Is there a workaround for this? I have this issue on Fedora 38 with latest Flatpak.

**Comment by llabusch93** [comment]
Having the same issues as described by the other folks, Debian 12, Flatpak version

**Comment by PGQT** [comment]
> Same issue on Pop_os, using browser extention for now.
 I can add my voice to confirm the issue in pop-os. The application was working for me on Thursday last week, but since sometime over the weekend, it no longer works.

**Comment by hevanaa** [comment]
Me too, can't use it on Fedora now. Had to start using the browser extension.

Before that, for many weeks now (I can't remember when it started), Gnome notifications notified every time when Bitwarden desktop client locked and told that "Bitwarden crashed". A bit annoying. If you started it from the terminal, there are lots of error messages. Finally the message is telling about a real error now...

**Comment by hduinkerken84** [comment]
Having the same issue on fedora 38 using flatpak.
You can however downgrade to the previous version through flatpak using the steps used at https://itsfoss.com/downgrade-flatpak-packages/

I had to downgrade both com.bitwarden.desktop and com.bitwarden.desktop.Locale

**Comment by sgilissen** [comment]
Same behaviour on both the .deb and the flatpak version here on Debian 12. 
![bitwardenblank](https://github.com/bitwarden/clients/assets/187589/b77bad8a-8bbd-4e95-ac89-bb31a64963ac)

I usually don't even have the time to fill in my vault master password.

`22:51:42.137 › Error: No password found
(node:137265) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/opt/Bitwarden/resources/app.asar/main.js:46304:23)
    at MessagingMain.updateTrayMenu (/opt/Bitwarden/resources/app.asar/main.js:45804:28)
    at MessagingMain.onMessage (/opt/Bitwarden/resources/app.asar/main.js:45730:22)
    at MessagingMain.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:45721:151)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:45700:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/opt/Bitwarden/resources/app.asar/main.js:45696:12)
    at IpcMainImpl.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:45721:79)
    at IpcMainImpl.emit (node:events:513:28)
(node:137265) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
22:51:42.141 › Error: No password found
22:51:42.143 › Error: No password found
22:51:42.176 › Error: No password found
22:51:42.766 › Error: No password found
(node:137265) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/opt/Bitwarden/resources/app.asar/main.js:46304:23)
    at MessagingMain.updateTrayMenu (/opt/Bitwarden/resources/app.asar/main.js:45804:28)
    at MessagingMain.onMessage (/opt/Bitwarden/resources/app.asar/main.js:45730:22)
    at MessagingMain.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:45721:151)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:45700:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/opt/Bitwarden/resources/app.asar/main.js:45696:12)
    at IpcMainImpl.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:45721:79)
    at IpcMainImpl.emit (node:events:513:28)
(node:137265) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
22:51:44.529 › Error: No password found
22:51:44.556 › TypeError: Cannot read properties of undefined (reading 'deleteBiometricKey')
    at BiometricsService.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:47252:55)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/opt/Bitwarden/resources/app.asar/main.js:47156:12)
    at BiometricsService.deleteBiometricKey (/opt/Bitwarden/resources/app.asar/main.js:47250:16)
    at DesktopCredentialStorageListener.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:47434:45)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:47311:71
    at new Promise (<anonymous>)
22:51:44.556 › TypeError: Cannot read properties of undefined (reading 'deleteBiometricKey')
    at BiometricsService.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:47252:55)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/opt/Bitwarden/resources/app.asar/main.js:47156:12)
    at BiometricsService.deleteBiometricKey (/opt/Bitwarden/resources/app.asar/main.js:47250:16)
    at DesktopCredentialStorageListener.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:47434:45)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:47311:71
    at new Promise (<anonymous>)
(node:137265) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/opt/Bitwarden/resources/app.asar/main.js:46304:23)
    at MessagingMain.updateTrayMenu (/opt/Bitwarden/resources/app.asar/main.js:45804:28)
    at MessagingMain.onMessage (/opt/Bitwarden/resources/app.asar/main.js:45730:22)
    at MessagingMain.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:45721:151)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:45700:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/opt/Bitwarden/resources/app.asar/main.js:45696:12)
    at IpcMainImpl.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:45721:79)
    at IpcMainImpl.emit (node:events:513:28)
(node:137265) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)


`

**Comment by ricjuhnl** [comment]
Same issue on Debian 12 bookworm with Flatpak version:

`flatpak run com.bitwarden.desktop
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 07:44:47.991: Failed to load module "xapp-gtk3-module"
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:47194:55)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/app/Bitwarden/resources/app.asar/main.js:47156:12)
    at BiometricsService.init (/app/Bitwarden/resources/app.asar/main.js:47193:16)
    at Main.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:53805:46)
    at Generator.next (<anonymous>)
    at fulfilled (/app/Bitwarden/resources/app.asar/main.js:53702:58)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
    at new Menubar (/app/Bitwarden/resources/app.asar/main.js:45540:131)
    at MenuMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:45594:56)
    at Generator.next (<anonymous>)
    at fulfilled (/app/Bitwarden/resources/app.asar/main.js:45564:58)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94576)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:46672:38)
    at BrowserWindow.emit (node:events:525:35)`

**Comment by jtaala** [comment]
See same on Arch linux with latest version with:
- flatpak
- appimage

Reverted version to 2023.9.1 and `chattr +i`'d the appimage so it can't update...

**Comment by buvinghausen** [comment]
Pretty sure this is borked on every Linux distro via all distribution channels

**Comment by abysso2** [comment]
Solved with new release 2023.9.3:

https://github.com/bitwarden/clients/releases

**Comment by buvinghausen** [comment]
> Having the same issue on fedora 38 using flatpak. You can however downgrade to the previous version through flatpak using the steps used at https://itsfoss.com/downgrade-flatpak-packages/
> 
> I had to downgrade both com.bitwarden.desktop and com.bitwarden.desktop.Locale

```
sudo flatpak update --commit=c78a73925d4c7bc6c4bf3c0139b4cc3ec44af20fdbfcc005320453b45a524366 com.bitwarden.desktop

sudo flatpak update --commit=5ccea7bae339082be13d8fc35584e98301cfe00b441207cff18d32ebfb13618d com.bitwarden.desktop.Locale
```

**Comment by sixerstyle** [comment]
> Solved with new release 2023.9.3:
> 
> https://github.com/bitwarden/clients/releases

Isnt fixed, same Problem on 2023.9.3:

unning '/usr/bin/bwrap --args 40 bitwarden --trace-deprecation'
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
    at new ElectronLogService (/app/Bitwarden/resources/app.asar/main.js:47508:50)
    at new Main (/app/Bitwarden/resources/app.asar/main.js:53758:27)
    at 64164 (/app/Bitwarden/resources/app.asar/main.js:44265:18)
    at __webpack_require__ (/app/Bitwarden/resources/app.asar/main.js:58132:42)
    at /app/Bitwarden/resources/app.asar/main.js:58188:37
    at Object.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:58190:12)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:47194:55)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/app/Bitwarden/resources/app.asar/main.js:47156:12)
    at BiometricsService.init (/app/Bitwarden/resources/app.asar/main.js:47193:16)
    at Main.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:53805:46)
    at Generator.next (<anonymous>)
    at fulfilled (/app/Bitwarden/resources/app.asar/main.js:53702:58)
(Use `bitwarden --trace-warnings ...` to show where the warning was created)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
    at new Menubar (/app/Bitwarden/resources/app.asar/main.js:45540:131)
    at MenuMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:45594:56)
    at Generator.next (<anonymous>)
    at fulfilled (/app/Bitwarden/resources/app.asar/main.js:45564:58)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[41:1020/174057.588766:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[41:1020/174057.590011:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!

**Comment by hevanaa** [comment]
It works again in Fedora 38 with 2023.9.3 version from flathub. 

But I still get this annoying message "We're sorry, it looks like Bitwarden crashed" message in Gnome every time Bitwarden is locked. If you start it from command line, it's full of error messages.

E.g. things like this:
› Error: No password found
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/app/Bitwarden/resources/app.asar/main.js:46304:23)

(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)

**Comment by sixerstyle** [comment]
with Gnome its works with version 2023.9.3. In KDE not, same Error there, Blanks after 2sek

**Comment by offline4ever** [comment]
@ricjuhnl @sgilissen @llabusch93 

I am also on Debian 12 and have the Flatpak version installed, deactivating graphics acceleration solved it for me.

`flatpak override --nodevice=dri --user com.bitwarden.desktop`

No solution for the problem, but at least a workaround.

**Comment by flonix8** [comment]
I have a similar issue. Had the blanking issue, 2023.9.3 fixed it for me (on KDE 5.27), but now 2023.10.0 introduced a new issue, where the window goes blank except some very few elements. I can still see the cursor (and everything technically works, i.e. I can unlock the vault) but nothing else. Even devtools are mostly blank. So it's back to being unusable again.

@offline4ever Thank you so much for the workaround. It seems to work.

I'm getting more and more frustrated with the Bitwarden situation on Linux though...

**Comment by buvinghausen** [comment]
> I'm getting more and more frustrated with the Bitwarden situation on Linux though...

Yeah if you hit .333 in baseball you are a first ballot hall of famer.  When only 1/3rd of your releases work in software you need to find a new profession.

**Comment by larouxn** [comment]
Looks like a fresh desktop client release is out. Let's see if it addresses the blank issue.

https://github.com/bitwarden/clients/releases/tag/desktop-v2023.10.1

**Comment by gbcox** [comment]
2023.10.0 was working fine for me with Fedora 39, but when I upgraded to 2023.10.1 I got the white screen.  How do I access the previous versions to download?  Thanks!

**Comment by rqkeating** [comment]
Kubuntu 23.10, flatpak 1.14.4-2, Bitwarden 2023.10.1

I was able to get Bitwarden working by turning off the "GPU acceleration" for that flatpak.  I used Flatseal to make that change but I think there are other ways of setting flatpak permissions too.

**Comment by pogues** [comment]
Still seeing the same behaviour on Fedora39 with Bitwarden 2023.12.0 via flatpak (i.e. crashes before I can enter the password)
Tried removing the "GPU acceleration" but that did not fix.
Interestingly the AppImage I just installed with the same version is working

**Comment by sixerstyle** [comment]
> Still seeing the same behaviour on Fedora39 with Bitwarden 2023.12.0 via flatpak (i.e. crashes before I can enter the password) Tried removing the "GPU acceleration" but that did not fix. Interestingly the AppImage I just installed with the same version is working

I found the error in mine. after installation in fedora bitwarden didn't have background permission. try 

sudo flatpak permission-set background background com.bitwarden.desktop
