### ISSUE TITLE
Autofill on Groww.in inputs password into the search bar

### ISSUE THREAD

**Issue by sanketgarade** [bitwarden/clients#6658]
### Steps To Reproduce

0. Make a dummy entry (user-email and password) into your bitwarden vault for URL groww.in
1. Go to [groww.in](https://groww.in/)
2. Click on "Login/Register". This will open a dialogue where you need to enter the login email address.
3. Try autofill (cmd+shift+L). This will fill up the email field with your dummy email.
4. Click "continue"
5. In the same dialogue a new field appears for entering the password.
6. Try autofill again

### Expected Result

The password should get autofilled into the "password" field below the email field.

### Actual Result

The password gets autofilled into the search bar at the top and not in the "password" field.

### Operating System

macOS

### Web Browser

Brave

### Browser Version

1.58.137 Chromium: 117.0.5938.153 (arm64)

### Build Version

2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by jprusik** [comment]
Hi @NovaSilentium we've pushed a lot of changes to our autofill logic since this issue was initially reported. I believe we solved the search fill for this page previously, but we're no longer able to test the exact login flow you describe as it now requires a pre-qualified email. Consequently, I'm closing this issue for now, but can reopen it for any actionable concerns.

**Comment by sanketgarade** [comment]
The issue still exists, but is slightly different now, as mentioned below. The steps to reproduce are the same.

**Actual Result**

~~The password gets autofilled into the search bar at the top and not in the "password" field.~~
The screen goes back to the one mentioned in step 3. (Enter email screen).

**Comment by jprusik** [comment]
> The issue still exists, but is slightly different now, as mentioned below. The steps to reproduce are the same.
> 
> **Actual Result**
> 
> ~The password gets autofilled into the search bar at the top and not in the "password" field.~ The screen goes back to the one mentioned in step 3. (Enter email screen).

I think this may be the normal functionality on the site. If I disable Bitwarden for the domain I get the same behaviour:

https://github.com/user-attachments/assets/c60ccec7-5eec-4ed7-912c-e30ae9bfd55e
