### ISSUE TITLE
punycode module deprecated message

### ISSUE THREAD

**Issue by mphillippiAPG** [bitwarden/clients#6689]
### Steps To Reproduce

from terminal on macOS, run any `bw` command:

bw --version

### Expected Result

should only provide the version:

2023.9.1

### Actual Result

shows a deprecation warning for punycode in node:

(node:2299) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2023.9.1

### Screenshots or Videos

❯ bw --version
(node:2299) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2023.9.1

### Operating System

macOS

### Operating System Version

14.0 (23A344)

### Shell

Zsh

### Build Version

2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by hseeberger** [comment]
As a workaround you can use `bw ...  2>/dev/null` for the time being, because the noise is written to stderr.

**Comment by tyler-8** [comment]
Output of the `node --trace-deprecation` command

```
~ node --trace-deprecation /opt/homebrew/bin/bw
(node:32186) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:392:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:328:10)
    at loadBuiltinModule (node:internal/modules/helpers:101:7)
    at Module._load (node:internal/modules/cjs/loader:1001:17)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/opt/homebrew/Cellar/bitwarden-cli/2023.9.1/libexec/lib/node_modules/@bitwarden/cli/node_modules/psl/index.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
Usage: bw [options] [command]
```

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by RoboProgrammer69** [comment]
Downgrade node to 20.9.0 version!

**Comment by maion308** [comment]
solution that worked for me:
npm install punycode --save

and then in node_modules go to the directory tr46 > index.js

// Replace this:
const punycode = require('punycode');
// With this:
const punycode = require('punycode/');

basically just add a trailing forward slash

**Comment by lmerz1** [comment]
> As a workaround you can use `bw ... 2>/dev/null` for the time being, because the noise is written to stderr.

So I was able to do this for e.g. `bw sync`, but not for a command like `bw list items --search example.com` – which to my understanding seems to imply the latter command writes its regular output to stderr instead of stdout.

Am I right in assuming this as a bug? I am relatively new to shell/command line use, so please do correct me in case I am mistaken.

The reverse also seems to hold:

`bw sync 1>/dev/null` shows no output (expected); whereas

`bw list items --search example.com 1>/dev/null` still shows output (both the deprecation message mentioned in this issue, as well as the prompt for entering the master password).

Screenshot attached as a demonstration of this.

<img width="1448" alt="Screen Shot 2023-10-31 at 10 33 32" src="https://github.com/bitwarden/clients/assets/33632840/953c7196-447b-4517-9272-88814213c22f">

**Comment by TheUdK** [comment]
Temporary fix im using:

`NODE_OPTIONS="--no-deprecation" bw --version`

or add as an env var.
`export NODE_OPTIONS="--no-deprecation`

If you add the env var this will suppress all other depreciation warnings as well. Should probably be removed once this has been fixed.

**Comment by saidhammane** [comment]
> Temporary fix im using:
> 
> `NODE_OPTIONS="--no-deprecation" bw --version`
> 
> or add as an env var. `export NODE_OPTIONS="--no-deprecation`
> 
> If you add the env var this will suppress all other depreciation warnings as well. Should probably be removed once this has been fixed.

Where did you put that exactly?

**Comment by TheUdK** [comment]
> > Temporary fix im using:
> > `NODE_OPTIONS="--no-deprecation" bw --version`
> > or add as an env var. `export NODE_OPTIONS="--no-deprecation`
> > If you add the env var this will suppress all other depreciation warnings as well. Should probably be removed once this has been fixed.
> 
> Where did you put that exactly?

You can either:
- if you are using zsh put `export NODE_OPTIONS="--no-deprecation` it in `~/.zshrc` or `~/.zshenv` to make it persist in new sessions.
- put `export NODE_OPTIONS="--no-deprecation` in the terminal session to make it persist for this session.
- execute every bw command with the node option as 'prefix' `NODE_OPTIONS="--no-deprecation" bw --version`

**Comment by kschat** [comment]
I didn't want to set `--no-deprecation` globally since I use Node at work. My temp workaround was to make an alias for `bw`:

```bash
# Temp workaround to disable punycode deprecation logging to stderr
# https://github.com/bitwarden/clients/issues/6689
alias bw='NODE_OPTIONS="--no-deprecation" bw'
```

**Comment by Moulick** [comment]
Can we please get some love on this??

**Comment by Hinton** [comment]
Hi everyone,

This seems to be caused by a transient dependency of `jsdom` which is required by several features of the CLI. Unfortunately this means we don't have a good way of resolving this until the dependency is updated.

In the meanwhile you can avoid the error by using the distributed version of the CLI from our website, by downgrading node or by passing in the `--no-deprecation` flag.

**Comment by luckydonald** [comment]
Related Issues: 
- https://github.com/jsdom/jsdom/issues/3613
- https://github.com/lupomontero/psl/issues/296
- https://github.com/salesforce/tough-cookie/pull/346

**Comment by tolecnal** [comment]
Not that it is needed, as it has been confirmed by several, but here is another one with the issue on macOS 14.3.1 running Node v21.6.2.

For the time being, I have added an alias per @kschat suggestion, which solves it for me until it has been resolved upstream.

**Comment by valorisa** [comment]
> solution that worked for me: npm install punycode --save
> 
> and then in node_modules go to the directory tr46 > index.js
> 
> // Replace this: const punycode = require('punycode'); // With this: const punycode = require('punycode/');
> 
> basically just add a trailing forward slash

Hello,

Could you please explain in detail this part _'and then in node_modules go to the directory tr46 > index.js'_ ? Thanks.

**Comment by Servinjesus1** [comment]
To keep the latest version and remove the error messasge, find your installation of `bw`:
```
realpath $(which bw)
```
then go there and up a few directories till you get to the directory with `build/`, `node_modules/`, and `package*.json` files. This is a node project, so run

```
npm install punycode --save
```

to install the "userland" version of punycode.
Then run

```
find . -type f -exec grep -H "require(.*punycode" {} \;
```

to find all the sub-dependencies which require punycode. As @maion308 suggested, making these
```
require('punycode/')
```

calls the right version. In this latest version ( 2024.6.0 ) I had to change a few subdependencies until the error went away. Notably I think it's still the `tr46` package that's the problem: it's just now a dependent of `node-fetch` whose version of `tr46` now also needs updating to `punycode/` on top of `bw-cli`'s dependency on the package.

**Comment by palaueb** [comment]
Hello, for me it was file `./node_modules/node-fetch/node_modules/whatwg-url/lib/url-state-machine.js`, changing to require('punycode/') fixed the issue. 

Also changed:
- ./node_modules/psl/index.js
- ./node_modules/node-fetch/node_modules/tr46/index.js

Thanks!

**Comment by jzadra** [comment]
This just started occurring for me.

bw cli: 2024.6.0
macOS Sonoma 14.5

**Comment by gsoneill** [comment]
I'm also having this issue

bw cli: 2024.6.1
macOS: Sonoma 14.5 (23F79)

**Comment by kniziol** [comment]
Result from the `Copy Last Error`:
```
(node:36881) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Invalid master password.
```
The master password is 100% correct. I've copied and pasted it to avoid typos.

Do you have any ideas on when it will be solved? 🙄

**Comment by ckujau** [comment]
For me it was editing 4 files to get rid of that warning:
```
$ cd $(dirname $(readlink -f $(which bw)))/../../
$ grep -r 'require("punycode")' .
./cli/node_modules/node-fetch/node_modules/whatwg-url/lib/url-state-machine.js:const punycode = require("punycode");
./cli/node_modules/node-fetch/node_modules/tr46/index.js:var punycode = require("punycode");
./cli/node_modules/tr46/index.js:const punycode = require("punycode");
./cli/node_modules/tough-cookie/lib/cookie.js:const punycode = require("punycode");
```

Replace all those with `punycode/` [as suggested](https://github.com/bitwarden/clients/issues/6689#issuecomment-1786252068) (and [install the punycode module locally](https://github.com/mathiasbynens/punycode.js?tab=readme-ov-file#installation))  and the warnings are gone.

**Comment by rojosinalma** [comment]
It's almost 1 year after the first acknowledgement of this issue and there's still no official solution. What's the current status, is there any intentions of fixing it or giving a reasonable timeline? @sammbw

**Comment by djsmith85** [comment]
@rojosinalma As @Hinton has previously [mentioned](https://github.com/bitwarden/clients/issues/6689#issuecomment-1961086814) this is an upstream issue:
> Hi everyone,
> 
> This seems to be caused by a transient dependency of `jsdom` which is required by several features of the CLI. Unfortunately this means we don't have a good way of resolving this until the dependency releases a new version.
> 
> In the meanwhile you can avoid the error by using the distributed version of the CLI from our website, by downgrading node or by passing in the `--no-deprecation` flag to `NODE_OPTIONS`.

**Comment by valorisa** [comment]
> For me it was editing 4 files to get rid of that warning:
> 
> ```
> $ cd $(dirname $(readlink -f $(which bw)))/../../
> $ grep -r 'require("punycode")' .
> ./cli/node_modules/node-fetch/node_modules/whatwg-url/lib/url-state-machine.js:const punycode = require("punycode");
> ./cli/node_modules/node-fetch/node_modules/tr46/index.js:var punycode = require("punycode");
> ./cli/node_modules/tr46/index.js:const punycode = require("punycode");
> ./cli/node_modules/tough-cookie/lib/cookie.js:const punycode = require("punycode");
> ```
> 
> Replace all those with `punycode/` [as suggested](https://github.com/bitwarden/clients/issues/6689#issuecomment-1786252068) (and [install the punycode module locally](https://github.com/mathiasbynens/punycode.js?tab=readme-ov-file#installation)) and the warnings are gone.



> For me it was editing 4 files to get rid of that warning:
> 
> ```
> $ cd $(dirname $(readlink -f $(which bw)))/../../ or $ realpath $(which bw)
> $ grep -r 'require("punycode")' .
> ./cli/node_modules/node-fetch/node_modules/whatwg-url/lib/url-state-machine.js:const punycode = require("punycode");
> ./cli/node_modules/node-fetch/node_modules/tr46/index.js:var punycode = require("punycode");
> ./cli/node_modules/tr46/index.js:const punycode = require("punycode");
> ./cli/node_modules/tough-cookie/lib/cookie.js:const punycode = require("punycode");
> ```
> 
> Replace all those with `punycode/` [as suggested](https://github.com/bitwarden/clients/issues/6689#issuecomment-1786252068) (and [install the punycode module locally](https://github.com/mathiasbynens/punycode.js?tab=readme-ov-file#installation)) and the warnings are gone.

**Comment by chipschipschips** [comment]
BitWarden, if you're not interested enough in resolving[1] this properly, and it's otherwise harmless, and one recommended workaround includes passing the `--no-deprecation` flag to `NODE_OPTIONS`, then why not set that environment variable in the CLI itself?

For example: 

```diff
@@ -1,4 +1,4 @@
-#!/usr/local/opt/node/bin/node
+#!/usr/bin/env NODE_OPTIONS=--no-deprecation /usr/local/opt/node/bin/node
```

You can then revert this once `jsdom` releases a new version.

[1] Eg: chasing this up with `jsdom`

**Comment by valorisa** [comment]
I scrupulously followed the instructions provided by ckujau and now I no longer have the warnings of depreciation of the 'punycode' module


![Capture d’écran 2024-09-19 à 12 24 41](https://github.com/user-attachments/assets/125726e5-9814-4f63-a337-b11f8f04e8ee)
![Capture d’écran 2024-09-19 à 12 25 22](https://github.com/user-attachments/assets/5da7a63f-6ed4-4a04-a31f-3d7ebb484a12)

**Comment by andrew-chang-dewitt** [comment]
For everyone tracking this:

Looks like this has been resolved in https://github.com/jsdom/jsdom/pull/3776, included in [v 25.01 release](https://github.com/jsdom/jsdom/releases/tag/25.0.1) as of 2024-09-22.  Since then, you might notice above here BW's upgraded to v25 in #10742, merged to main 3 days ago & included in the [browser](https://github.com/bitwarden/clients/releases/tag/browser-v2024.10.0) & [web](https://github.com/bitwarden/clients/releases/tag/web-v2024.10.0) version 2024.10.0 releases. No matching CLI release yet though.

**Comment by DJAlPee** [comment]
New CLI version released today (updated with brew on my device), but still having this issue:
```
✗ bw --version
(node:68370) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2024.10.0
```

**Comment by andrew-chang-dewitt** [comment]
I still get the same deprecation warning even when I built bitwarden cli from source at the latest commit on main.

**Comment by andrew-chang-dewitt** [comment]
Did some cursory digging, looks like this is still upstream&mdash;this time with `node-fetch@2.x`:

Running bw w/ deprecation tracing outputs the following:

```
$ NODE_OPTIONS="--trace-deprecation" bw --version
(node:41464) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:398:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:337:10)
    at loadBuiltinModule (node:internal/modules/helpers:96:7)
    at Module._load (node:internal/modules/cjs/loader:1037:17)
    at Module.require (node:internal/modules/cjs/loader:1271:19)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/home/andrew/.nvm/versions/node/v22.2.0/lib/node_modules/@bitwarden/cli/node_modules/node-fetch/node_modules/whatwg-url/lib/url-state-machine.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1434:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
2024.10.0
```

Per `node-fetch`, version 2.x can't be updated to latest version of `whatwg-url` due to minimum supported version of Node is v18 & `node-fetch@2.x` supports Node versions all the way back to v4. See [node-fetch/node-fetch/#1793](https://github.com/node-fetch/node-fetch/pull/1793#issuecomment-1839050150). Maintainer recommends (see proceeding PR comment link) switching to `node-fetch@3.x` or native fetch in Node versions 18+.

`bitwarden/clients` pins node-fetch to 2.6.12 in [package.json](https://github.com/bitwarden/clients/blob/dfa7509c8eab3f72e9ab25dc73b6e5a33047dd2e/package.json#L191C4-L191C28).

**Comment by andrew-chang-dewitt** [comment]
> Did some cursory digging, looks like this is still upstream—this time with `node-fetch@2.x`:
> ...

Should this issue be reopened, or is it better if I file a new issue for this new cause?

**Comment by djsmith85** [comment]
Thank you @andrew-chang-dewitt for the investigation and identifying another upstream issue. I'll go ahead and re-open this.

**Comment by andrew-chang-dewitt** [comment]
Just in case anyone else is looking at resolving this w/ a PR like I was, it seems like the following issues could be blocking a resolution:

1. #10606: `node-fetch@v3.x` requires ESM support

    1. I explored importing `node-fetch@3.x` using the `const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));` trick (as [suggested by the `node-fetch` team](https://github.com/node-fetch/node-fetch/blob/main/docs/v3-UPGRADE-GUIDE.md#converted-to-es-module)), but quickly ran into a lot more issues than I have the time to spend on resolving this myself
        -  I tried various versions of `transformIgnorePatterns: ["node_modules/(?!node-fetch)"]` in various `jest.config.js` files, but every time the tests at src/service-container/service-container.spec.ts failed to parse ESM syntax in `node-fetch`
        - Also tried converting `./babel.config.json` to `./babel.config.js` as suggested in [a few](https://stackoverflow.com/a/54656593) [different issues](https://github.com/jestjs/jest/issues/6229#issuecomment-403539460), but still no success

2. An alternative to (1) could be switching to [native `fetch`](https://nodejs.org/docs/latest/api/globals.html#fetch), but this would require bumping the entire project's node version to 21+ (likely 22+ 21 went out of maintenance support earlier this year)&mdash;a change I assume the team would want to look at themselves instead of some random outsider.

**Comment by evgenykushnarenko** [comment]
> For me it was editing 4 files to get rid of that warning:
> 
> ```
> $ cd $(dirname $(readlink -f $(which bw)))/../../
> $ grep -r 'require("punycode")' .
> ./cli/node_modules/node-fetch/node_modules/whatwg-url/lib/url-state-machine.js:const punycode = require("punycode");
> ./cli/node_modules/node-fetch/node_modules/tr46/index.js:var punycode = require("punycode");
> ./cli/node_modules/tr46/index.js:const punycode = require("punycode");
> ./cli/node_modules/tough-cookie/lib/cookie.js:const punycode = require("punycode");
> ```
> 
> Replace all those with `punycode/` [as suggested](https://github.com/bitwarden/clients/issues/6689#issuecomment-1786252068) (and [install the punycode module locally](https://github.com/mathiasbynens/punycode.js?tab=readme-ov-file#installation)) and the warnings are gone.

Its work for me! 🚀

**Comment by bcdady** [comment]
> Module `punycode` is deprecated since Node.js 21 petkaantonov/urlparser#20

Same for me. I've just uninstalled and reinstalled bw directly via npm and still seeing this error message, presumably related to `node-fetch@2.x`

**Comment by valorisa** [comment]
> > Module `punycode` is deprecated since Node.js 21 [petkaantonov/urlparser#20](https://github.com/petkaantonov/urlparser/issues/20)
> 
> Same for me. I've just uninstalled and reinstalled bw directly via npm and still seeing this error message, presumably related to `node-fetch@2.x`

Have you try this : $ cd $(dirname $(readlink -f $(which bw)))/../../
$ grep -r 'require("punycode")' .
./cli/node_modules/node-fetch/node_modules/whatwg-url/lib/url-state-machine.js:const punycode = require("punycode");
./cli/node_modules/node-fetch/node_modules/tr46/index.js:var punycode = require("punycode");
./cli/node_modules/tr46/index.js:const punycode = require("punycode");
./cli/node_modules/tough-cookie/lib/cookie.js:const punycode = require("punycode");

**Comment by vicke4** [comment]
Updating to version `2025.1.2` fixed the issue for me.

Steps to fix the issue on Mac:

```zsh
brew update # updates your local brew formulae
brew install bitwarden-cli # updates bitwarden-cli to the latest version
```

**Comment by bcdady** [comment]
Agree. On Ubuntu and MacOS, I'm not seeing this symptom any longer from bw CLI version `2025.1.2`

**Comment by k-bx** [comment]
```
➜  ~ bw --version
(node:54948) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2025.1.2
```

**Comment by andrew-chang-dewitt** [comment]
looks like it might be fixed depending on your node version. 

with node 22 & @bitwarden/cli 2025.1.2, I still get the error:

```
andrew@LAZARUS: ~
$ bw --version
(node:39120) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2025.1.2

andrew@LAZARUS: ~
$ node --version
v22.13.1
```

however, when I upgrade to node 23, I no longer see the error:

```
andrew@LAZARUS: ~
$ bw --version
2025.1.2

andrew@LAZARUS: ~
$ node --version
v23.7.0
```

these results were seen on ubuntu 24.04 & WSL 2.3.

```
andrew@LAZARUS: ~
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

andrew@LAZARUS: ~
$ wsl.exe --version
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.22631.4751
```

**Comment by andrew-chang-dewitt** [comment]
> looks like it might be fixed depending on your node version.
> ...

Interestingly enough, it looks like both @bitwarden/cli [v2024.12.0](https://github.com/bitwarden/clients/blob/cli-v2024.12.0/package-lock.json#L27819) & [v2025.1.2](https://github.com/bitwarden/clients/blob/cli-v2025.1.2/package-lock.json#L27485) still require the same punycode version.

Inspecting both the bw versions installed in my node v23.x & v22.x installations (using nvm), they both still installed node-fetch 2.6.12 & both of those still depend on whatwg-url 5.0.0, the transitive dep that required punycode [last time I traced this](https://github.com/bitwarden/clients/issues/6689#issuecomment-2432650297). 

Not sure why node v23 seems to resolve this, given this apparent lack of changes.

**Comment by phuongthuan** [comment]
> Updating to version `2025.1.2` fixed the issue for me.
> 
> Steps to fix the issue on Mac:
> 
> brew update # updates your local brew formulae
> brew install bitwarden-cli # updates bitwarden-cli to the latest version

This issue solved my problem 🚀

**Comment by baodrate** [comment]
This is still an issue in cli v2025.12.1 with node v25

```
~ % bw -v
(node:27934) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2025.12.1

~ % head -n1 =bw
#!/opt/homebrew/opt/node/bin/node

~ % /opt/homebrew/opt/node/bin/node -v
v25.5.0
```

**Comment by ghost** [comment]
created #18741 to track new version
