### ISSUE TITLE
Error while adding passkey on porkbun.com: Cannot read properties of undefined (reading 'authenticatorAttachment')

### ISSUE THREAD

**Issue by zizzfizzix** [bitwarden/clients#6769]
### Steps To Reproduce

1. Go to https://porkbun.com/account logged-in
2. Scroll down to '2FA - Security Key'
3. Click on 'Register a Key'
5. Dismiss the warning alert
6. See the TypeError alert

### Expected Result

Bitwarden extension passkey creation window opened

### Actual Result

```
TypeError: Cannot read properties of undefined (reading 'authenticatorAttachment')
    at chrome-extension://nngceckbapebfimnlniiiahkandclblb/content/fido2/page-script.js:16891:171
    at Generator.next (<anonymous>)
    at chrome-extension://nngceckbapebfimnlniiiahkandclblb/content/fido2/page-script.js:16828:71
    at new Promise (<anonymous>)
    at page_script_awaiter (chrome-extension://nngceckbapebfimnlniiiahkandclblb/content/fido2/page-script.js:16824:12)
    at navigator.credentials.create (chrome-extension://nngceckbapebfimnlniiiahkandclblb/content/fido2/page-script.js:16889:62)
    at registerCredential (https://porkbun.com/js/webauthnregister.js?v=PrettyTrees_0.353:35:44)
```

### Additional Context

No problem adding an iCloud Keychain passkey earlier.

### Operating System

macOS

### Operating System Version

14.1

### Web Browser

Chrome

### Browser Version

119

### Build Version

2023.10

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by tcoenraad** [comment]
Same on Safari, then with `undefined is not an object (evaluating '_b.authenticatorSelection.authenticatorAttachment')`. Also happens on simplelogin.io.

**Comment by agelwarg** [comment]
I had actually contacted Porkbun support and sent them this video...figured I might as well attach here as well.

https://github.com/bitwarden/clients/assets/392423/edf716bb-2e5f-4a2b-8cf4-325859c2e8e7

**Comment by edward93** [comment]
> I'm having something of a similar issue myself when implementing my own fido2 auth. As soon as the browser calls `navigator.credentiale.create()` I get the following error (thrown from the extension):
> 
> ```
> cannot read properties of null (reading 'endswith')
> ```

Just an update, I do not observe this anymore in chrome! Could've been a browser issue!

**Comment by coroiu** [comment]
@edward93 there was a bug preventing `localhost` from working properly, it was fixed in 2023.10.2 :)

**Comment by phoropter** [comment]
I'm still getting this behavior on 2023.10.2 in Firefox and Brave for porkbun. With firefox the error is slightly different; `_b.authenticatorSelection is undefined`

**Comment by oborseth** [comment]
Looks like Bitwarden is not checking to make sure authenticatorSelection is defined before attempting to access it. We've rolled out a change on our site that should fix this issue.

**Comment by agelwarg** [comment]
Looks like the change on the Porkbun site has fixed this as I have been able to successfully register a Passkey in Bitwarden -- fwiw, my Chrome browser extension is `2023.12.0`
