### ISSUE TITLE
"No supported key algorithms were found

### ISSUE THREAD

**Issue by agelwarg** [bitwarden/clients#6804]
### Steps To Reproduce

1. Go to https://accounts.zoho.com/home#multiTFA/modes
2. Scroll down to Passkey
3. Click on "Set up Now"
4. Give the new passkey a name and click "Next"

### Expected Result

New Passkey added

### Actual Result

Failure

### Screenshots or Videos

<img width="381" alt="image" src="https://github.com/bitwarden/clients/assets/392423/886e4627-2e96-4aac-b3af-4f9c80841fb7">

### Operating System

macOS

### Operating System Version

Sonoma 14.1

### Web Browser

Chrome

### Browser Version

118.0.5993.117

### Build Version

2023.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by micaelvaleri** [comment]
Same with Bitwarden add-on Version: 2023.10.1 on Brave Version 1.60.110 Chromium: 119.0.6045.105 on Linux Mint 21.1 Vera

**Comment by Neonwarden** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by micaelvaleri** [comment]
Kayak.com gives a similar error "It looks like your current browser does not support passkeys. You can still add a passkey to your KAYAK account from another device."

**Comment by Neon-44** [comment]
same on Firefox and Mangadex.org

but i am really hyped we finally got Passkeys, big thanks to the Engineer Team. I really appreciate your work :):)

your work is totally worth the Price for Premium :):)

**Comment by vijay-prema** [comment]
I'm seeing the same issue with zoho, in Firefox on Ubuntu 2204.  Bitwarden passkeys works for other sites like github and Google. Only zoho has this issue so far.

**Comment by Zikinn** [comment]
Microsoft 365 Business Account (myaccount.microsoft.com) shows the same error, unable to add Bitwarden Passkey, strangely Outlook (Microsoft Personal Account) can add Bitwarden Passkey and FIDO2 Physical Key correctly.

**Comment by ocrete** [comment]
I'm seeing the same thing with our corporate keycloak instance.

**Comment by markesss** [comment]
I was just testing Keycloak with WebAuthn, and found that Keycloak JS is assembling the publicKey.publicKeyCredParams array as [{alg: "-7", type: "public-key" }], assembling the **alg** property as a string, instead of an integer.... 


When its passed through to Bitwarden (specifically, [_lib/common/src/vault/services/fido2/fido2-client.service.ts:115_](https://github.com/bitwarden/clients/blob/07e2731a2e9343833cdfb9bbae5ecddc97f8043e/libs/common/src/vault/services/fido2/fido2-client.service.ts#L115)) the key algorithms are filtered out because they're not matching a supported key algorithm {alg: -7, type: "public-key"}

Hope this helps save someone some time, I probably spent more time than I should have trying to figure out where the problem was, suspecting it was my configuration in Keycloak!

**Comment by Neon-44** [comment]
Soooo....

What are we going to do?

Are we going to try and parse the Strings or do we insist that the providers have to fix their side?

**Comment by markesss** [comment]
It looks like the browser native api handles both, otherwise none of these implementations would have made it to production even though they are technically incompatible…

For usability and adoption, Bitwarden should probably adapt its tests to handle string or integer values here. Even if it is a deviation from the standard, otherwise it would prevent Bitwardens passkey implementation from being adopted. 

Just my 2c of course

**Comment by foxt** [comment]
I think another problem is that if Bitwarden fails to parse the request it hard fails instead of passing it to the browser

**Comment by BluCobalt** [comment]
I have the same issue when trying to create a key on Oracle Cloud, on Windows. Opening a private browser tab (trying without bitwarden) makes it go through and it works.

**Comment by tuanson84uk** [comment]
![Screenshot 2024-03-07 093947](https://github.com/bitwarden/clients/assets/44844697/f495d197-d69b-40bb-8e56-909828b5e8a2)

The same happened when registering on OCI - Oracle Cloud Infrastructure.

**Comment by bohanyang** [comment]
Same for me on Oracle Cloud

**Comment by good-live** [comment]
Yeah im also facing issues on multiple sites. Would be great to have a fix from Bitwarden site. Especially because the bitwarden extension blocks use of some other passkey provider.

**Comment by ralstonba** [comment]
Status? #7832 hasn't received any feedback, what is preventing progress on this?

**Comment by supleed2** [comment]
I saw that a fix was supposedly merged, and it seems a new version has been released since then (which I am running, `2024.8.1`), but I'm still seeing this issue on Oracle Cloud Infrastructure like in https://github.com/bitwarden/clients/issues/6804#issuecomment-1982233352

Is this resolved with the other websites mentioned?

**Comment by xvyvx** [comment]
As mentioned above, this problem is still exists when enable passkey on zoho.com(2024.9.0 on chrome 128.0.6613.138).

**Comment by Camis** [comment]
In the latest version of  
browser-v2024.10.1

“Bug” has been corrected and you can now set Passkey to Zoho.

**Comment by agelwarg** [comment]
Confirmed working for Zoho.  FWIW, I'm still on v2024.10.0.  I don't know where any release notes are that would call out this particular bug, but nonetheless, it is now working...recently.

**Comment by agelwarg** [comment]
I went back and stepped through comparing the releases and it looks like this was fixed in v2024.9.1.

https://github.com/bitwarden/clients/compare/browser-v2024.9.0...browser-v2024.9.1

(Look for changes to apps/browser/src/autofill/fido2/utils/webauthn-utils.ts)

**Comment by tecosaur** [comment]
Hmm, I'm on 2024.10.1 and still not having any luck with Oracle Cloud, has anybody had a different experience?
