### ISSUE TITLE
Passkey login request not intercepted by BitWarden on LinkedIn.com

### ISSUE THREAD

**Issue by chrissv** [bitwarden/clients#7302]
### Steps To Reproduce

1. Logging in to LinkedIn.com using username/password, I went to "Settings" and "Sign in & Security" and created a passkey in BitWarden
2. I verified BitWarden shows a passkey stored for linkedin.com
3. Log out of LinkedIn
4. Go to LinkedIn login page: https://www.linkedin.com/login
5. Click "Sign in with a passkey"

### Expected Result

BitWarden pops up an offer to provide the passkey

### Actual Result

Windows Hello pops up an offer to provide a passkey. There are no indications of any errors (in the browser console window).

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/3324281/6bbe0276-2cb9-4c08-8299-bd3183cd544b)
LinkedIn login screen

=========================================

![image](https://github.com/bitwarden/clients/assets/3324281/e56ea43b-5680-4412-98a5-ee1208e3ebb2)
Windows Hello prompt which appears instead of BitWarden prompt

### Additional Context

I verified BitWarden passkeys work fine with passkeys.io

### Operating System

Windows

### Operating System Version

Version 10.0.19045 Build 19045

### Web Browser

Chrome

### Browser Version

Version 120.0.6099.71 (Official Build) (64-bit)

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by chrissv** [comment]
My BitWarden browser extension auto-updated to 2023.12.1. I re-tested this scenario and the issue is still present.

**Comment by SergeantConfused** [comment]
Hi @chrissv,

Thank you for your report. I was able to reproduce this behaviour and I have flagged it to our Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you again,

**Comment by FivesKodakumi** [comment]
Hi i have a nearly identical issue with an other Website/ Program Teleport. I can add the key with no problem but windows Hello shows up at the moment it should use the key stored in Bitwarden. You can contact me so i can give additional information to solve this bug

**Comment by Thibault2ss** [comment]
I have slightly different issue which I described in [issue 7436](https://github.com/bitwarden/clients/issues/7436), where Bitwarden's extension doesn't even intercept the call and prompt during passkey creation (not just passkey sign-in, but actual passkey creation).

Though the Additional context I mentioned in there may (or may not 🤷) be useful for that issue:

> Maybe something could help resolve: I have my own app where I use webauthn authentication, and I had the same issue of the bitwarden extension not prompting [...]. I had to remove the option mediation: 'required' for the Bitwarden extension to prompt when requesting a signin with the pass key using the `navigator.credentials.get()`.

**Comment by h44z** [comment]
> n there may (or may no

I have the same issue, creating passkeys on github.com does not trigger BitWarden. Instead it directly opens the browsers login window.

**Comment by chrissv** [comment]
I was updated to 2024.1.0 so I thought I would verify if this problem still exists.
This specific issue doesn't exist, but a new issue was discovered: #7545

**Comment by Thibault2ss** [comment]
If fixed my issue on github indeed 👍

**Comment by trmartin4** [comment]
We have not been able to replicate internally due to the nature of LinkedIn passkey feature availability.  However, due to the fact that the issue has been resolved with bug fixes included in `2024.1.0` I will close this issue and move efforts to looking at #7545.

**Comment by sitiom** [comment]
As of the latest version, this issue still persists on https://www.roblox.com/. I have created a separate issue at https://github.com/bitwarden/clients/issues/7456, but I was told that it was a duplicate of this one. Can someone please reopen my issue?

**Comment by vinayak19th** [comment]
> `2024.1.0` fixes my issue on github indeed 👍

It was fixed on windows for me but still exists on ubuntu
