### ISSUE TITLE
Apr 12 FF browser plugin update 2024.3.1 not displaying properly

### ISSUE THREAD

**Issue by Cactus8559** [bitwarden/clients#8769]
### Steps To Reproduce

1. Click on Browser Extension in Firefox

### Expected Result

Display entire Bitwarden extension (including the bottom (Tabs, Vault, Send, Generator, Settings).

### Actual Result

The bottom of the Bitwarden extension drop down is cut off or now shown  at all.  
*** see discussion in Bitwarden Community forums under the same title ("[Bug: Apr 12 FF browser plugin update 2024.3.1 not displaying properly](https://community.bitwarden.com/t/bug-apr-12-ff-browser-plugin-update-2024-3-1-not-displaying-properly/65759)").  Screen shots from users are shown there.

### Screenshots or Videos

See Bitwarden Community Forum 
Bug: Apr 12 FF browser plugin update 2024.3.1 not displaying properly](https://community.bitwarden.com/t/bug-apr-12-ff-browser-plugin-update-2024-3-1-not-displaying-properly/65759)

### Additional Context

See Bitwarden Community Forum 
Bug: Apr 12 FF browser plugin update 2024.3.1 not displaying properly](https://community.bitwarden.com/t/bug-apr-12-ff-browser-plugin-update-2024-3-1-not-displaying-properly/65759)

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

124.0.2

### Build Version

2024.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Tipoff4317** [comment]
Also, see https://community.bitwarden.com/t/no-option-for-pin-code/65951/4 , the OP of that thread reported that Zooming out will show the bottom menus entirely and reliably.

**Comment by Greenderella** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by Reeceeboii** [comment]
Same behaviour for me on Chrome v125.0.6422.142. Extension version 2024.4.2.

The navigation bar is off the bottom and I need to scroll to reach it.
![image](https://github.com/bitwarden/clients/assets/42159320/97df0e16-a65b-492d-a301-3c4ab83bfa4c)

**Comment by JCoil** [comment]
Same again for me on Chrome 125.0.6422.142
Extension 2024.5.2

Same behaviour on all the tabs. It's especially problematic on tabs with more content such as Vault and Settings because those have their own inner scroll views which means you have to grab the outer scrollbar directly or scroll all the way up/down to view the header/footer.

Not sure exactly when the behaviour started, but I have noticed it for at least a couple of months.

I have Chrome set to a default zoom of 110% which may or may not be relevant.

<img src="https://github.com/bitwarden/clients/assets/11196596/a65fa49f-36be-4725-9891-3c4b708a8269" width="300"/>

<img src="https://github.com/bitwarden/clients/assets/11196596/cf4d6af4-957a-43fe-b802-3b20683c97fa" width="300"/>

**Comment by JCoil** [comment]
Aha!
Just checked by changing my Chrome default page zoom in Settings>Appearance to 100%, then restarting Chrome.

Reopening Bitwarden extension and it now displays as expected with no outer scrollbar and the tab footer visible.

Just changing the page zoom without restarting does _not_ fix the issue, so it seems that it very likely has something to do with the default zoom in Settings

**Comment by Reeceeboii** [comment]
> Aha! Just checked by changing my Chrome default page zoom in Settings>Appearance to 100%, then restarting Chrome.
> 
> Reopening Bitwarden extension and it now displays as expected with no outer scrollbar and the tab footer visible.
> 
> Just changing the page zoom without restarting does _not_ fix the issue, so it seems that it very likely has something to do with the default zoom in Settings.
> 
> Changing back to my normal 110% default zoom and restarting and the issue has reappeared.

It's a bummer that you can't have a non-100% default zoom. I have mine to 125% by default because otherwise everything is too small on a 4k screen. This definitely needs fixing.

**Comment by gblues** [comment]
I have been dealing with this in Firefox on Windows 11.

* Scale is set to 300% in OS Display Settings
* Browser is maximized
* Menu bar is visible
* Bookmarks bar is visible
* Browser zoom is at 100%

In this setup, the bottom menu bar is cut off, I can just barely navigate it, but clearly the window size math ain't mathing properly.

![image](https://github.com/user-attachments/assets/eb6a5c5b-f679-4183-8ca1-1b4fb3fff2d1)

If you'll notice the rounded corners at the bottom, we can see the overall dialog is the right size--i.e. it's not just going down off the bottom of the screen.

**Comment by shanghaiknight** [comment]
Is anything being done to resolve this bug?

**Comment by trmartin4** [comment]
@Cactus8559 we have released a new browser extension UI with the `2024.12.0` extension release, during which we believe we have addressed this issue.

Can you confirm that the menu is no longer cut off?

Thank you for your patience as we addressed this.

**Comment by gblues** [comment]
Speaking only for myself, I can confirm that the bottom menu bar is no longer cut off. Thank you!

**Comment by ericswpark** [comment]
I am still experiencing the bottom bar getting cut off on the latest extension version (2024.12.3):

![image](https://github.com/user-attachments/assets/dce6b5bb-606e-4db7-961a-a1f4da456ec3)

When I open the extension in a pop-up window this does not happen:

![image](https://github.com/user-attachments/assets/d354ce4c-c5eb-4b30-9b85-e7d05a8bd0ca)

**Comment by lama-development** [comment]
I have my browser default scaling set to **110%** and can confirm the bottom bar is still getting cut off (Bitwarden `2024.12.4` with Microsoft Edge)
  
![image](https://github.com/user-attachments/assets/bf90e3a5-3ff8-4386-a86e-b64f3bb7f6f6)

**Comment by shanghaiknight** [comment]
![Screenshot 2025-01-07 092831](https://github.com/user-attachments/assets/9d84f413-7088-4154-b413-3c443aa62c56)
The issue still happens on smaller screens, if any amount of Zoom is used.  This especially happens if display zoom is used in conjunction with browser zoom.  I have older clients who cannot see their screens and this happens to them.

A concerted effort to fix this would be deeply appreciated. We're a business customer, and this affects key individuals in our organization.  If it remains unfixed, we'll soon have to find another provider.

**Comment by vleague2** [comment]
@bwbug The original report for this issue does not mention zoom, so if the original problem is still present in 2025.1.0, I plan to leave this issue open to be solved separately. It is possible that the height calculation logic used to solve the zoom/double scrollbar could fix problems in other situations where vertical space is limited, but I have not tested those scenarios.

**Comment by francescotaioli** [comment]
I have the same issue too.

**Comment by danielleflinn** [comment]
Closing as duplicate of [Bottom bar not visible #12872](https://github.com/bitwarden/clients/issues/12872)

**Comment by ericswpark** [comment]
@danielleflinn perhaps #12872 should have been marked as a duplicate of this bug, instead of the other way around, seeing that the linked bug was filed only this January. The current bug thread has persisted since April of last year.

**Comment by willmartian** [comment]
Hi all. See my comment [here.](https://github.com/bitwarden/clients/issues/12872#issuecomment-2861702938) In short, we believe this is [a Firefox bug.](https://bugzilla.mozilla.org/show_bug.cgi?id=1748411) 😞
