### ISSUE TITLE
Firefox plugin opens browser side panel (sidebar) on vault lock

### ISSUE THREAD

**Issue by thibaut-decherit** [bitwarden/clients#900]
My Firefox side panel defaults to this plugin.
Since last update (or so), everytime the vault is being locked (either manually or thanks to the auto lock feature) it will open the side panel by itself to display the plugin.

It happens a couple seconds after lock, even if I didn't use the side panel during this session.
It doesn't happen if side panel is set to display something else (bookmarks, history...)

When it happens the red padlock disappears briefly from the plugin icon, like when the vault is unlocked (even if side panel is not set to display Bitwarden)

Bug encountered on Windows and Linux.

Steps to reproduce:

- Log in, either throught plugin's widget (not sure if it's the right word) or side panel
- Lock vault (and close side panel if you manipulated the vault through it)
- Wait for around 7 seconds

**Comment by kspearrin** [comment]
This seems to happen because we now call `browser.runtime.reload()` shortly after the extension is locked to make sure memory is properly purged. It's a shame that Firefox re-opens the sidebar when this occurs, since that definitely is going to be annoying. Opera doesn't seem to do this with their sidebar.

Maybe we can switch to `window.reload()` instead.

**Comment by GabrielDuarteM** [comment]
@kspearrin I'm also having a very similar problem but in Opera. When the vault is locked, either automatically or manually, the extensions bar (which normally leave hidden) is automatically shown, so I have to manually hide it again, which is very annoying.

Top left corner shows problem
![image](https://user-images.githubusercontent.com/7675500/55552494-c7b80d80-56dd-11e9-848a-5c6a472037b8.png)

I think by the description of this issue that both are probably caused by the same thing, but just in case, do you want me to file another bug?

**Comment by kspearrin** [comment]
Should be fixed next version for both Opera and Firefox

**Comment by Jourond** [comment]
This issue is still happening for me. On each lock the sidebar opens back up and I can't disable it.

MacOS
Firefox 66.0.5 (64-bit)
Bitwarden Extension 1.39.3

**Comment by kspearrin** [comment]
@Jourond It is fixed in the next version.

**Comment by plavirudar** [comment]
> 
> 
> @Jourond It is fixed in the next version.

When can we expect an update to the next version? The Firefox addon https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/ seems to have been updated on Mar 14 (over 3 months ago). Is there any place that we can download a more recent build?

**Comment by Crocmagnon** [comment]
I guess not, the release page on GitHub doesn't list any more recent release : https://github.com/bitwarden/browser/releases

**Comment by DanJRinehart** [comment]
This needs a second pass. The only thing stopping me from using Firefox right now is the fact that this add on is causing that sidebar to load every time it locks. This was not fixed yet.

**Comment by Shaltz** [comment]
Same here, I'm on firefox 86.0, and every time I launch FF, the BW sidebar loads up on EVERY window...
Thats quite annonying... any ETA when that should really be fixed ??

**Comment by itsayellow** [comment]
Can this bug be reopened?  I just installed the bitwarden plugin on the newest firefox and every time my vault times out it opens every sidebar on every firefox window.  Very frustrating.

**Comment by eliykat** [comment]
Reopened and queued for reproduction/triage. Can you please provide your OS, Firefox and Bitwarden versions @Shaltz and @itsayellow?

**Comment by itsayellow** [comment]
OS: MacOS Big Sur 11.2.3
Firefox: 86.0.1
Bitwarden plugin: Version: 1.49.1

thanks for reopening!

**Comment by beytun** [comment]
I have the same issue.
OS: MacOS Catalina 10.15.7
Firefox: 88.0b2 (64-bit)
Bitwarden plugin: 1.49.1

**Comment by itsayellow** [comment]
To add more information, I haven't seen bitwarden open my sidebar again.  It's possible it only happened the first time the vault timed out after I installed it.  (My current versions: Firefox 87.0, Bitwarden 1.49.1)

**Comment by Allesuah** [comment]
Hi,

I have just installed the plugin and Im getting the same error.

OS: Windows 10 (1904.867)
Firefox: 87.0
Bitwarden plugin: 1.49.1

**Comment by n0valis** [comment]
I have the same problem on
Debian Bullseye
Firefox 91.5.0esr 64-Bit
Bitwarden 1.55.0

**Comment by JJ-White** [comment]
Same issue here, sidebar opens with Bitwarden on every new Firefox window. System specs:

Ubuntu 21.10
Mozilla Firefox 99.0.1
Bitwarden plugin 1.57.0

The workaround mentioned in the linked issue (#1991) where you switch to another sidebar tab (e.g. bookmarks), close the sidebar, and exit Firefox with Ctrl + Q seems to have worked for me.

**Comment by atjbramley** [comment]
Hi @thibaut-decherit ,

I attempted to reproduce your issue and was unable to do so using the Bitwarden release 2023.9.2 on macOS 14.1 and Firefox 118.0.2.

I suspect that this issue was fixed by the code changes referenced above.

We use GitHub issues as a place to track bugs and other development related issues. If this issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

The issue here will be closed.

Thanks!

**Comment by eirnym** [comment]
Same here: macOS Ventura 13.6
Firefox 119.0
Bitwarden plugin 2023.4.3

**Comment by atjbramley** [comment]
Hi @eirnym, can you please update to the latest version of the Bitwarden plugin.
If the issue persists, please contact support using the link above and we'll work with you to see if this can be reproduced.
We look forward to receiving your email with our Support Team.

**Comment by eirnym** [comment]
You presumably fixed it in 2019, then in 2021. Why issue persists?

**Comment by eirnym** [comment]
This is the latest one. This way of nudging is the worse of any possible.


<img width="637" alt="Zrzut ekranu 2023-10-27 o 09 35 40" src="https://github.com/bitwarden/clients/assets/485399/1331f300-14ef-469e-a449-9be350ccd1ba">

**Comment by eirnym** [comment]
Please, reopen the issue

**Comment by Greenderella** [comment]
Hello,

We've thoroughly investigated this issue across multiple platforms, including macOS, Windows, and Linux, and have been unable to reproduce it. 

If you're still experiencing this problem after performing a clean installation of the browser extension by removing any leftover data ([instructions here](https://bitwarden.com/help/data-storage/#on-your-local-machine)), you can also try refreshing your Firefox profile using [Mozilla's instructions](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings).

If your issue persists, please don't hesitate to reach out to us through our [contact form](https://bitwarden.com/contact/), so we can continue troubleshooting.

The issue will remain closed.

Thank you!

**Comment by eirnym** [comment]
There's a few interesting details found during our local investigation:

* We use self-hosted BitWarden
* Default lock mode is "On browser restart" (translated from "Po restarcie przeglądarki"
* I don't know the rest of settings on the server.
* I have 5+ opened Firefox _windows_

After I clean **all** browser settings (close firefox, literally `rm -rf firefox-profile-folder`, create new profile and install Bitwarden plugin) and create a new account, I can reproduce the issue.

The issue persists until I change lock mode. After I set plugin lock mode to "Never" ("Nigdy") and I close all previously opened sidebars and then restart Firefox, then on that specific account I can't reproduce the issue. Closed sidebars persist even I log out and log in back.


I believe this issue is too hard to reproduce and test because it needs very specific conditions (like first-time login).

PS: I don't know if there's a setting to show this plugin sidebar by default or not.
