### ISSUE TITLE
Field undefined when trying to listen on it

### ISSUE THREAD

**Issue by noefleury** [bitwarden/clients#9175]
### Steps To Reproduce

When navigating through views in some apps, this bug could happen.

More precisely, when an element appears and the url is changing at the same time (works in both orders).

It could be for example be triggered by a button.

```html
<!-- trigger.html -->

<button onclick="triggerBug()">test</button>

<input type="password" style="display: none" id="example">

<script>

    function triggerBug() {
        document.getElementById('example').style.display = 'inline-block';
        window.history.pushState({}, '', 'triggered');
    }

</script>
```

### Expected Result

Just to don't throw an error.

### Actual Result

In file `bootstrap-autofill-overlay.js:4267 `
```
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'viewable')
    at CollectAutofillContentService.<anonymous> (bootstrap-autofill-overlay.js:4267:53)
    at Generator.next (<anonymous>)
    at fulfilled (bootstrap-autofill-overlay.js:4111:58)
```

### Additional Context

Broken due to release `2024.4.1`, more precisely this commit : https://github.com/bitwarden/clients/commit/77cfa8a5ad9ab355896b3a5a76998d5c15c8a823#diff-8ff1ef69519807ae86fc872374b223656c9459d1b8b0304e8a2b602182b68f98R1349

### Operating System

macOS

### Web Browser

Chrome

### Build Version

2024.4.2

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment]
Hmm, I checked out your linked PR.

I'm wondering if it makes more sense to return early from the method if the element has not been cached, rather than process it. In the context of that intersection observer, if an element hasn't been previously cached then it likely shouldn't be triggering the update in either regard... it might not be entirely wrong to add the element to the list of autofill elements... but again, given the context of the intersection observer, we should only be re-evaluating visibility if the element has been previously found in the DOM.

**Comment by cagonzalezcs** [comment]
Resolved by https://github.com/bitwarden/clients/pull/9279

**Comment by sysmat** [comment]
error still present in chrome: Version 125.0.6422.113 (Official Build) (64-bit)

**Comment by noefleury** [comment]
> error still present in chrome: Version 125.0.6422.113 (Official Build) (64-bit)

Yes because the last release `2024.5.0` was made before the merged fix. Should be available soon.

**Comment by jurck222** [comment]
error still comes up

chrome: Version 125.0.6422.142 (Official Build) (64-bit)

BitWarden: 2024.5.1

**Comment by sysmat** [comment]
in angula2 with zone "monkey patch" browser is also problem with this extension, site not working properly

**Comment by sianami123** [comment]
bootstrap-legacy-autofill-overlay.js:6247  Uncaught TypeError: Cannot read properties of undefined (reading 'domQueryService')
    at checkPageContainsShadowDom (bootstrap-legacy-autofill-overlay.js:6247:14)
    at bootstrap-legacy-autofill-overlay.js:869:53
edge Version 132.0.2957.140 (Official build) (64-bit)
