### ISSUE TITLE
Safari extension locked constantly 

### ISSUE THREAD

**Issue by N1ck0-1as** [bitwarden/clients#9850]
### Steps To Reproduce

1. Use the last release of Bitwarden Safari's extension in the Mac App Store (which one fix auto-fill)
2. Use Biometric to unlock extension
3. Open several times the extension: sometimes it will be locked and Biometric does not unlock. You have to retrieve several times or enter master password
4. You can use "reload / recharger" to have the issue (see screenshots)

### Expected Result

Extension must be unlocked when biometric is used with good credentials for the active tab and keep unlocked every time the extension is opened

### Actual Result

Extension's DOM seems to be not refreshed when biometric is called to unlock. And bad or no credentials are auto-fill when the extension is unlocked.
You have to open 2, 3, 4 times the extension to see it unlocked and display credentials

### Screenshots or Videos

<img width="554" alt="Capture d’écran 2024-06-27 à 01 04 57" src="https://github.com/bitwarden/clients/assets/167800824/24128af8-4624-434b-9947-411ad4b8a7ed">
<img width="485" alt="Capture d’écran 2024-06-27 à 01 05 08" src="https://github.com/bitwarden/clients/assets/167800824/b3cedc69-dec6-4b10-9f4c-cc8e0bfd1b2e">
<img width="407" alt="Capture d’écran 2024-06-27 à 01 05 28" src="https://github.com/bitwarden/clients/assets/167800824/1ee00627-03ab-4d6c-804e-f2a32a6715fc">

When you click several times on "refresh", sometimes, the extension will be locked. No issue with Edge / Chrome extension.
<img width="389" alt="Capture d’écran 2024-06-27 à 01 26 24" src="https://github.com/bitwarden/clients/assets/167800824/4061e3fb-45a8-4f0a-80f6-5288eef34021">

### Operating System

macOS

### Operating System Version

14.5

### Web Browser

Safari

### Browser Version

17.5

### Build Version

2024.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Grinchii** [comment]
Also Passkeys on Safari are literally unusable cause of this Bug. 

It asks me for the Fingerprint 10time in a row, but it won't unlock... After repeatedly closing and trying it again, it sometime works, but hardly able to call this workable at the moment.

**Comment by vordenken** [comment]
Please fix this bitwarden is literally unusable atm on macOS.
Thanks for your awesome work bitwarden team!

**Comment by trmartin4** [comment]
Hello!

We have verified that this will be resolved with https://github.com/bitwarden/clients/pull/10050, which has been merged and will be included in an upcoming release.  I will leave this open until the feature has been released, but I wanted to let you know that we have identified the cause and have addressed it.

**Comment by syneart** [comment]
Hi,
I found that [#10050](https://github.com/bitwarden/clients/pull/10050) was already merged on July 12, 2024, and I have also updated to v2024.7.1, but the issue still persists ...

**Comment by trmartin4** [comment]
@syneart can you confirm your vault timeout settings for us?

**Comment by syneart** [comment]
> @syneart can you confirm your vault timeout settings for us?

Okay, my vault timeout is set to 'Immediately' and the timeout action is set to 'Lock'.

**Comment by syneart** [comment]
Hi, @trmartin4 
Here is the current situation.
Safari version: Version 17.5 (19618.2.12.11.6)

https://github.com/user-attachments/assets/84103b4c-108f-4b1d-9706-711297c56d04

**Comment by quexten** [comment]
Hi, thanks for providing the additional details.

This bug is most likely resolved by https://github.com/bitwarden/clients/pull/10241 . I have tested the "immediately" vault timeout on it and the behaviour from your recording does not seem to appear.

**Comment by syneart** [comment]
Hi, 

That sounds like good news! 
I hope in the next release version I can try to see if the issue has been fixed.

**Comment by marcolaux** [comment]
Is this already in the stable App Store release? As it got merged 2 weeks ago (time of writing) I feel the need to point out that I also still experience the issue.

**Comment by stevedenney3** [comment]
Hello, I'm encountering a similar issue. As per suggestion from Bitwarden technical support, I'm adding details of the issue I'm seeing, in the hopes it is helpful (and hopefully not too redundant).

Behavior: Clicking on the extension icon often results in the app looking as if it’s waiting for the vault to be unlocked, but that’s not correct. Within about 10-20 seconds, a retry will show the matching vault login entries, as expected. This behavior is NOT consistent - sometimes it works without delay. I can’t detect any pattern in the behavior. Have tried “Clear Storage” in the Safari extension settings, but no apparent change.

Desktop app: v. 2024.7.1 (27455)
Extension: v. 2024.7.1
MacBook OS: Sonoma 14.6.1 (14.6.1 (23G93)), 2.4 GHz 8-Core Intel Core i9, 32 GB 2400 MHz DDR4
Safari: Version 17.5 (19618.2.12.11.6)
No apparent memory leak; current Bitwarden extension memory usage is about 97MB
My Vault Timeout in the extension is set to “Never”, with the Vault Timeout Action set to “Lock”.
This is a recent issue (only started happening within the last couple of months or so; sorry not to be more precise).

There’s one wrinkle which I want to bring to your attention: Through experimentation, I’ve discovered that although the extension *looks*as if it’s waiting to be unlocked, it actually is not! Attempting to unlock – or not – seems to have no effect on how long the extension actually takes to display the vault contents. Whether with or without an unlock attempt, clicking elsewhere and then back on the extension (as you describe) will eventually show the matching vault login entries, as expected. This behavior is NOT consistent - sometimes it works with a single retry; other times, it takes multiple retries (between 10-20 seconds in total) before the vault contents are finally shown.

**Comment by 4rianton** [comment]
Same issue... almost unusable on Safari. Patiently waiting for a fix.

**Comment by austenlennon** [comment]
Same here.... I have to click on the icon several times.... meanwhile the wrong information shows up in the boxes.

**Comment by syneart** [comment]
> Hi, thanks for providing the additional details.
> 
> This bug is most likely resolved by #10241 . I have tested the "immediately" vault timeout on it and the behaviour from your recording does not seem to appear.

Thank you @quexten.

This issue should have been fixed in Version: 2024.8.0.  After updating, it has been resolved. Thanks again!

**Comment by trmartin4** [comment]
Thank you @syneart for verifying!  We'll close this issue as resolved.

**Comment by austenlennon** [comment]
It is still. problem with my Sonoma machine... Bitwarden Inc. 2015-2024 Version: 2024.7.1 Server version: 2024.8.0

**Comment by 4rianton** [comment]
> It is still. problem with my Sonoma machine... Bitwarden Inc. 2015-2024 Version: 2024.7.1 Server version: 2024.8.0

Because you haven't updated your Bitwarden version.

**Comment by austenlennon** [comment]
I must live on Mars. I saw no update but then Apple Store and it then showed the updated. Thank you.

**Comment by 4rianton** [comment]
Likely a phased rollout where you only see it in the combined update screen sometime within a week after the release. To force update, one needs to go to the app page it seems.

**Comment by stevedenney3** [comment]
Piling on to confirm that v2024.8.0 has resolved my issues as well. Thank you!
